### PR TITLE
Testing cleanup from the cesm3_0_beta03/04 "chill" tags for cesm3_0_beta05

### LINKED ISSUE #2801: fsurdat file needed for NEON MOAB site
> I didn't want to open a whole new issue for this BUT...
> In #2500 this test changed from FAIL (expected) to PEND in the SHAREDLIB_BUILD phase
> `SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Bgc.derecho_gnu.clm-NEON-MOAB--clm-PRISM`
> with this error `CLMBuildNamelist::add_default() : No default value found for fsurdat.`
>
> Same on izumi:
> `SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Bgc.izumi_nag.clm-NEON-MOAB--clm-PRISM`

_Originally posted by @slevis-lmwg in https://github.com/ESCOMP/CTSM/issues/2310#issuecomment-2372367434_
___
I'm elevating this to its own issue because now the `cs.status` output is confusing, and the expected failure isn't detected.

### PR DESCRIPTION
**Pull request by ekluzek**
### Description of changes

Fix a list of issues mostly for testing that came in with the cesm3_0_beta03 and cesm3_0_beta04 tags for the science "chill" deadline bringing in the baseline science capabilities needed for the cesm3_0 release.

List of things:
- New polarcap grid
- Fix use_init_interp for several resolutions that had problems
- Remove clm5_1 physics option
- Newly needed surface datasets added to auto build in Makefile for mksurfdata_esmf
- Fix several individual tests that were failing
- Update to submodules to ones roughly based on cesm3_0_beta04
- Add graceful error checking to the FATES parameter file tests that will get it working in some cases

### Specific notes

Contributors other than yourself, if any: @slevis-lmwg @adamrher @samsrabin 

CTSM Issues Fixed (include github issue #): The individual PR's to this branch have the list of things resolved.
  Fixes #2801 

Are answers expected to change (and if so in what way)? No

Any User Interface Changes (namelist or namelist defaults changes)? No

Does this create a need to change or add documentation? Did you do so? No No

Testing performed, if any: will do regular testing

### CODE REVIEW

File: bld/CLMBuildNamelist.pm [hunk 1]
```diff
@@ -678,6 +678,11 @@ sub setup_cmdl_chk_res {
   }
 }
 
+sub begins_with
+{
```
Comment (ekluzek) [inline bld/CLMBuildNamelist.pm:682]: This is making a bunch of perl assumptions in regard to syntax that are unintuitive, so at least need some comments to explain.

**Review by ekluzek — COMMENTED** [review]
I just saw one thing that I thought needed at least some comments to explain.

**Review by slevis-lmwg — APPROVED** [review]
Happy to see all these cumulative changes coming in! Thank you, Erik.

**Comment by ekluzek** [comment]
There's a few unexpected fails in the Derecho/Izumi fates testlist:

ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdLandUse	(SETUP)		EXPECTED (SHAREDLIB_BUILD)
ERS_Lm12.1x1_brazil.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesFireLightningPopDens	(NLCOMP RUN)
ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.izumi_nag.clm-FatesColdLandUse	(SETUP)		EXPECTED (SHAREDLIB_BUILD)
ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.izumi_nag.clm-FatesColdPRT2	(CREATE_NEWCASE)		EXPECTED (RUN)
ERS_D_Ld5.1x1_brazil.I2000Clm50FatesCruRsGs.izumi_nag.clm-FatesColdHydro	(CREATE_NEWCASE)		
SMS_Lm3_D_Mmpi-serial.1x1_brazil.I2000Clm50FatesCruRsGs.izumi_nag.clm-FatesColdHydro	(CREATE_NEWCASE)

File: cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands [hunk 2]
```diff
@@ -0,0 +1,85 @@
+#!/bin/bash
+
+# Make sure the environment is setup to run the FATES modify parameter file tool
+
+# Function to check for errors and abort
+check_error () {
+   # Arguments: error, message
+   if [ $# != 2 ]; then
+      echo "Wrong number of arguments to check_error"
```
Comment (samsrabin) [inline cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands:9]: Add `>&2` to send to `STDERR` instead of `STDOUT`.

File: cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+   fi
+   error=$1
+   msg=$2
+   if [ $error != 0 ]; then
+      echo "ERROR: Command failed"
+      echo $msg
```
Comment (samsrabin) [inline cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands:15]: Add `>&2` to send to `STDERR` instead of `STDOUT` (both lines here).

File: cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+      echo "conda was found"
+   fi
+   noconda=0
+fi
+
+# Check that  the modify script exists and can be used
+
+MODIFY_FATES_PARAMFILE="$FATESDIR/tools/modify_fates_paramfile.py"
+if [ ! -f $MODIFY_FATES_PARAMFILE ]; then
+   echo "$MODIFY_FATES_PARAMFILE does NOT exist"
```
Comment (samsrabin) [inline cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands:58]: Add `>&2` to send to `STDERR` instead of `STDOUT`.

File: cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+      if [ $DEBUG ]; then
+         echo "conda activate ctsm_pylib was successful"
+      fi
+   else
+      echo "Make sure your python environment can run $MODIFY_FATES_PARAMFILE"
+      echo "One way to do that is to add conda to your environment"
+      echo "    then activate the ctsm_pylib environemnt"
+      echo "    in some cases you may have to add conda activate ctsm_pylib in your startup files"
+      echo "    ctsm_pylib is created at the top level of CTSM using py_env_create"
+      exit 1
```
Comment (samsrabin) [inline cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands:81]: Add `>&2` to send to `STDERR` instead of `STDOUT` (all above lines).

File: cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+   echo "$MODIFY_FATES_PARAMFILE was found"
+fi
+
+$MODIFY_FATES_PARAMFILE --help >& /dev/null
+error=$?
+if [ $error != 0 ]; then
+   echo "$MODIFY_FATES_PARAMFILE can NOT be successfully run"
+   if [ $noconda == 1 ]; then
+      echo "Attempting to activate the conda ctsm_pylib environment"
+      conda activate ctsm_pylib
```
Comment (ekluzek) [inline cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands:70]: In the Monday standup we decided we should have a two step check at this point:

- conda run -n ctsm_pylib (and then add it into the MODIFY_FATES_PARAMFILE variable)
- and then the conda activate
- fail if neither of those work

File: cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands [hunk 7]
```diff
@@ -0,0 +1,85 @@
+#!/bin/bash
```
Comment (ekluzek) [inline cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands:1]: Another way this could be done, is to add several similar type of scripts into something like a ...

cime_config/usermods_dirs/_include

so it could be used by both testmods and user-mods as well as being a place where similar error checking type bash shell_command scripts could be put. If in one directory the Shell syntax of

``` shell
#!/bin/bash
. $script

```

would need to be used. There's some strangeness to how the include user-mod structure works, so this might be a good way to go. And everything in that directory could be something designed to run interactively as I've set this one up. And that might facilitate adding some automated testing around running these scripts.

**Comment by ekluzek** [comment]
I'm getting some tests that are failing due to a STOP_N issue. I think it's because cime ER tests don't work with 15 days (or any unit for 15)? So the workaround might just to do something like _Ld20 rather than _Ld15.

File: cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands (hunk 7 above)
Comment (ekluzek) [reply cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands:1]: I'm leaving this as an include testmod for now. But, I'll start an issue about potential changes here. And I think the bash way might be the way to go. I'm not for certain though...

Resolving for now.

File: cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands (hunk 6 above)
Comment (ekluzek) [reply cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands]: I brought the above in now. On Derecho the "conda run" form is working.

File: cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands (hunk 5 above)
Comment (ekluzek) [reply cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands]: Done

File: cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands (hunk 4 above)
Comment (ekluzek) [reply cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands]: Done

File: cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands (hunk 3 above)
Comment (ekluzek) [reply cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands]: Done

File: cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands (hunk 2 above)
Comment (ekluzek) [reply cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands]: Done

File: bld/CLMBuildNamelist.pm (hunk 1 above)
Comment (ekluzek) [reply bld/CLMBuildNamelist.pm:684]: @slevis-lmwg see what I've added below to address this.

File: doc/ChangeLog [hunk 8]
```diff
@@ -1,4 +1,265 @@
...
+Purpose and description of changes
+----------------------------------
+
+Fix a list of issues mostly for testing that came in with the cesm3_0_beta03 and cesm3_0_beta04 tags
+for the science "chill" deadline bringing in the baseline science capabilities needed for the cesm3_0 release.
+
+List of things:
+
+- New polarcap grid
+- Fix use_init_interp for several resolutions that had
```
Comment (slevis-lmwg) [inline doc/ChangeLog:16]: This sentence seems incomplete.

File: doc/ChangeLog [hunk 9]
```diff
@@ -1,4 +1,265 @@
...
+- Remove clm5_1 physics option
+- Newly needed surface datasets added to auto build in Makefile for mksurfdata_esmf
+- Fix several individual tests that were failing
+- Update to submodules to ones roughly based on cesm3_0_beta04
+- Add graceful error checking to the FATES parameter file tests that will get it working in some cases
+
+Contributors
+------------
+    @slevis-lmwg @ekluzek @adamrher
```
Comment (slevis-lmwg) [inline doc/ChangeLog:25]: I would add @samsrabin due to his contribution in #2801

File: doc/ChangeLog [hunk 10]
```diff
@@ -1,4 +1,265 @@
...
+
+Changes to tests or testing:
+   Changes to lilac/sspmatrixcn tests needed for cime update
+   Clm51 tests changed to Clm60
+   C96 tests changed to C96_C96_mt232
+   Exact restart monthly length tests changed to days because of cime testing update
+   Exact restart 15 day length tests changed to 20 because of a cime testing bug
+   Some additional VR grid tests
+   FatesColdLandUse test requires a long name transient test now
+   New testmod include directory (FatesSetupParam) to setup modifying FATES parameter file, testmods requiring it use it
```
Comment (slevis-lmwg) [inline doc/ChangeLog:96]:
```suggestion
   New testmod include directory (FatesSetupParam) to setup modifying FATES parameter file, testmods requiring its use
```

Not clear as written, so I'm not sure whether my suggested edit is correct.

File: doc/ChangeLog [hunk 11]
```diff
@@ -1,4 +1,265 @@
...
+   Add a unit-tester to the FatesSetupParam directory to make sure it's functions work correctly
```
Comment (slevis-lmwg) [inline doc/ChangeLog:97]:
```suggestion
   Add a unit-tester to the FatesSetupParam directory to make sure its functions work correctly
```
...just a typo

File: doc/ChangeLog [hunk 12]
```diff
@@ -1,4 +1,265 @@
...
+   PFUNIT testing build infrastructure updated to use full ESMF library
+
+Testing summary: regular + fates + ctsm_sci
```
Comment (slevis-lmwg) [inline doc/ChangeLog:100]: Just a reminder that this section is pending.

**Review by slevis-lmwg — APPROVED** [review]
@ekluzek I requested a few changes to the ChangeLog.

File: bld/CLMBuildNamelist.pm (hunk 1 above)
Comment (slevis-lmwg) [reply bld/CLMBuildNamelist.pm:684]: I like it.

**Comment by ekluzek** [comment]
aux_clm, fates, ctsm_sci testing on Izumi and Derecho are all passing as expected. With the exception of this test:

ERS_L761.1x1_smallvilleIA.IHistClm50BgcCropQianRs.derecho_gnu.clm-smallville_dynurban_monthly   (XML)

Which has an XML failure.

**Comment by ekluzek** [comment]
OK, changing that last test so that it's length is 765 rather than 761 gets it to work. So now all of the testing is passing as expected.

File: doc/ChangeLog [hunk 13]
```diff
@@ -1,4 +1,266 @@
...
+  Add support for new grid: ne0np4.POLARCAP.ne30x4
+  Add support for f19 and f45 16-pft surface datasets
+  Fix some finidat issues for: f19, VR grids
+  Remove more mention of vichydro in namelist defaults
+
+Notes of particular relevance for developers:
+---------------------------------------------
+
+Caveats for developers (e.g., code that is duplicated that requires double maintenance):
+   I think we should expand the shell_commands unit testing I added in FatesSetupParam.
```
Comment (ekluzek) [inline doc/ChangeLog:75]: @glemieux I'd like to get your thoughts on this section I have here. I think we should meet to discuss it a bit, and talk about it in an upcoming CTSM SE meeting.

FYI: I'll probably resolve this conversation before you get a chance to look at it, just to finish the PR.

File: doc/ChangeLog (hunk 12 above)
Comment (ekluzek) [reply doc/ChangeLog:101]: Updated

File: doc/ChangeLog (hunk 9 above)
Comment (ekluzek) [reply doc/ChangeLog]: Done

File: doc/ChangeLog (hunk 8 above)
Comment (ekluzek) [reply doc/ChangeLog]: Fixed by adding a single word to finish it.

**Comment by ekluzek** [comment]
In my local's on Derecho and Izumi, this was correct in terms of having ctsm5.3.013 merged in. So I just remerged in master and pushed it and it then corrected the files here. So that part is resolved now.

There's one namelist test I'm looking at now. But, almost done...

File: bld/CLMBuildNamelist.pm [hunk 14]
```diff
@@ -4751,8 +4765,6 @@ sub setup_logic_fates {
               my $fname = remove_leading_and_trailing_quotes( $nl->get_value($var) );
               if ( ! defined($nl->get_value($var))  ) {
                  $log->fatal_error("$var is required when use_fates_inventory_init is set" );
-              } elsif ( ! -f "$fname" ) {
```
Comment (ekluzek) [inline bld/CLMBuildNamelist.pm:4754]: I removed the check for file existence here, because it was too early and caused problems. The check for file existence is a general thing that should be done for all filenames anyway, so doesn't need to have special code to handle it for each one here.

However, this now is still failing to check for file existance at the right time, which causes a build-namelist test to fail. I'm looking into this now...

Comment (ekluzek) [reply bld/CLMBuildNamelist.pm:4754]: Ahh, the file existence checking is in add_default and these filenames are in the testmods rather than going into the namelist_defaults. So I'll make an issue to move them to namelist_defaults, which will then take care of checking for existance.

The other check for file existence happens in a case with the check_input_data step. So it will fail at that point if the file doesn't exist.
