### PR TITLE
ctsm5.4.036: Complete the FATES-CLM nitrogen coupling

### LINKED ISSUE #3378: Completing the FATES-CLM nitrogen coupling
I think of this as the parent issue: https://github.com/NGEET/fates/issues/1270

Currently we can only send synthetic uptake boundary conditions to FATES, and send nothing back to CLM.

This issue will address coupling to CLM's:
- Uptake competition code
- Nitrogen fixation code

In meeting with @rgknox and @adrifoster we discussed that I should focus on the
`else  !----------NITRIF_DENITRIF-------------!`
section of SoilBiogeochemCompetitionMod.F90 (<-- for guidance see Allocation in https://github.com/E3SM-Project/E3SM/pull/4325)
and on new bc_in lines in utils/clmfates_interfaceMod.F90.
@rgknox suggested that for now FATES need not worry about `.not. use_nitrif_denitrif`.

**Testing starting from ctsm5.3.065 (fates: sci.1.84.0_api.40.0.0):**
A motivation behind this update is to perform single-point FATES-MIMICS simulations, so I modified this existing test as below
`ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.izumi_nag.clm-FatesColdPRT2`
Side notes about PRT2 tests:
- This one fails on izumi_nag as per https://github.com/NGEET/fates/issues/983
- Currently PRT2 tests set `fates_cnp_prescribed_nuptake = 1` and `fates_cnp_prescribed_puptake =1` as per https://github.com/ESCOMP/CTSM/issues/2624

Single-point tests
`PASS ERS_D_Ld30.1x1_brazil.I2000Clm60FatesCrujraRs.derecho_intel.clm-FatesColdPRT2`
Turning on mimics shows that we will need to troubleshoot the FATES-MIMICS coupling:
`FAIL ERS_D_Ld30.1x1_brazil.I2000Clm60FatesCrujraRs.derecho_intel.clm-FatesColdPRT2--clm-mimicsFatesCold`
Fates and fireemis cannot both be true, so...
`FAIL ERS_D_Ld30.1x1_brazil.I2000Clm60FatesCrujraRs.derecho_intel.clm-FatesColdPRT2--clm-mimicsFatesCold--clm-nofireemis` DUMPS CORE and states "floating overflow" in line 1180 SoilBiogeochemDecompCascadeMIMICSMod.F90

So I tried our preexisting FATES-MIMICS test with nofireemis appended
`FAIL ERP_P256x2_Ld30.f45_f45_mg37.I2000Clm60FatesRs.derecho_intel.clm-mimicsFatesCold--clm-nofireemis`
`CH4 Conservation Error in CH4Mod during diffusion, nstep, c, errch4 (mol /m^2.timestep)      1     2     NaN`
Same test in debug mode
`ERP_D_P256x2_Ld30.f45_f45_mg37.I2000Clm60FatesRs.derecho_intel.clm-mimicsFatesCold--clm-nofireemis`
traceback
```
floating overflow
...
floating invalid
...
process killed (SIGTERM)
197  BandDiagonalMod.F90
415  SoilTemperatureMod.F90
883  clm_driver.F90
```
@rgknox suggests switching from intel to gnu for better uninitialized variable catching.
- [x] Made #2261 a sub-issue and updated it with the above FATES-MIMICS test-results.

### PR DESCRIPTION
**Pull request by slevis-lmwg**
### Description of changes
For now see the issue #3378 

Corresponding mods on the FATES side: 
https://github.com/NGEET/fates/pull/1472

[Nutrient enabled FATES handbook](https://docs.google.com/document/d/1I35fGDfKTkn9_8Z6qXot7HZf3ICSpLONd-iFEErAh0k/edit?usp=drive_link)
[FATES CLM N coupling](https://docs.google.com/document/d/1mpBtpCLGJpAGw6R3-nGGY92IWRU3ISvaAUKxvcDVJRw/edit?usp=drive_link)

### Specific notes

Contributors other than yourself, if any:
@rgknox @adrifoster @wwieder 

CTSM Issues Fixed (include github issue #):
#3378 

Are answers expected to change (and if so in what way)?
For non-fates tests expect roundoff diffs due to a change in the order of operations in CNNDynamicsMod.F90 as documented [below](https://github.com/ESCOMP/CTSM/pull/3409#issuecomment-4238969834).

Any User Interface Changes (namelist or namelist defaults changes)?
Yes, see changes to CLMBuildNamelist and namelistdefaults.

Does this create a need to change or add documentation? Did you do so?
Yes, no.

- [x] Todo: add a modification to the PRT2 test, make sure that prescribed P uptake is set to 10. This will ensure that there are no P limitations in fates, when FATES becomes coupled to CLM's N cycle (in future PR). i:e: fates_cnp_prescribed_puptake=10

Initial testing performed
...with the first two commits in this PR:
```
PASS ERS_D_Ld30.1x1_brazil.I2000Clm60FatesCrujraRs.derecho_intel.clm-FatesColdPRT2
PASS ERS_D_Ld30.1x1_brazil.I2000Clm60FatesCrujraRs.derecho_intel.clm-FatesCold
```
Later comments point out that these two tests were inadequate at catching problems, and that I switched to two other tests.

### CODE REVIEW

**Comment by slevis-lmwg** [comment]
With the latest commit, I repeated the two earlier tests and added another to check whether answers have changed from the baseline:
```
PASS ERS_D_Ld30.1x1_brazil.I2000Clm60FatesCrujraRs.derecho_intel.clm-FatesColdPRT2
PASS ERS_D_Ld30.1x1_brazil.I2000Clm60FatesCrujraRs.derecho_intel.clm-FatesCold
FAIL ERP_Ld9.f45_f45_mg37.I2000Clm50FatesRs.derecho_intel.clm-FatesColdAllVars -c /glade/campaign/cgd/tss/ctsm_baselines/ctsm5.3.065
```
The latter fails in case2, after reading the restart file, with a N balance error. 

UPDATE
- See below for suggestions to resolve FAIL
- Add new test ERP_Ld9.f45_f45_mg37.I2000Clm50FatesRs.derecho_intel.clm-FatesColdPRT2 (sanity check first that it meets requirements set forth in the fourth checkbox [here](https://github.com/ESCOMP/CTSM/issues/3378#issuecomment-3189342883), which I think means pointing to an alternate fates paramfile)
- Later comment explains why I decided to revert to preexisting ERS tests and skip adding this ERP test.

**Comment by rgknox** [comment]
Since its failing a FATES configuration that does not have dynamic N, I'm betting that we are running the new uptake portion of the code when we shouldn't.

File: src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90 [hunk 1]
```diff
@@ -991,6 +1038,44 @@ subroutine SoilBiogeochemCompetition (bounds, num_bgc_soilc, filter_bgc_soilc,nu
             end if
          end do ! end of column loops
 
+         ! Set the FATES N uptake fluxes
+
+         if (use_fates) then
```
Comment (slevis-lmwg) [inline src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90]: From today's meeting with Ryan:
```suggestion
         if (col%is_fates(c) .and. fates_parteh_mode == 2) then
```
here and in the other if (use_fates).
This future-proofs this section if we want to run fates columns side-by-side with, say, crop columns.

File: src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90 [hunk 2]
```diff
@@ -319,12 +327,51 @@ subroutine SoilBiogeochemCompetition (bounds, num_bgc_soilc, filter_bgc_soilc,nu
...
+               ci = bounds%clump_index
+               s = clm_fates%f2hmap(ci)%hsites(c)
+               n_pcomp = clm_fates%fates(ci)%bc_out(s)%num_plant_comps
+
+               ! Overwrite the column level demands, since fates plants are all sharing
+               ! the same space, in units per the same square meter, we just add demand
+               ! to scale up to column
+               plant_ndemand(c) = 0._r8
+
+               ! We fill the vertically resolved array to simplify some jointly used code
```
Comment (slevis-lmwg) [inline src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90:346]: Put the if fates_parteh_mode == 2 here and make the else set plant_ndemand(_vr) = 0 to hopefully resolve the N balance error

Comment (slevis-lmwg) [reply src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90:346]: Likely still need to resolve N bal. error when parteh == 2

File: src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90 (hunk 1 above)
Comment (slevis-lmwg) [reply src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90]: First two tests listed above still PASS, so I'm resolving this conversation.

File: src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90 (hunk 2 above)
Comment (slevis-lmwg) [reply src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90:346]: The 3rd test still fails with a N-bal error, and I'm running the 4th test to see what happens:
- I still see indications of badly initialized variables...
- Try uncommenting the harvest lines mentioned in an earlier post
- Consider inconsistent if-statements

Comment (slevis-lmwg) [reply src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90:346]: Rethinking my tests:
1. The 1x1 tests have not helped (I have now removed them)
2. The ERP...PRT2 test fails with
`FAILED to get /glade/derecho/scratch/slevis/ERP_Ld9.f45_f45_mg37.I2000Clm50FatesRs.derecho_intel.clm-FatesColdPRT2.20250814_175600_rzyi7o/case2/ERP_Ld9.f45_f45_mg37.I2000Clm50FatesRs.derecho_intel.clm-FatesColdPRT2.20250814_175600_rzyi7o/fates_params_prt2_prescribed_np.nc`
so I will go back and try the preexisting PRT2 test and the closest non-PRT2:
```
./create_test ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdPRT2 -c /glade/campaign/cgd/tss/ctsm_baselines/fates-sci.1.84.0_api.40.0.0-ctsm5.3.066
./create_test ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdLUH2 -c /glade/campaign/cgd/tss/ctsm_baselines/fates-sci.1.84.0_api.40.0.0-ctsm5.3.066
```
- [x] before this PR's changes: caseids 20250815_113417_sx4t8g and 20250815_113743_mr25bk
- [x] with 01671b91627dc38617ed285cd52e39e05496539d: caseids 20250815_114817_ilbscj and 20250815_114840_il903r
- [x] FAIL with the latest commit: 
- [x] testid 20250815_120848_v9vgmh gives this Traceback <-- TROUBLESHOOTING THIS CASE
```
error (65): floating invalid
Image              PC                Routine            Line        Source
libpthread-2.31.s  0000149243D098C0  Unknown               Unknown  Unknown
cesm.exe           0000000002F2D454  soilbiogeochemcom         608  SoilBiogeochemCompetitionMod.F90
cesm.exe           0000000003FCD516  cndrivermod_mp_cn         474  CNDriverMod.F90
cesm.exe           0000000001A99BF1  cnvegetationfacad        1030  CNVegetationFacade.F90
cesm.exe           0000000000A8B2C7  clm_driver_mp_clm        1058  clm_driver.F90
```
**UPDATE I had placed the new code in the `if (.not. use_nitrif_denitrif)` opposite to what I should have done. I have now updated the code (while still keeping the new code in the ".not." section). Testing PASSed 20250825_174700_7w8gx9**

  - [x] testid 20250815_120902_1msot7 gives the same Traceback, but also before the Traceback this error
```
Nan values for pftareafrac. dumping site info.
----------------------------------------
Site Coordinates
----------------------------------------
latitude                    =   -74.0000000000000
longitude                   =    255.000000000000
```
Same test PASSed with the above update 20250826_101645_52b4zd
- Tests now work, though should they DIFF from the baseline?

**Comment by slevis-lmwg** [comment]
Enabled fixation and ran the same tests:
```
PASS ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdPRT2 -c /glade/campaign/cgd/tss/ctsm_baselines/fates-sci.1.84.0_api.40.0.0-ctsm5.3.066
PASS ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdLUH2 -c /glade/campaign/cgd/tss/ctsm_baselines/fates-sci.1.84.0_api.40.0.0-ctsm5.3.066
```
PRT2 still b4b with the baseline.
LUH2 now DIFF from the baseline.

PASS The same tests with the code change for harvest (same results relative to the baseline).

**Comment by slevis-lmwg** [comment]
Worked on the next checkbox in the issue (#3378), submitted the same tests, and after some troubleshooting:
PASS PRT2 and b4b with the baseline.
PASS LUH2 and DIFF from the baseline as before.

**Comment by slevis-lmwg** [comment]
```
OK ./build-namelist_test.pl
OK ./run_sys_tests -s fates -c fates-sci.1.84.0_api.40.0.0-ctsm5.3.066/ --skip-generate
REDO ./run_sys_tests -s aux_clm -c ctsm5.3.066 --skip-generate
```
Notes:
- Gnu and nvhpc tests needed a bug-fix that intel didn't catch (next commit). 
- Then the fates test-suite worked (I didn't repeat aux_clm for now)
- Many tests DIFFer from the baseline.
- The PRT2 test had the expected NLCOMP change, though no DIFFs from the baseline (even after rebuilding/rerunning):
```
  BASE: suplnitro = 'ALL'
  COMP: suplnitro = 'NONE'
```

**Comment by slevis-lmwg** [comment]
Updated the fates paramfile (see next commit) and submitted these two again
```
./create_test ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdLUH2 -c /glade/campaign/cgd/tss/ctsm_baselines/fates-sci.1.84.0_api.40.0.0-ctsm5.3.066
./create_test ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdPRT2 -c /glade/campaign/cgd/tss/ctsm_baselines/fates-sci.1.84.0_api.40.0.0-ctsm5.3.066
```
The first (LUH2) same as before (DIFF from baseline) since nothing changed for it.
The second (ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdPRT2.C.20250923_141838_qjxqou) now:
- DIFF from baseline and
- FAIL COMPARE_base_rest suggesting variable(s) missing from restart, I suspect

**Comment by slevis-lmwg** [comment]
Submitted the same 2 tests
```
./create_test ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdLUH2 -c /glade/campaign/cgd/tss/ctsm_baselines/fates-sci.1.84.0_api.40.0.0-ctsm5.3.066
./create_test ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdPRT2 -c /glade/campaign/cgd/tss/ctsm_baselines/fates-sci.1.84.0_api.40.0.0-ctsm5.3.066
```
now with the error check suggested in https://github.com/NGEET/fates/issues/1454 (see corresponding commit https://github.com/NGEET/fates/pull/1472/commits/97839f187e44599c3183afa34fd5de16982560a3 in https://github.com/NGEET/fates/pull/1472)

- PRT2 same behavior: variable(s) missing from restart?
- LUH2 FAIL triggered the new error message (turns out it shouldn't have, yet, becase fates_parteh_mode was 1):
```
hlm_name cannot be CLM while prescribed_puptake == 0, because the CLM does not do prognostic phosphorus. Exiting.
ERROR in FatesInterfaceMod.F90 at line 919
```

UPDATE Repeating with 2025/12/10 updates:
- PRT2 same behavior: COMPARE_base_rest
- LUH2 didn't trigger the new error message in its new location and passed, as expected; when I added `fates_parteh_mode = 2`, another similar error got triggered, and Ryan and I decided to keep the latter and remove the former
- Test on izumi 2025/12/16 while derecho is down (gnu, intel, nag):
`ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.izumi_*.clm-FatesColdLUH2` FAILs in RUN as per https://github.com/ESCOMP/CTSM/issues/2653, so I tried
`PASS ERS_D_Mmpi-serial_Ld5.1x1_brazil.I2000Clm50FatesRs.izumi_nag.clm-FatesCold` with parteh_mode = 1
`FAIL ERS_D_Mmpi-serial_Ld5.1x1_brazil.I2000Clm50FatesRs.izumi_nag.clm-FatesCold` with parteh_mode = 2 as expected
- [x] Troubleshoot restart issue (SL, but also Ryan offered to look into it)
  - `FAIL ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.izumi_nag.clm-FatesColdPRT2` as expected https://github.com/ESCOMP/CTSM/issues/3183 but it may work if I shorten the test to Ld10
  - Return to derecho: UPDATED my fates-cn branches to ctsm5.4.004/sci.1.88.0_api.42.0.0
LUH2 DIFF from latest baseline fates-sci.1.88.0_api.42.0.0-ctsm5.4.001 EXPECTED due to update to .004
PRT2 FAIL COMPARE_base_rest
  - The [first post mentioning the restart problem](https://github.com/ESCOMP/CTSM/pull/3409#issuecomment-3325413045) made me think of rerunning the original PRT2 against the latest baseline `fates-sci.1.89.0_api.43.0.0-ctsm5.4.005` without https://github.com/ESCOMP/CTSM/pull/3409/commits/391a0231f07223a03d0f1f75391253931aefcb03 and that PASSed despite the NLCOMP change of suplnitro from 'ALL' to 'NONE'.
- [x] Add new tests (from meeting with Ryan 2025/12/16):
  - [x] PRT2_synthN (nuptake = 10) to reproduce what used to happen before coupling
  - [x] PRT2_suplnAll that swaps namelist setting suplnitro from NONE to ALL. Initially failed with expected namelist error that we decided to remove:
```
ERROR : CLMBuildNamelist::setup_logic_supplemental_nitrogen() : supplemental Nitrogen (suplnitro) is NOT set to NONE, FATES is on, and FATES-SP is not active, but fates_parteh_mode is 2, so Nitrogen is active; change suplnitro back to NONE
```

**Comment by slevis-lmwg** [comment]
The reason for the [last commit](https://github.com/ESCOMP/CTSM/pull/3409/commits/25ea275239cb9c2eb60c9d1647ce0c44be029ca3) is explained in https://github.com/ESCOMP/CTSM/issues/2653#issuecomment-3663058871.

**Comment by slevis-lmwg** [comment]
After the latest updates, I'm submitting these tests with ./create_test:
```
PASS ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdPRT2_synthN
BASELINE ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdLUH2
COMPARE_base_rest ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdPRT2
COMPARE_base_rest ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdPRT2_suplnAll
```
LUH2 diffs from fates-sci.1.89.0_api.43.0.0-ctsm5.4.005:
FATES_HET_RESP                   7.5810E-16            NORMALIZED  2.1208E-07
FATES_NEP                        7.5810E-16            NORMALIZED  2.8903E-07
Ryan suggests not worrying about this one, as this may originate in an LUH2 issue.

----

PRT2 diffs in the same 38 fields in base.cprnc.out as in cprnc.out.
- Ryan thinks that the restart problem comes from the FATES side because the problem appears when nitrogen becomes interactive
- For troubleshooting, it may help to run 2 time steps in single-point, possibly turning off pieces of code, e.g. any litter generation and exudation
- @rgknox offered to start some of this troubleshooting

PRT2_suplnAll h0a restart diffs in
SNOWICE                          5.9583E-04            NORMALIZED  1.0038E-05
SNOWLIQ                          6.3099E-04            NORMALIZED  5.7300E-03
but more fields in h1a and cpl...

----

Add this non-fates test to the list of four tests above:
`SMS.f10_f10_mg37.I2000Clm50BgcCrop.derecho_intel.clm-crop`

File: src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90 (hunk 2 above)
Comment (slevis-lmwg) [reply src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90:346]: Resolving this one. The last comment about baseline diffs may or may not still be relevant.

File: bld/CLMBuildNamelist.pm [hunk 3]
```diff
@@ -3349,6 +3349,18 @@ sub setup_logic_supplemental_nitrogen {
...
+    my $parteh_mode = $nl->get_value('fates_parteh_mode');
+    if ( ($parteh_mode == 1) &&  ($suplnitro !~ /ALL/) && not &value_is_true( $nl_flags->{'use_fates_sp'}) ) {
+      $log->fatal_error("supplemental Nitrogen (suplnitro) is NOT set to ALL, FATES is on, " .
+                        "and FATES-SP is not active, but fates_parteh_mode is 1, so Nitrogen is not active. " .
+                        "Change suplnitro back to ALL");
+    }
+    if ( ($parteh_mode == 2) &&  ($suplnitro !~ /NONE/) && not &value_is_true( $nl_flags->{'use_fates_sp'}) ) {
+      $log->fatal_error("supplemental Nitrogen (suplnitro) is NOT set to NONE, FATES is on, " .
+                        "and FATES-SP is not active, but fates_parteh_mode is 2, so Nitrogen is active; " .
+                        "change suplnitro back to NONE");
```
Comment (slevis-lmwg) [inline bld/CLMBuildNamelist.pm]: Remove this new check because in parteh_mode = 2 we want to allow either NONE or ALL suplnitro.

File: bld/CLMBuildNamelist.pm [hunk 4]
```diff
@@ -3349,6 +3349,18 @@ sub setup_logic_supplemental_nitrogen {
         $log->warning("There is no need to use a bgc_spinup mode when supplemental Nitrogen is on for all PFT's, as these modes spinup Nitrogen" );
       }
     }
+
+    my $parteh_mode = $nl->get_value('fates_parteh_mode');
+    if ( ($parteh_mode == 1) &&  ($suplnitro !~ /ALL/) && not &value_is_true( $nl_flags->{'use_fates_sp'}) ) {
+      $log->fatal_error("supplemental Nitrogen (suplnitro) is NOT set to ALL, FATES is on, " .
+                        "and FATES-SP is not active, but fates_parteh_mode is 1, so Nitrogen is not active. " .
+                        "Change suplnitro back to ALL");
```
Comment (slevis-lmwg) [inline bld/CLMBuildNamelist.pm]: Here remove the sp condition because irrelevant.

File: bld/CLMBuildNamelist.pm (hunk 3 above)
Comment (slevis-lmwg) [reply bld/CLMBuildNamelist.pm]: Or replace check with not allowing parteh_mode = 2 and sp mode together.

**Comment by slevis-lmwg** [comment]
Troubleshoot ctsm side PR https://github.com/slevis-lmwg/ctsm/pull/19 
paired with fates side PR https://github.com/slevis-lmwg/fates/pull/3

**Comment by slevis-lmwg** [comment]
```
./create_test ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdPRT2_synthN
./create_test ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdLUH2 -c /glade/campaign/cgd/tss/ctsm_baselines/fates-sci.1.89.0_api.43.0.0-ctsm5.4.005
./create_test ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdPRT2 -c /glade/campaign/cgd/tss/ctsm_baselines/fates-sci.1.89.0_api.43.0.0-ctsm5.4.005
./create_test ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdPRT2_suplnAll
./create_test SMS.f10_f10_mg37.I2000Clm50BgcCrop.derecho_intel.clm-crop -c /glade/campaign/cgd/tss/ctsm_baselines/ctsm5.4.005
```
PASS synthN
BASELINE LUH2
COMPARE_base_rest PRT2
COMPARE_base_rest PRT2-suplnAll
PASS SMS

**Comment by slevis-lmwg** [comment]
@rgknox to follow up...
If this PR and the fates-side PR seem ready to you, then I think we should look for the source of the restart failure. I know you offered to help with that, but let me know if you would like me to start looking into it.

**Comment by rosiealice** [comment]
Hi @rgknox @slevis-lmwg . We have a new post-doc in Oslo (Shelby Sunquist, who just finished her PhD at N-Arizona with @adrifoster on her committee :) ) who will continue Betty's work on linking MIMICS+ into CLM-BGC by extending it to work with FATES. She has just started this week, and so I wanted to figure out the status of this coupling.  Is the primary issue with the PR as it stands that it fails the ERS test?  I wonder if it might be possible for her to run/build off of this code in parellel with the effort to fix whatever the residual bug is?

**Comment by slevis-lmwg** [comment]
@rosiealice 
Ryan and I checked in. We think that Shelby's work can start, while Ryan and I look into the restart problem. Ryan suggests that it could be helpful for all of us to meet soon.

**Comment by rgknox** [comment]
Agreed.  I highly recommend we meet as well. We could help transfer knowledge about the nuances of a N limited FATES simulations that we learned through coupling with E3SM, such as important parameters, spin-up phases, etc.

**Comment by rosiealice** [comment]
Thanks @slevis-lmwg & @rgknox , that's good to know.    We will circle back to this once Shelby is spun up on life in general after Easter (she only just arrived about a week ago...)

**Comment by rgknox** [comment]
I'm investigating the ERS restart test failure and tried two tests. In the first test, I forced litter flux from FATES to CLM to be zero. This did not have any impact on restarts, suggesting that the bug is either not related to restarting litter fluxes, or simply is not relegated to restarting litter fluxes.  I also forced the fine-root profile that fates sends to the nitrogen allocation scheme to zero, and this did generate b4b restarts. My next test will be to go into the allocation code, and set the fates-side boundary conditions to constants, and see if that works. That will tell us if the problem is restarting clm-side allocation/decomposition variables, of if its fates-side restarting of boundary conditions..  cc @slevis-lmwg

**Comment by slevis-lmwg** [comment]
After the latest updates, I started by submitting `SMS.f10_f10_mg37.I2000Clm50BgcCrop.derecho_intel.clm-crop.C.20260406_124851_rch8g6` and this passed. I got pulled in other directions for the day, but my plan is to
- confirm the other tests work...

**FAIL PRT2_synthN RUN**
```
forrtl: severe (408): fort: (2): Subscript #1 of the array PLANT_NH4_UPTAKE_FLUX has value 2 which is greater than the upper bound of 1
cesm.exe           0000000001DFE98F  set_restart_vecto        2713  FatesRestartInterfaceMod.F90
cesm.exe           000000000099C9D5  restart                  1935  clmfates_interfaceMod.F90
cesm.exe           0000000000939B38  clm_instrest              620  clm_instMod.F90
cesm.exe           0000000000D32E1C  restfile_write            132  restFileMod.F90
cesm.exe           0000000000917E69  clm_drv                  1529  clm_driver.F90
cesm.exe           0000000000856DC4  modeladvance              913  lnd_comp_nuopc.F90
```
----
**FAIL LUH2 RUN** turns out to expected as per #3789 
```
negative area           1           1           1  -999.0
ENDRUN: ERROR in EDInitMod.F90 at line 608
```
----
PASS PRT2, just no baseline to compare
PASS PRT2_suplnAll
PASS SMS (as already mentioned above the bullet)
- resolve failures, then start a full aux_clm test

**Comment by slevis-lmwg** [comment]
@rgknox two tests failed (PRT2_synthN and LUH2) and three passed. See error msgs in the previous post.

Looking into the first of these. I think we set `allocate(bc_in%plant_nh4_uptake_flux(1,1))` in main/FatesInterfaceMod.F90 because coupled_p_uptake and coupled_n_uptake are false. The failure then occurs in main/FatesRestartInterfaceMod.F90 in this loop:
```
icomp = 0
do_patch: do while(associated(cpatch))
   do while(associated(ccohort))
      if (hlm_parteh_mode == carbon_nitrogen_phosphorus) then
         icomp=icomp+1
         this%rvars(ir_nh4uptakeflux_co)%r81d(io_idx_co) = bc_in(s)%plant_nh4_uptake_flux(icomp,1)
```
My first inclination is to move `icomp = 0` into the first do loop and try the tests again. So far:

FAIL PRT2_synthN RUN
FAIL LUH2 RUN expected
FAIL PRT2 COMPARE_base_rest
FAIL PRT2_suplnAll COMPARE_base_rest
PASS SMS

so my first intuition was wrong, and I will restore FatesRestartInterfaceMod.F90 and try changing the allocate statement in FatesInterfaceMod.F90.

PASS PRT2_synthN RUN
FAIL LUH2 RUN expected
PASS PRT2 COMPARE_base_rest
PASS PRT2_suplnAll COMPARE_base_rest
PASS SMS

Fixed!

**Comment by slevis-lmwg** [comment]
Starting aux_clm on derecho + izumi:
`./run_sys_tests -s aux_clm -c ctsm5.4.029 --skip-generate`

RUN failures to investigate (none on izumi) in /glade/derecho/scratch/slevis/tests_0408-165737de
```
ERI_D_Ld9.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhenCamLndTuningMode
ERP_P128x2_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen
ERP_P64x2_D_Ld5.f10_f10_mg37.I1850Clm50Bgc.derecho_intel.clm-ciso--clm-matrixcnOn_ignore_warnings
SMS.f45_f45_mg37.I2000Clm60FatesSpRsGs.derecho_nvhpc.clm-FatesColdSatPhen
```
- ERP_P64 reran four times and then a fifth after a clean build and it continues to fail, so I'm abandoning, even though an ERP_D test with the same "matrix" error passed with one rerun.
- ERI, ERP_P128, SMS give `ERROR: fates_parteh_mode=carbon_only must have suplnitro set to suplnAll. ERROR in controlMod.F90 at line 504`. Erik and I looked at CLMBuildNamelist.pm and resolved quickly.
- [x] Erik suggested I add a build-namelist_test.pl test confirming this failure triggers in the build phase.
----
Also, should we expect the DIFFs from baseline in the following tests (some also on izumi, but I did not list them) due to the diff between `sci.1.91.3_api.43.1.0-25-g21c1bcbe` and the baseline `sci.1.91.1_api.43.1.0`? Though I see diffs in non-Fates cases, too. Erik suggests introducing the changes in a b4b step followed by a non-b4b step if possible.
```
    FAIL ERI_D_Ld9.f10_f10_mg37.I1850Clm45Bgc.derecho_gnu.clm-default BASELINE ctsm5.4.029: DIFF
    FAIL ERP_D_P64x2_Ld3.f10_f10_mg37.I2000Clm45BgcCrop.derecho_gnu.clm-no_subgrid_fluxes BASELINE ctsm5.4.029: DIFF
    FAIL ERS_D_Ld20.f45_f45_mg37.I2000Clm50FatesRs.derecho_gnu.clm-FatesColdTwoStreamNoCompFixedBioGeo BASELINE ctsm5.4.029: DIFF
    FAIL ERS_D_Ld6.f10_f10_mg37.I1850Clm45BgcCrop.derecho_gnu.clm-clm50CMIP6frc BASELINE ctsm5.4.029: DIFF
    FAIL LGRAIN2_Ly2_P128x1.f10_f10_mg37.I1850Clm45BgcCrop.derecho_gnu.clm-ciso--clm-cropMonthOutput BASELINE ctsm5.4.029: DIFF
    FAIL LREPRSTRUCT_Ly2_P128x1.f10_f10_mg37.I1850Clm45BgcCrop.derecho_gnu.clm-ciso--clm-cropMonthOutput BASELINE ctsm5.4.029: DIFF
    FAIL SMS_D_Ld5.f10_f10_mg37.I2000Clm50FatesRs.derecho_gnu.clm-FatesCold BASELINE ctsm5.4.029: DIFF
    FAIL SMS_Ld5.f10_f10_mg37.I1850Clm45BgcCrop.derecho_gnu.clm-till--clm-remove_residues BASELINE ctsm5.4.029: DIFF
    FAIL SMS_Ld5_PS.f19_g17.I2000Clm50FatesRs.derecho_gnu.clm-FatesCold BASELINE ctsm5.4.029: DIFF
    FAIL ERI_D_Ld20.f10_f10_mg37.I2000Clm50Fates.derecho_intel.clm-FatesCold BASELINE ctsm5.4.029: DIFF
    FAIL ERI_D_Ld20.f45_f45_mg37.I2000Clm50FatesRs.derecho_intel.clm-FatesColdTwoStream BASELINE ctsm5.4.029: DIFF
    FAIL ERI_D_Ld9.f45_f45_mg37.I2000Clm60Fates.derecho_intel.clm-FatesColdCamLndTuningMode BASELINE ctsm5.4.029: DIFF
    FAIL ERP_D_P64x2_Ld3.f10_f10_mg37.I2000Clm50BgcCru.derecho_intel.clm-noFUN_flexCN BASELINE ctsm5.4.029: DIFF
    FAIL ERP_D_P64x2_Ld3.f10_f10_mg37.I2000Clm50BgcCru.derecho_intel.clm-noFUN_flexCN--clm-matrixcnOn_ignore_warnings BASELINE ctsm5.4.029: DIFF (EXPECTED FAILURE)
    FAIL ERP_Ld9.f45_f45_mg37.I2000Clm50FatesRs.derecho_intel.clm-FatesColdAllVars BASELINE ctsm5.4.029: DIFF
    FAIL ERP_P64x2_D_Ld5.f10_f10_mg37.I1850Clm45BgcCrop.derecho_intel.clm-crop BASELINE ctsm5.4.029: DIFF
    FAIL ERP_P64x2_D_Ld5.f10_f10_mg37.I1850Clm45BgcCru.derecho_intel.clm-ciso BASELINE ctsm5.4.029: DIFF
    FAIL ERP_P64x2_D_Ld5.f10_f10_mg37.I1850Clm45BgcCru.derecho_intel.clm-default BASELINE ctsm5.4.029: DIFF
    FAIL ERP_P64x2_D_Ld5.f10_f10_mg37.IHistClm45BgcCru.derecho_intel.clm-decStart BASELINE ctsm5.4.029: DIFF
    FAIL ERP_P64x2_Ld396.f10_f10_mg37.IHistClm60Bgc.derecho_intel.clm-monthly--clm-matrixcnOn_ignore_warnings BASELINE ctsm5.4.029: DIFF (EXPECTED FAILURE)
    FAIL ERS_D_Ld5.f10_f10_mg37.I2000Clm50Fates.derecho_intel.clm-FatesCold BASELINE ctsm5.4.029: DIFF
    FAIL ERS_D_Ld6.f10_f10_mg37.I1850Clm45BgcCrop.derecho_intel.clm-clm50CMIP6frc BASELINE ctsm5.4.029: DIFF
    FAIL ERS_Ld30.f45_f45_mg37.I2000Clm50FatesRs.derecho_intel.clm-FatesColdFixedBiogeo BASELINE ctsm5.4.029: DIFF
    FAIL ERS_Ld30.f45_f45_mg37.I2000Clm50FatesRs.derecho_intel.clm-FatesColdSizeAgeMort BASELINE ctsm5.4.029: DIFF
    FAIL ERS_Ly5_P128x1.f10_f10_mg37.IHistClm45BgcCrop.derecho_intel.clm-cropMonthOutput BASELINE ctsm5.4.029: DIFF
    FAIL ERS_P128x1_Ld765.f10_f10_mg37.I2000Clm60Fates.derecho_intel.clm-FatesColdNoComp BASELINE ctsm5.4.029: DIFF
    FAIL REP_P64x2_Ld396.f10_f10_mg37.IHistClm60Bgc.derecho_intel.clm-monthly--clm-matrixcnOn_ignore_warnings BASELINE ctsm5.4.029: DIFF (EXPECTED FAILURE)
    FAIL SMS_D_Ld5.f10_f10_mg37.I2000Clm50FatesRs.derecho_intel.clm-FatesCold BASELINE ctsm5.4.029: DIFF
    FAIL SMS_D_Ld65.f10_f10_mg37.I2000Clm45BgcCropQianRs.derecho_intel.clm-FireLi2014Qian BASELINE ctsm5.4.029: DIFF
    FAIL SMS_D_Lm6_P256x1.f45_f45_mg37.I2000Clm50FatesRs.derecho_intel.clm-FatesCold BASELINE ctsm5.4.029: DIFF
    FAIL SMS_Ld5.f10_f10_mg37.I1850Clm45BgcCrop.derecho_intel.clm-crop BASELINE ctsm5.4.029: DIFF
    FAIL SMS_Ld5.f10_f10_mg37.I2000Clm50FatesRs.derecho_intel.clm-FatesCold BASELINE ctsm5.4.029: DIFF
    FAIL SMS_Ln9.f09_f09_mg17.I1850Clm45Bgc.derecho_intel.clm-clm45cam4LndTuningModeZDustSoilErod BASELINE ctsm5.4.029: DIFF
```

**Comment by slevis-lmwg** [comment]
Testing on derecho after the latest updates:
- [x] ./run_sys_tests -s fates -c fates-sci.1.92.0_api.44.0.0-ctsm5.4.031 --skip-generate
- [x] build-namelist_test.pl

Before I try `./run_sys_tests -s aux_clm -c ctsm5.4.032 --skip-generate`, I will look into the diffs from baseline with this test from the above list of failures:
`SMS_Ld5.f10_f10_mg37.I1850Clm45BgcCrop.derecho_intel.clm-crop`
Largest diffs (grepped for "E-0") out of a total of 53 fields with non-zero diffs suggest roundoff diffs:
```
 RMS CH4_SURF_AERE_SAT                2.0582E-10            NORMALIZED  3.9956E-03
 RMS CH4_SURF_DIFF_SAT                8.6639E-14            NORMALIZED  1.6418E-04
 RMS FCH4                             4.7957E-15            NORMALIZED  1.3812E-04
 RMS FCH4TOCO2                        4.7907E-12            NORMALIZED  8.6788E-05
 RMS FCH4_DFSAT                       8.9717E-20            NORMALIZED  2.3733E-07
 RMS NEM                              4.7907E-12            NORMALIZED  1.2779E-04
 RMS SOM_C_LEACHED                    1.3173E-25            NORMALIZED  1.5688E-09
 RMS TOTCOLCH4                        6.1704E-10            NORMALIZED  1.9915E-09
 RMS CONC_O2_SAT                      4.7118E-03            NORMALIZED  4.4369E-02
```
- The test gives similar/same diffs when I reverse the mods in SoilBiogeochemCompetitionMod.F90
- The test returns b4b when I reverse the mods in CNNDynamicsMod.F90
- [x] Starting aux_clm to confirm all DIFFs go away, though Fates tests appear to fail now

File: src/biogeochem/CNNDynamicsMod.F90 [hunk 5]
```diff
@@ -239,17 +239,14 @@ subroutine CNNFixation(num_soilc, filter_soilc, &
...
                ! %ema_npp is Smoothed [gc/m2/yr]
-               !npp = clm_fates%fates(clump_index)%bc_out(s)%ema_npp/(dayspyr*secspday)
-               ! FATES N cycling is not yet active, so runs are supplemented anyway
-               ! this will be added when FATES N cycling is completed.
-               npp = 0._r8
+               npp = clm_fates%fates(clump_index)%bc_out(s)%ema_npp
             else
-               npp = col_lag_npp(c)
+               ! need to put npp in units of gC/m^2/year here first
+               npp = col_lag_npp(c) * secspday * dayspyr
```
Comment (slevis-lmwg) [inline src/biogeochem/CNNDynamicsMod.F90:245]: This update and line 249 below likely explain (at least in part) the changing answers when running without fates. Keep looking for more potential culprits and then revert all of them (temporarily) to test for b4b.

File: src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90 [hunk 6]
```diff
@@ -319,12 +328,53 @@ subroutine SoilBiogeochemCompetition (bounds, num_bgc_soilc, filter_bgc_soilc,nu
             end do
          end do
 
-         do j = 1, nlevdecomp
-            do fc=1,num_bgc_soilc
-               c = filter_bgc_soilc(fc)      
-               sum_ndemand_vr(c,j) = plant_ndemand(c) * nuptake_prof(c,j) + potential_immob_vr(c,j)
+         bgc_soilc_loop1: do fc = 1, num_bgc_soilc
```
Comment (slevis-lmwg) [inline src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90:333]: This update likely contributes to the changing answers when running without fates. This one seems more difficult to revert to perform b4b testing, but I will look into it.

File: src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90 [hunk 7]
```diff
@@ -337,7 +387,7 @@ subroutine SoilBiogeochemCompetition (bounds, num_bgc_soilc, filter_bgc_soilc,nu
                   nlimit(c,j) = 0
                   fpi_vr(c,j) = 1.0_r8
                   actual_immob_vr(c,j) = potential_immob_vr(c,j)
-                  sminn_to_plant_vr(c,j) = plant_ndemand(c) * nuptake_prof(c,j)
+                  sminn_to_plant_vr(c,j) = plant_ndemand_vr(c,j)
```
Comment (slevis-lmwg) [inline src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90:392]: This and other changes in this file likely contribute to the changing answers when running without fates...

File: src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90 (hunk 6 above)
Comment (slevis-lmwg) [reply src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90:333]: Maybe not. Resolving.

File: src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90 (hunk 7 above)
Comment (slevis-lmwg) [reply src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90:392]: Probably not, so resolving.

File: src/biogeochem/CNNDynamicsMod.F90 (hunk 5 above)
Comment (slevis-lmwg) [reply src/biogeochem/CNNDynamicsMod.F90:245]: Good news, the b4b diffs in non-Fates cases go away when I revert the order-of-operation changes in CNNDynamicsMod.F90, and the list of non-Fates failures is the expected:
```
./run_sys_tests -s aux_clm -c ctsm5.4.032 --skip-generate
./cs.status.fails | grep -v NLCOMP | grep -v PASS | grep -v Fates
```
```
    FAIL ERI_Ld41.f10_f10_mg37.I2000Clm60BgcCrop.derecho_gnu.clm-default COMPARE_branch_hybrid (EXPECTED FAILURE)
    FAIL ERP_P64x2_D_Ld3.f10_f10_mt232.IHistClm60BgcCropCrujra.derecho_gnu.clm-default--clm-all_outputs COMPARE_base_rest (EXPECTED FAILURE)
    FAIL ERP_D_P64x2_Ld10.f10_f10_mg37.I2000Clm60Bgc.derecho_intel.clm-Hillslope RUN time=91 (EXPECTED FAILURE)
    PEND ERP_D_P64x2_Ld10.f10_f10_mg37.I2000Clm60Bgc.derecho_intel.clm-Hillslope COMPARE_base_rest
    FAIL ERP_P64x2_Ld396.f10_f10_mg37.IHistClm60Bgc.derecho_intel.clm-monthly--clm-matrixcnOn_ignore_warnings BASELINE ctsm5.4.032: DIFF (EXPECTED FAILURE)
    FAIL ERS_D_Ld7_Mmpi-serial.1x1_smallvilleIA.IHistClm50BgcCropRs.derecho_intel.clm-decStart1851_noinitial RUN time=96 (EXPECTED FAILURE)
    FAIL REP_P64x2_Ld396.f10_f10_mg37.IHistClm60Bgc.derecho_intel.clm-monthly--clm-matrixcnOn_ignore_warnings COMPARE_base_rep2 (EXPECTED FAILURE)
    FAIL REP_P64x2_Ld396.f10_f10_mg37.IHistClm60Bgc.derecho_intel.clm-monthly--clm-matrixcnOn_ignore_warnings BASELINE ctsm5.4.032: DIFF (EXPECTED FAILURE)
    FAIL SMS_D_Ly6_Mmpi-serial.1x1_smallvilleIA.IHistClm45BgcCropQianRs.derecho_intel.clm-cropMonthOutput RUN time=40 (EXPECTED FAILURE)
    FAIL SUBSETDATAPOINT_Ld5_D_Mmpi-serial.CLM_USRDAT.I2000Clm60BgcCropCrujra.derecho_intel.clm-default RUN time=47 (EXPECTED FAILURE)
    FAIL SUBSETDATAREGION_Ld5_D_Mmpi-serial.CLM_USRDAT.I2000Clm60BgcCropCrujra.derecho_intel.clm-default RUN time=66 (EXPECTED FAILURE)
```
(For the record, FATES cases fail with SIGFPE with this code reverted, which is fine because I reverted only to show b4b in all non-Fates cases.)

**Comment by slevis-lmwg** [comment]
Now repeat `./run_sys_tests -s aux_clm -c ctsm5.4.032 --skip-generate` with the latest commit:
- [x] izumi
- [x] derecho
Three tests ran out of walltime that didn't fail before, so I will not spend additional time on them for now:
```
ERS_Ly5_Mmpi-serial.1x1_smallvilleIA.I1850Clm50BgcCrop.derecho_gnu.clm-ciso_monthly RUN
ERS_Ly5_Mmpi-serial.1x1_smallvilleIA.I1850Clm50BgcCrop.derecho_gnu.clm-ciso_monthly--clm-matrixcnOn RUN
ERS_Ly5_P128x1.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-cropMonthOutput--clm-matrixcnOn_ignore_warnings RUN
```
Known issue #3840

**Comment by slevis-lmwg** [comment]
@rgknox testing seems satisfactory to me, so this PR and its fates counterpart are ready for your final review, unless you think of anything else that we need to work on here.

File: cime_config/testdefs/testmods_dirs/clm/FatesColdLUH2/user_nl_clm [hunk 8]
```diff
@@ -27,7 +27,7 @@ hist_fincl1       = 'FATES_NCOHORTS', 'FATES_TRIMMING', 'FATES_AREA_PLANTS',
 'FATES_DEMOTION_CARBONFLUX', 'FATES_PROMOTION_CARBONFLUX',
 'FATES_MORTALITY_CFLUX_CANOPY', 'FATES_MORTALITY_CFLUX_USTORY',
 'FATES_NEP', 'FATES_HET_RESP', 'FATES_FIRE_CLOSS', 'FATES_FIRE_FLUX_EL',
-'FATES_CBALANCE_ERROR', 'FATES_ERROR_EL', 'FATES_LEAF_ALLOC',
```
Comment (glemieux) [inline cime_config/testdefs/testmods_dirs/clm/FatesColdLUH2/user_nl_clm:30]: Do we have an issue to note why this shouldn't be included here?  I could find anything specific outside of a conflict with using it during ST3 or SP mode tests.

File: bld/CLMBuildNamelist.pm [hunk 9]
```diff
@@ -3320,12 +3320,12 @@ sub setup_logic_supplemental_nitrogen {
...
-		  'suplnitro', 'use_cn'=>$nl_flags->{'use_cn'}, 'use_crop'=>$nl_flags->{'use_crop'});
+                 'suplnitro', 'use_cn'=>$nl_flags->{'use_cn'}, 'use_crop'=>$nl_flags->{'use_crop'});
 
-  } elsif ( $nl_flags->{'bgc_mode'} eq "fates" && not &value_is_true( $nl_flags->{'use_fates_sp'})  ) {
-      # Or... if its fates but not fates-sp
+  } elsif ( $nl_flags->{'bgc_mode'} eq "fates" ) {
+      # Or... if its fates
       add_default($opts, $nl_flags->{'inputdata_rootdir'}, $definition, $defaults, $nl,
-		  'suplnitro', 'use_fates'=>$nl_flags->{'use_fates'});
+                 'suplnitro', 'fates_parteh_mode'=>remove_leading_and_trailing_quotes($nl->get_value('fates_parteh_mode')));
```
Comment (glemieux) [inline bld/CLMBuildNamelist.pm]: check this

File: cime_config/testdefs/testlist_clm.xml [hunk 10]
```diff
@@ -3900,7 +3900,27 @@
...
     <options>
       <option name="wallclock">00:40:00</option>
-      <option name="comment">Exact restart debug test covering Fates CNP nutrients mode.</option>
+      <option name="comment">Exact restart debug test covering Fates CNP nutrients mode (P still prescribed in clm).</option>
+    </options>
+  </test>
+  <test name="ERS_D_Ld30" grid="f45_f45_mg37" compset="I2000Clm60FatesRs" testmods="clm/FatesColdPRT2_suplnAll">
+    <machines>
+      <machine name="derecho" compiler="intel" category="fates"/>
+      <machine name="lawrencium-lr3" compiler="intel" category="fates"/>
```
Comment (glemieux) [inline cime_config/testdefs/testlist_clm.xml]: @rgknox do you use `lawrencium`?  We should instances of `lawrencium` if we don't think we're going to be using it anytime soon, but that's out of scope for this PR so I'd just make an issue if you agree.

**Review by glemieux — APPROVED** [review]
This looks good.  Thanks again to @slevis-lmwg for the walkthrough.  I just have two questions/comments that should be dealt with via other PRs (if at all).

File: bld/namelist_files/namelist_defaults_ctsm.xml [hunk 11]
```diff
@@ -2737,6 +2733,9 @@ lnd/clm2/surfdata_esmf/NEON/ctsm5.4.0/surfdata_1x1_NEON_TOOL_hist_2000_78pfts_c2
 <use_fates_fixed_biogeog        use_fates=".true."                         >.false.</use_fates_fixed_biogeog>
 <fates_history_dimlevel         use_fates=".true.">2,2</fates_history_dimlevel>
 
+<!-- Supplmental Nitrogen mode -->
+<suplnitro >NONE</suplnitro>
+<suplnitro fates_parteh_mode="carbon_only" >ALL</suplnitro>
```
Comment (ekluzek) [inline bld/namelist_files/namelist_defaults_ctsm.xml:2741]: Doesn't this need the addition of:

```suggestion
<suplnitro use_fates=".true." >ALL</suplnitro>
<suplnitro use_fates=".true." fates_parteh_mode="carbon_only" >ALL</suplnitro>
```

File: src/main/clm_varctl.F90 [hunk 12]
```diff
@@ -324,9 +324,16 @@ module clm_varctl
 
   integer, public            :: fates_seeddisp_cadence = iundef         ! 0 => no seed dispersal
                                                                         ! 1, 2, 3 => daily, monthly, or yearly dispersal
-  integer, public            :: fates_parteh_mode = -9                  ! 1 => carbon only
-                                                                        ! 2 => C+N+P (not enabled yet)
-                                                                        ! no others enabled
+  character(len=256), public :: fates_parteh_mode = ''                  ! FATES Plant Allocation Reactions and Transport Hypotheses
```
Comment (ekluzek) [inline src/main/clm_varctl.F90]: I really love upgrading this to a character description. So much easier to understand!

File: bld/namelist_files/namelist_defaults_ctsm.xml (hunk 11 above)
Comment (ekluzek) [reply bld/namelist_files/namelist_defaults_ctsm.xml:2741]: OK, it looks like this was an intentional change. I only wonder about making this more obvious in comments though.

File: bld/namelist_files/namelist_definition_ctsm.xml [hunk 13]
```diff
@@ -708,8 +708,8 @@ Toggle to turn on the FATES model
 Functionally Assembled Terrestrial Ecosystem Simulator (FATES)
 </entry>
 
-<entry id="fates_parteh_mode" type="integer" category="physics"
-        group="clm_inparm" valid_values="1,2">
+<entry id="fates_parteh_mode" type="char*256" category="physics"
```
Comment (ekluzek) [inline bld/namelist_files/namelist_definition_ctsm.xml]: You could make the string shorter. If you use SHR_KIND_CS it would be 80 characters which is still longer than needed for this. But, you could use it in the code and have it consistent here.

```suggestion
<entry id="fates_parteh_mode" type="char*256" category="physics"
```

File: src/main/clm_varctl.F90 (hunk 12 above)
Comment (ekluzek) [inline src/main/clm_varctl.F90]: I do suggest either hardcoding the length to something shorter (and agree with the value in the namelist defintion above), or use SHR_KIND_CS which has a length of 80.

You can add a use statement to shr_kind, for it, and then use it similar to other string lengths.
```suggestion
  character(len=CS), public :: fates_parteh_mode = ''                  ! FATES Plant Allocation Reactions and Transport Hypotheses
```

``` fortran
use shr_kind_mod, only: CS=>SHR_KIND_CS
```

File: src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90 [hunk 14]
```diff
@@ -545,15 +595,59 @@ subroutine SoilBiogeochemCompetition (bounds, num_bgc_soilc, filter_bgc_soilc,nu
             end do
          end do
 
+         bgc_soilc_loop2: do fc = 1, num_bgc_soilc
```
Comment (ekluzek) [inline src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90:603]: Add a comment to say what this loop is doing.

**Review by ekluzek — APPROVED** [review]
I did a fairly quick skim, and only have a few suggestions. There was one thing I was concerned about, but realized it was done on purpose. So I only wonder if more comments might help with the supplemental nitrogen setting?

@glemieux had some comments to handle. And we should have him and @samsrabin finish a review as well.

The other thing I wondered about this is how FATES carbon_nitrogen will interact with other parts of Nitrogen in CLM like LUNA? That likely will take some scientific validation, but we might want to have some warnings or comments about some of that?

File: bld/namelist_files/namelist_definition_ctsm.xml [hunk 15]
```diff
@@ -708,8 +708,8 @@ Toggle to turn on the FATES model
...
+       group="clm_inparm" valid_values="carbon_only,carbon_nitrogen">
 Switch deciding which nutrient model to use in FATES.
 (Only relevant if FATES is on)
```
Comment (ekluzek) [inline bld/namelist_files/namelist_definition_ctsm.xml:714]: The other thing I wonder about is making a note to say that this is experimental.

```suggestion
(Only relevant if FATES is on)
(fates_parteh_mode='carbon_nitrogen' is EXPERIMENTAL and UNSUPPORTED)
```

File: bld/namelist_files/namelist_definition_ctsm.xml (hunk 13 above)
Comment (samsrabin) [reply bld/namelist_files/namelist_definition_ctsm.xml]: Big big thank you for switching to char instead of int!

**Comment by rosiealice** [comment]
Hi @ekluzek thanks for this. I just wanted to say that this code does not intersect with LUNA, as Vcmax is an input oarameter in FATES and so we don't for now handle any of the acclimation processes that LUNA predicts. This also goes for FUN and the 'Flex-CN' (I'm unsure if we still call it that) functionality.

**Comment by slevis-lmwg** [comment]
Note to self: Open new documentation issues to update Technote and User's Guide.

**Comment by slevis-lmwg** [comment]
Blocked by https://github.com/NGEET/fates/pull/1472 for now.

File: cime_config/testdefs/testlist_clm.xml (hunk 10 above)
Comment (rgknox) [reply cime_config/testdefs/testlist_clm.xml]: yes, we can get rid of lawrencium, I never use that machine

File: src/main/clm_varctl.F90 (hunk 12 above)
Comment (samsrabin) [reply src/main/clm_varctl.F90]: Yeah, this should use `CS`.

File: src/main/clm_varpar.F90 [hunk 16]
```diff
@@ -53,8 +53,16 @@ module clm_varpar
...
-                                                      ! (allows for multiple harvests in a calendar year in case harvest occurs near
+                                                      ! (allows for multiple harvests in a calendar
+                                                      ! year in case harvest occurs near
                                                       ! beginning/end of year);
+
+  ! These strings define the clm-fates coupling, i.e. which chemical species
+  ! are cycled between the two, see corresponding values for fates_parteh_mode:
+  ! bld/namelist_files/namelist_definition_ctsm.xml
+  character(len=256), public, parameter :: clmfates_carbon_only = 'carbon_only'
+  character(len=256), public, parameter :: clmfates_carbon_nitrogen = 'carbon_nitrogen'
```
Comment (samsrabin) [inline src/main/clm_varpar.F90]: Again, these should be converted to use length `CS` instead of a magic number.

File: src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90 (hunk 14 above)
Comment (samsrabin) [reply src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90:603]: Yeah; how does it differ from the `fates1` loop?

**Review by samsrabin — COMMENTED** [review]
Looks great! Just some minor things agreeing with Erik.

File: cime_config/testdefs/testmods_dirs/clm/FatesColdLUH2/user_nl_clm (hunk 8 above)
Comment (slevis-lmwg) [reply cime_config/testdefs/testmods_dirs/clm/FatesColdLUH2/user_nl_clm:30]: I will try putting this back.

File: cime_config/testdefs/testlist_clm.xml (hunk 10 above)
Comment (slevis-lmwg) [reply cime_config/testdefs/testlist_clm.xml]: done

File: bld/namelist_files/namelist_defaults_ctsm.xml (hunk 11 above)
Comment (slevis-lmwg) [reply bld/namelist_files/namelist_defaults_ctsm.xml:2741]: @ekluzek I'm happy to add comments. Can you specify what needs clarification? As is, this says that the fates "carbon_only" option sets suplnitro to ALL, while other cases set suplnitro to NONE. Previously, every fates case needed suplnitro set to ALL. Is that what you're looking for? I will add a comment like that preemptively and pls let me know if I'm off the mark.

File: bld/namelist_files/namelist_definition_ctsm.xml (hunk 13 above)
Comment (slevis-lmwg) [reply bld/namelist_files/namelist_definition_ctsm.xml]: Setting to 80 here.

File: src/main/clm_varctl.F90 (hunk 12 above)
Comment (slevis-lmwg) [reply src/main/clm_varctl.F90]: done

File: src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90 (hunk 14 above)
Comment (slevis-lmwg) [reply src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90:603]: The distinction boils down to the if-statement surrounding the two loops:
- bgc_soilc_loop1 is in the `if (.not. use_nitrif_denitrif) then`, while
- bgc_soilc_loop2 in the `else  !----------NITRIF_DENITRIF-------------!`

Given the length of the code in each part, I will add comments clarifying this.

Comment (slevis-lmwg) [reply src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90:603]: done

File: bld/namelist_files/namelist_definition_ctsm.xml (hunk 15 above)
Comment (slevis-lmwg) [reply bld/namelist_files/namelist_definition_ctsm.xml:714]: done

File: src/main/clm_varpar.F90 (hunk 16 above)
Comment (slevis-lmwg) [reply src/main/clm_varpar.F90]: done

**Comment by slevis-lmwg** [comment]
- [x] `./run_sys_tests -s aux_clm -c ctsm5.4.035 -g ctsm5.4.036`
- [x] `./run_sys_tests -s fates -c fates-sci.1.92.4_api.45.0.0-ctsm5.4.036 --skip-generate`
- [x] build-namelist_test
- [x] ChangeLog

File: bld/namelist_files/namelist_defaults_ctsm.xml (hunk 11 above)
Comment (slevis-lmwg) [reply bld/namelist_files/namelist_defaults_ctsm.xml:2741]: As testing wraps up, I will resolve remaining conversations in prep. for merging.

File: cime_config/testdefs/testmods_dirs/clm/FatesColdLUH2/user_nl_clm (hunk 8 above)
Comment (slevis-lmwg) [reply cime_config/testdefs/testmods_dirs/clm/FatesColdLUH2/user_nl_clm:30]: Worked!
