### PR TITLE
Optionally base GDD20 on per-gridcell windows, not per-hemisphere

### LINKED ISSUE #2460: RXCROPMATURITY_Lm61.f09_g17.IHistClm50BgcCrop.derecho_intel.clm-cropMonthOutput fails in ctsm5.1.dev175
### Brief summary of bug

RXCROPMATURITY_Lm61.f09_g17.IHistClm50BgcCrop.derecho_intel.clm-cropMonthOutput

fails in ctsm5.1.dev175, possibly earlier

### General bug information

**CTSM version you are using:** ctsm5.1.dev175

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** Just the system test

### Details of bug

Looks like case.setup isn't done at the point it's needed which means the .env_mach_specific.sh in the $CASEDIR..gddgen doesn't exist, which is at least one of the problems.

Since the 

.  $CASEDIR.gddgen/.env_mach_specific.sh; CONDA_PREFIX=;  conda activate npl &&  python3 $CTSMROOT/tools/modify_input_files/fsurdat_modifier $CASEDIR.gddgen/modify_fsurdat_allcropseverywhere.cfg

command run is complex it would be good to have some checking proceed it to check for the existence of both the
.env_mach_specific.sh file and the modify_fsurdat config file. It looks like that would be the only things that could be done to break it up into more understandable pieces.

### Important output or errors that show the problem

TestStatus.log

```
 ---------------------------------------------------
2024-04-05 12:32:49: Exception during run:
Command '. /glade/derecho/scratch/erik/ctsm5.1.dev175/cime/scripts/RXCROPMATURITY_Lm61.f09_g17.IHistClm50BgcCrop.derecho_intel.clm-cropMonthOutput.20240405_122456_wckjn4.gddgen/.env_mach_specific.sh; CONDA_PREFIX=;  conda activate npl &&  python3 /glade/derecho/scratch/erik/ctsm5.1.dev175/tools/modify_input_files/fsurdat_modifier /glade/derecho/scratch/erik/ctsm5.1.dev175/cime/scripts/RXCROPMATURITY_Lm61.f09_g17.IHistClm50BgcCrop.derecho_intel.clm-cropMonthOutput.20240405_122456_wckjn4.gddgen/modify_fsurdat_allcropseverywhere.cfg ' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/glade/derecho/scratch/erik/ctsm5.1.dev175/cime_config/SystemTests/systemtest_utils.py", line 52, in run_python_script
    subprocess.run(
  File "/glade/u/apps/opt/conda/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '. /glade/derecho/scratch/erik/ctsm5.1.dev175/cime/scripts/RXCROPMATURITY_Lm61.f09_g17.IHistClm50BgcCrop.derecho_intel.clm-cropMonthOutput.20240405_122456_wckjn4.gddgen/.env_mach_specific.sh; CONDA_PREFIX=;  conda run -n npl python3 /glade/derecho/scratch/erik/ctsm5.1.dev175/tools/modify_input_files/fsurdat_modifier /glade/derecho/scratch/erik/ctsm5.1.dev175/cime/scripts/RXCROPMATURITY_Lm61.f09_g17.IHistClm50BgcCrop.derecho_intel.clm-cropMonthOutput.20240405_122456_wckjn4.gddgen/modify_fsurdat_allcropseverywhere.cfg ' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/glade/derecho/scratch/erik/ctsm5.1.dev175/cime/CIME/SystemTests/system_tests_common.py", line 282, in run
    self.run_phase()
  File "/glade/derecho/scratch/erik/ctsm5.1.dev175/cime_config/SystemTests/rxcropmaturity.py", line 138, in run_phase
    self._run_fsurdat_modifier()
  File "/glade/derecho/scratch/erik/ctsm5.1.dev175/cime_config/SystemTests/rxcropmaturity.py", line 281, in _run_fsurdat_modifier
    stu.run_python_script(
  File "/glade/derecho/scratch/erik/ctsm5.1.dev175/cime_config/SystemTests/systemtest_utils.py", line 64, in run_python_script
    subprocess.run(
  File "/glade/u/apps/opt/conda/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '. /glade/derecho/scratch/erik/ctsm5.1.dev175/cime/scripts/RXCROPMATURITY_Lm61.f09_g17.IHistClm50BgcCrop.derecho_intel.clm-cropMonthOutput.20240405_122456_wckjn4.gddgen/.env_mach_specific.sh; CONDA_PREFIX=;  conda activate npl &&  python3 /glade/derecho/scratch/erik/ctsm5.1.dev175/tools/modify_input_files/fsurdat_modifier /glade/derecho/scratch/erik/ctsm5.1.dev175/cime/scripts/RXCROPMATURITY_Lm61.f09_g17.IHistClm50BgcCrop.derecho_intel.clm-cropMonthOutput.20240405_122456_wckjn4.gddgen/modify_fsurdat_allcropseverywhere.cfg ' returned non-zero exit status 1.

```

### PR DESCRIPTION
**Pull request by samsrabin**
### Description of changes
In the existing code, when using the default CLM crop calendars, `gddmaturity` (maturity requirement; the number of growing degree-days it takes for a crop to mature and be harvested) can vary within some bounds based on climate over the past 20 years. Specifically, CLM looks at some annual "warm period" which differs between the northern and southern hemispheres, which I call the "GDD20 season." This variation allows "farmers" to adapt the "cultivars" (varieties) they grow based on recent climate.

When _prescribing_ maturity requirement, though—with input file `stream_fldFileName_cultivar_gdds`—it's currently not allowed to vary over time. Instead, it's locked in to what's provided in the input file: the mean GDD accumulation in the GGCMI growing period over the 1980-2009 growing seasons.

We want this variation to allow "farmers" to adapt the "varieties" they grow based on whether the recent climate has been warmer or cooler than that baseline 1980-2009 period.

This PR represents the second step toward adding that ability. I'm breaking this work up into separate PRs to keep them manageable:
1. (#2560) Define "recent climate" based on the same "warm period" currently used by default CLM.
2. (This PR) Define "recent climate" based on the GGCMI growing seasons.
3. Restrict adapted `gddmaturity` values to a realistic range.

### Specific notes

**Other features/changes**
- Adds "Cidadinho" test site (like Smallville but in the Southern Hemisphere)
- Fixes PEM test failures resulting from ambiguous nearest neighbors
- Fixes PEM test failures resulting from bad reset of `sowing_reason_perharv_patch`
- Adds RXCROPMATURITYSKIPGEN SystemTest, which is like RXCROPMATURITY but doesn't actually generate GDDs. Allows short testing with existing GDD inputs. Included in aux_clm as `RXCROPMATURITYSKIPGEN_Ld1097.f10_f10_mg37.IHistClm50BgcCrop.derecho_intel.clm-cropMonthOutput`.
- Adds various crop calendar testmods, with some added to aux_clm and crop_calendars test suites.
- Adds output variables `GDD20_BASELINE`, `GDD20_SEASON_START`, `GDD20_SEASON_END`

**Contributors other than yourself, if any:** None

**CTSM Issues Fixed:**
- Contributes to #1928
- Fixes #2460

**Are answers expected to change (and if so in what way)?** Not unless enabling this new, experimental feature.

**Any User Interface Changes (namelist or namelist defaults changes)?**
- Adds namelist logical `stream_gdd20_seasons` (default false). Enabling this automatically sets the relevant input files (see below) to the half-degree GGCMI growing seasons.
- Adds input files `stream_fldFileName_gdd20_season_start` and `_end` (default `''`, unless `stream_gdd20_seasons` is true, in which case the GGCMI sowing and harvest dates are used). Providing either file but `stream_gdd20_seasons = .true.` will cause an error in the build namelist step.
- Adds namelist logical `flush_gdd20` (default false), which if true causes the accumulated GDD20 variables to be reset as soon as possible.
- Adds namelist logical `allow_invalid_gdd20_season_inputs` (default false), which if false will cause a failure upon reading a value in `stream_fldFileName_gdd20_season_start` or `_end` outside the range [1, 365] (or 366 in leap years).

**Does this create a need to change or add documentation? Did you do so?** Documentation will need to be updated when all the PRs in my plan are merged and this feature is considered ready for use. But at this point, things are preliminary enough that I'd have to rewrite whatever docs I added in this PR. So no: I'm adding no documentation here.

**Testing performed, if any:**
- As of 227426345f: aux_clm results are bit-for-bit identical with `ctsm5.2.005`, although there was a build failure in one nag compiler test.
- In a 1958-2010 run at f19 resolution, using the GGCMI-based GDD20 seasons made little difference in most crops. Rice and cotton, however, were decimated. I'm not 100% sure why, so I will plan to include this only as an option, not a default.

### CODE REVIEW

File: src/biogeophys/TemperatureType.F90 [hunk 1]
```diff
@@ -881,7 +897,7 @@ subroutine Restart(this, bounds, ncid, flag, is_simple_buildtemp, is_prog_buildt
     use shr_log_mod     , only : errMsg => shr_log_errMsg
     use spmdMod         , only : masterproc
     use abortutils      , only : endrun
-    use ncdio_pio       , only : file_desc_t, ncd_double, ncd_int
+    use ncdio_pio       , only : file_desc_t, ncd_double, ncd_int, ncd_log
```
Comment (samsrabin) [inline src/biogeophys/TemperatureType.F90:900]: Unused? Revert?

File: src/cpl/share_esmf/cropcalStreamMod.F90 [hunk 2]
```diff
@@ -49,6 +53,9 @@ module cropcalStreamMod
   character(len=CL)       :: stream_fldFileName_gdd20_baseline ! GDD20 baseline stream filename to read
   logical                 :: cropcals_rx ! Used only for setting input files in namelist; does nothing in code, but needs to be here so namelist read doesn't crash
   logical                 :: cropcals_rx_adapt ! Used only for setting input files in namelist; does nothing in code, but needs to be here so namelist read doesn't crash
+  logical                     :: allow_invalid_gdd20_season_inputs ! Fall back on hemisphere "warm periods" in cases of invalid values in stream_fldFileName_gdd20_season_start and _end?
+  character(len=CL)       :: stream_fldFileName_gdd20_season_start ! Stream filename to read for start of gdd20 season
+  character(len=CL)       :: stream_fldFileName_gdd20_season_end ! Stream filename to read for end of gdd20 season
```
Comment (samsrabin) [inline src/cpl/share_esmf/cropcalStreamMod.F90:58]: Make these (and all other files) use `CX` (512) instead of `CL` (256).

File: bld/CLMBuildNamelist.pm [hunk 3]
```diff
@@ -4185,12 +4189,28 @@ sub setup_logic_cropcal_streams {
...
+  if ( &value_is_true($stream_gdd20_seasons)) {
+    add_default($opts, $nl_flags->{'inputdata_rootdir'}, $definition, $defaults, $nl, 'stream_fldFileName_gdd20_season_start');
+    add_default($opts, $nl_flags->{'inputdata_rootdir'}, $definition, $defaults, $nl, 'stream_fldFileName_gdd20_season_end');
+
+    # Check
+    my $gdd20_season_start_file = $nl->get_value('stream_fldFileName_gdd20_season_start') ;
+    my $gdd20_season_end_file = $nl->get_value('stream_fldFileName_gdd20_season_end') ;
+    if ( &string_is_undef_or_empty($gdd20_season_start_file) or &string_is_undef_or_empty($gdd20_season_end_file) ) {
+      $log->message($gdd20_season_start_file);
+      $log->message('abcd');
```
Comment (samsrabin) [inline bld/CLMBuildNamelist.pm:4203]: Delete this line.

File: bld/namelist_files/namelist_defaults_ctsm.xml [hunk 4]
```diff
@@ -1697,15 +1704,18 @@ lnd/clm2/surfdata_esmf/NEON/surfdata_1x1_NEON_TOOL_hist_78pfts_CMIP6_simyr2000_c
...
+<stream_fldFileName_swindow_start cropcals_rx_adapt=".true.">lnd/clm2/cropdata/calendars/processed/swindow_starts_ggcmi_crop_calendar_phase3_v1.01.2000-2000.20231005_145103.tweaked_latlons.nc</stream_fldFileName_swindow_start>
+<stream_fldFileName_swindow_end cropcals_rx_adapt=".true.">lnd/clm2/cropdata/calendars/processed/swindow_ends_ggcmi_crop_calendar_phase3_v1.01.2000-2000.20231005_145103.tweaked_latlons.nc</stream_fldFileName_swindow_end>
+<stream_fldfilename_cultivar_gdds cropcals_rx_adapt=".true.">lnd/clm2/cropdata/calendars/processed/gdds_20230829_161011.tweaked_latlons.nc</stream_fldfilename_cultivar_gdds>
+<stream_fldFileName_gdd20_baseline cropcals_rx_adapt=".true." stream_gdd20_seasons=".false.">lnd/clm2/cropdata/calendars/processed/20230714_cropcals_pr2_1deg.actually2deg.1980-2009.from_GDDB20.interpd_halfdeg.tweaked_latlons.nc</stream_fldFileName_gdd20_baseline>
+<stream_fldFileName_gdd20_baseline cropcals_rx_adapt=".true." stream_gdd20_seasons=".true.">lnd/clm2/cropdata/calendars/processed/gdd20bl.copied_from.gdds_20230829_161011.v2.tweaked_latlons.nc</stream_fldFileName_gdd20_baseline>
```
Comment (samsrabin) [inline bld/namelist_files/namelist_defaults_ctsm.xml:1715]: Why are stream_fldFileName_gdd20_baseline values different based on stream_gdd20_seasons? And why were those values chosen?

File: src/cpl/share_esmf/cropcalStreamMod.F90 [hunk 5]
```diff
@@ -613,6 +736,90 @@ subroutine cropcal_interp(bounds, num_pcropp, filter_pcropp, init, crop_inst)
...
+           gdd20_season_starts(p) = real(dataptr2d_gdd20_season_start(ig,n), r8)
+           gdd20_season_ends(p)   = real(dataptr2d_gdd20_season_end  (ig,n), r8)
+       else
+           write(iulog,'(a,i0)') 'cropcal_interp(), gdd20 seasons: Crop patch has ivt ',ivt
+           call ESMF_Finalize(endflag=ESMF_END_ABORT)
+        endif
+     end do
+
+     ! Handle invalid gdd20 season values
+     if (any(gdd20_season_starts(begp:endp) < 1._r8 .or. gdd20_season_ends(begp:endp) < 1._r8)) then
```
Comment (samsrabin) [inline src/cpl/share_esmf/cropcalStreamMod.F90:795]: Should also check for values that are too high.

File: src/cpl/share_esmf/cropcalStreamMod.F90 [hunk 6]
```diff
@@ -613,6 +736,90 @@ subroutine cropcal_interp(bounds, num_pcropp, filter_pcropp, init, crop_inst)
...
+         ! Fail if not allowing fallback to paramfile sowing windows
+         if ((.not. allow_invalid_gdd20_season_inputs) .and. any(gdd20_season_starts(begp:endp) < 1._r8 .and. patch%wtgcell(begp:endp) > 0._r8 .and. patch%itype(begp:endp) >= npcropmin)) then
+             write(iulog, *) 'At least one crop in one gridcell has invalid gdd20 season start date(s). To ignore and fall back to paramfile sowing windows, set allow_invalid_gdd20_season_inputs to .true.'
```
Comment (samsrabin) [inline src/cpl/share_esmf/cropcalStreamMod.F90:798]: Should say start **or end**.

Comment (samsrabin) [reply src/cpl/share_esmf/cropcalStreamMod.F90:798]: "To ignore and fall back to paramfile sowing windows **for such crop-gridcells**"

File: cime_config/testdefs/testlist_clm.xml [hunk 7]
```diff
@@ -3660,16 +3660,41 @@
...
+      <machine name="derecho" compiler="intel" category="rxcropmaturity"/>
+      <machine name="derecho" compiler="intel" category="crop_calendars"/>
     </machines>
     <options>
       <option name="wallclock">12:00:00</option>
       <option name="comment">This test is designed to test the ability to prescribe crop sowing dates and maturity requirements. It first performs a GDD-generating run, then calls Python code to generate the maturity requirement file. This is then used in a sowing+maturity forced run, which finally is tested to ensure correct behavior.</option>
     </options>
   </test>
 
+  <test name="RXCROPMATURITY_Lm61" grid="f10_f10_mg37" compset="IHistClm60BgcCrop"  testmods="clm/cropMonthOutput">
```
Comment (samsrabin) [inline cime_config/testdefs/testlist_clm.xml:3675]: This 10x15 version and the 1-degree version don't both need to be in rxcropmaturity and crop_calendars suites.

File: cime_config/testdefs/testmods_dirs/clm/RxCropCalsAdaptFlush/user_nl_clm [hunk 8]
```diff
@@ -0,0 +1,2 @@
+
+flush_gdd20 = .true.
```
Comment (samsrabin) [inline cime_config/testdefs/testmods_dirs/clm/RxCropCalsAdaptFlush/user_nl_clm:2]: Add a test to crop_calendars suite that exercises this testmod

File: cime_config/testdefs/testmods_dirs/clm/RxCropCalsAdaptGGCMI/user_nl_clm [hunk 9]
```diff
@@ -0,0 +1,5 @@
+
+stream_gdd20_seasons = .true.
+flush_gdd20 = .true.
+!TODO SSR: Try without this once you have half-degree inputs
```
Comment (samsrabin) [inline cime_config/testdefs/testmods_dirs/clm/RxCropCalsAdaptGGCMI/user_nl_clm:4]: Put full name

File: cime_config/testdefs/testmods_dirs/clm/StreamGdd20Seasons/user_nl_clm [hunk 10]
```diff
@@ -0,0 +1,2 @@
+stream_gdd20_seasons = .true.
+allow_invalid_gdd20_season_inputs = .true.
```
Comment (samsrabin) [inline cime_config/testdefs/testmods_dirs/clm/StreamGdd20Seasons/user_nl_clm:2]: Is this testmod used anywhere?

File: cime_config/testdefs/testmods_dirs/clm/cropAnnOutputMonthly/user_nl_clm [hunk 11]
```diff
@@ -0,0 +1,3 @@
+! These variables SHOULD only be saved annually in real runs, but for testing purposes it's fine to have them monthly.
+! Modifies h2 history file defined in crop testmod.
+hist_nhtfrq(3) = 0
```
Comment (samsrabin) [inline cime_config/testdefs/testmods_dirs/clm/cropAnnOutputMonthly/user_nl_clm:3]: Check to see if this testmod is really needed, now that h2 in cropMonthOutput is saved monthly.

File: cime_config/testdefs/testmods_dirs/clm/midDecStart/include_user_mods [hunk 12]
```diff
@@ -0,0 +1 @@
+../default
```
Comment (samsrabin) [inline cime_config/testdefs/testmods_dirs/clm/midDecStart/include_user_mods:1]: Add README saying that midDecStart is used instead of decStart if you want the run split to happen in December rather than January (i.e., before rather than after new year).

File: cime_config/testdefs/testmods_dirs/clm/sowingWindows/user_nl_clm [hunk 13]
```diff
@@ -1,5 +1,5 @@
-stream_fldFileName_swindow_start = '$DIN_LOC_ROOT/lnd/clm2/cropdata/calendars/processed/swindow_starts_ggcmi_crop_calendar_phase3_v1.01.2000-2000.20231005_145103.nc'
-stream_fldFileName_swindow_end = '$DIN_LOC_ROOT/lnd/clm2/cropdata/calendars/processed/swindow_ends_ggcmi_crop_calendar_phase3_v1.01.2000-2000.20231005_145103.nc'
-stream_meshfile_cropcal = '$DIN_LOC_ROOT/share/meshes/360x720_120830_ESMFmesh_c20210507_cdf5.nc'
+stream_fldFileName_swindow_start = '$DIN_LOC_ROOT/lnd/clm2/cropdata/calendars/processed/swindow_starts_ggcmi_crop_calendar_phase3_v1.01.2000-2000.20231005_145103.tweaked_latlons.nc'
+stream_fldFileName_swindow_end = '$DIN_LOC_ROOT/lnd/clm2/cropdata/calendars/processed/swindow_ends_ggcmi_crop_calendar_phase3_v1.01.2000-2000.20231005_145103.tweaked_latlons.nc'
+stream_meshfile_cropcal = '$DIN_LOC_ROOT/lnd/clm2/cropdata/calendars/processed/swindow_starts_ggcmi_crop_calendar_phase3_v1.01.2000-2000.20231005_145103.tweaked_latlons.nc'
```
Comment (samsrabin) [inline cime_config/testdefs/testmods_dirs/clm/sowingWindows/user_nl_clm:3]: Is this testmod actually used anywhere?

File: python/ctsm/crop_calendars/check_rxboth_run.py [hunk 14]
```diff
@@ -128,22 +136,27 @@ def main(argv):
...
                 case["rx_gdds_ds"].isel(time=0),
                 case["ds"],
                 casename,
                 "GDDHARV",
                 gdd_min=gdd_min,
             )
+            any_bad = any_bad or gdds_not_obeyed
+
+    if any_bad:
+        raise RuntimeError("Unexpected behavior in rxboth run")
```
Comment (samsrabin) [inline python/ctsm/crop_calendars/check_rxboth_run.py:159]: Error message should say what exactly failed (if printed messages haven't already said so).

File: python/ctsm/crop_calendars/cropcal_module.py [hunk 15]
```diff
@@ -333,14 +345,17 @@ def import_output(
     my_vars,
     year_1=None,
     year_n=None,
-    my_vegtypes=utils.define_mgdcrop_list(),
+    my_vegtypes=utils.define_mgdcrop_list_nograsses(),
```
Comment (samsrabin) [inline python/ctsm/crop_calendars/cropcal_module.py:348]: Probably should include grasses, just for future proofing.

File: python/ctsm/crop_calendars/cropcal_module.py [hunk 16]
```diff
@@ -410,7 +425,9 @@ def import_output(
     # Check that e.g., GDDACCUM <= HUI
     for var_list in [["GDDACCUM", "HUI"], ["SYEARS", "HYEARS"]]:
         if all(v in this_ds_gs for v in var_list):
-            check_v0_le_v1(this_ds_gs, var_list, both_nan_ok=True, throw_error=True)
+            any_bad = check_v0_le_v1(
+                this_ds_gs, var_list, both_nan_ok=True, throw_error=throw_errors
+            )
```
Comment (samsrabin) [inline python/ctsm/crop_calendars/cropcal_module.py:430]: Don't write this directly to `any_bad`.

File: python/ctsm/crop_calendars/generate_gdd20_baseline.py [hunk 17]
```diff
@@ -182,51 +259,59 @@ def generate_gdd20_baseline(input_files, output_file, author):
...
             print("   dummy GDD20")
         else:
-            this_da = ds_in[gddn].fillna(MISSING_FILL)
+            # this_da = ds_in[gddn].fillna(MISSING_FILL)
+            this_da = ds_in[gddn_str]
             this_da = _add_time_axis(this_da)
-            long_name = gddn
-            print(f"   {gddn}")
+            print(f"   {gddn_str}")
+            this_da = this_da.fillna(MISSING_RX_GDD_VAL)
```
Comment (samsrabin) [inline python/ctsm/crop_calendars/generate_gdd20_baseline.py:291]: What's going on here?

File: python/ctsm/crop_calendars/generate_gdds_functions.py [hunk 18]
```diff
@@ -260,9 +282,9 @@ def import_and_process_1yr(
 
     # Get list of crops to include
     if skip_crops is not None:
-        crops_to_read = [c for c in utils.define_mgdcrop_list() if c not in skip_crops]
+        crops_to_read = [c for c in utils.define_mgdcrop_list_nograsses() if c not in skip_crops]
```
Comment (samsrabin) [inline python/ctsm/crop_calendars/generate_gdds_functions.py:285]: Should probably not skip grasses, for future-proofing.

File: python/ctsm/crop_calendars/generate_gdds_functions.py [hunk 19]
```diff
@@ -260,9 +282,9 @@ def import_and_process_1yr(
...
     else:
-        crops_to_read = utils.define_mgdcrop_list()
+        crops_to_read = utils.define_mgdcrop_list_nograsses()
```
Comment (samsrabin) [inline python/ctsm/crop_calendars/generate_gdds_functions.py:287]: Should probably not skip grasses, for future-proofing.

File: python/ctsm/crop_calendars/import_ds.py [hunk 20]
```diff
@@ -41,6 +41,29 @@ def compute_derived_vars(ds_in, var):
...
+        if ds_out is None:
+            ds_out = ds_in
+        else:
+            ds_out = xr.concat(
+                [ds_out, ds_in],
+                data_vars="minimal",
+                compat="override",
+                coords="all",
+                dim="time",
+                # combine="nested",
```
Comment (samsrabin) [inline python/ctsm/crop_calendars/import_ds.py:62]: Delete this

File: python/ctsm/crop_calendars/interpolate_gdds.py [hunk 21]
```diff
@@ -0,0 +1,166 @@
...
+
+    # Interpolate
+    ds_out = xr.Dataset()
+    for var in ds_in:
+
+        # Check variable
+        if "lat" not in ds_in[var].dims and "lon" not in ds_in[var].dims:
+            print(f"Skipping variable {var} with dimensions {ds_in[var].dims}")
+            continue
+        elif args.variable_prefix not in var:
```
Comment (samsrabin) [inline python/ctsm/crop_calendars/interpolate_gdds.py:124]: Use regex to check that the prefix occurs at the START of the variable name.

File: python/ctsm/run_sys_tests.py [hunk 22]
```diff
@@ -736,13 +736,29 @@ def _check_py_env(test_attributes):
     # whether import is possible.
     # pylint: disable=import-error disable
 
-    # Check requirements for FSURDATMODIFYCTSM, if needed
-    if any("FSURDATMODIFYCTSM" in t for t in test_attributes):
+    # Check requirements for using modify_fsurdat, if needed
```
Comment (samsrabin) [inline python/ctsm/run_sys_tests.py:739]: Update this comment

Comment (samsrabin) [inline python/ctsm/run_sys_tests.py:739]: "modify_fsurdat **module**" for clarity

**Review by slevis-lmwg — CHANGES_REQUESTED** [review]
@samsrabin and I went over all but the fortran parts of this PR.
@samsrabin took notes.
We will finish going over the remainder tomorrow.

File: src/cpl/share_esmf/cropcalStreamMod.F90 (hunk 2 above)
Comment (samsrabin) [reply src/cpl/share_esmf/cropcalStreamMod.F90:58]: No, don't. Would have to change more than just this here.

File: src/cpl/share_esmf/cropcalStreamMod.F90 (hunk 5 above)
Comment (samsrabin) [reply src/cpl/share_esmf/cropcalStreamMod.F90:795]: No, that's handled above.

File: src/biogeochem/CNPhenologyMod.F90 [hunk 23]
```diff
@@ -2716,22 +2716,27 @@ subroutine PlantCrop(p, leafcn_in, jday, kyr, do_plant_normal, &
                ivt(p) == nmiscanthus .or. ivt(p) == nirrig_miscanthus .or. &
                ivt(p) == nswitchgrass .or. ivt(p) == nirrig_switchgrass) then
             gddmaturity(p) = max(950._r8, min(gdd20*0.85_r8, hybgdd(ivt(p))))
-            if (do_plant_normal) then
+            if (do_plant_normal) then  ! TODO SSR: Add ".and. .not. do_plant_prescribed"?
```
Comment (samsrabin) [inline src/biogeochem/CNPhenologyMod.F90:2719]: Review that TODO.

File: src/biogeochem/CNPhenologyMod.F90 [hunk 24]
```diff
@@ -2716,22 +2716,27 @@ subroutine PlantCrop(p, leafcn_in, jday, kyr, do_plant_normal, &
...
                gddmaturity(p) = max(950._r8, min(gddmaturity(p)+150._r8, 1850._r8))
             end if
          else
-            write(iulog, *) 'ERROR: PlantCrop(): unrecognized ivt for GDD target: ',ivt(p)
+            ! TODO SSR: Add more descriptive error message
             call endrun(msg="Stopping")
```
Comment (samsrabin) [inline src/biogeochem/CNPhenologyMod.F90:2724]: Yes, do this.

File: src/biogeochem/CNPhenologyMod.F90 [hunk 25]
```diff
@@ -2716,22 +2716,27 @@ subroutine PlantCrop(p, leafcn_in, jday, kyr, do_plant_normal, &
...
-      if (use_cropcal_streams .and. gddmaturity(p) < min_gddmaturity) then
-          if (did_rx_gdds) then
-              write(iulog,*) 'Some patch with ivt ',ivt(p),' has rx gddmaturity',gddmaturity(p),'; using min_gddmaturity instead (',min_gddmaturity,')'
-          endif
-          gddmaturity(p) = min_gddmaturity
-      endif
+      if (gddmaturity(p) < min_gddmaturity) then
+         if (use_cropcal_rx_cultivar_gdds .or. generate_crop_gdds) then
+             if (did_rx_gdds) then
+                 write(iulog,*) 'Some patch with ivt ',ivt(p),' has rx gddmaturity',gddmaturity(p),'; using min_gddmaturity instead (',min_gddmaturity,')'
```
Comment (samsrabin) [inline src/biogeochem/CNPhenologyMod.F90:2732]: Add space in message

File: src/biogeochem/CropType.F90 [hunk 26]
```diff
@@ -53,6 +53,8 @@ module CropType
      integer , pointer :: rx_swindow_ends_thisyr_patch  (:,:) ! all prescribed sowing window end   dates for this patch this year (day of year) [patch, mxsowings]
      real(r8), pointer :: rx_cultivar_gdds_thisyr_patch (:,:) ! all cultivar GDD targets for this patch this year (ddays) [patch, mxsowings]
      real(r8), pointer :: gdd20_baseline_patch          (:)   ! GDD20 baseline for this patch (ddays) [patch]
+     real(r8), pointer :: gdd20_season_start_patch(:) ! gdd20 season start date for this patch (day of year) [patch]. Real to enable history field.
+     real(r8), pointer :: gdd20_season_end_patch  (:) ! gdd20 season end   date for this patch (day of year) [patch]/ Real to enable history field.
```
Comment (samsrabin) [inline src/biogeochem/CropType.F90:57]: Replace slash with period.

File: src/biogeophys/TemperatureType.F90 [hunk 27]
```diff
@@ -94,6 +95,7 @@ module TemperatureType
      real(r8), pointer :: gdd020_patch            (:)   ! patch 20-year average of gdd0                     (ddays)
      real(r8), pointer :: gdd820_patch            (:)   ! patch 20-year average of gdd8                     (ddays)
      real(r8), pointer :: gdd1020_patch           (:)   ! patch 20-year average of gdd10                    (ddays)
+     logical           :: flush_gdd20 = .false.         ! whether accumulated GDD20s need to be flushed
```
Comment (samsrabin) [inline src/biogeophys/TemperatureType.F90:98]: Redundant with what happens in `clm_varctl`? Try deleting.

File: src/biogeophys/TemperatureType.F90 [hunk 28]
```diff
@@ -893,8 +909,9 @@ subroutine Restart(this, bounds, ncid, flag, is_simple_buildtemp, is_prog_buildt
     logical          , intent(in)    :: is_prog_buildtemp    ! Prognostic building temp is being used
     !
     ! !LOCAL VARIABLES:
-    integer :: j,c       ! indices
+    integer :: j,c,p     ! indices
```
Comment (samsrabin) [inline src/biogeophys/TemperatureType.F90:912]: Is `p` actually needed?

File: src/biogeophys/TemperatureType.F90 [hunk 29]
```diff
@@ -1357,22 +1394,130 @@ subroutine InitAccVars(this, bounds)
...
+    call extract_accum_field (trim(field_name), gddx_patch, nstep)
+
+    end associate
+  end subroutine UpdateAccVars_CropGDDs
+
+  !-----------------------------------------------------------------------
+  subroutine UpdateAccVars (this, bounds, crop_inst)
+    !
+    ! USES
+    use shr_const_mod    , only : SHR_CONST_TKFRZ
```
Comment (samsrabin) [inline src/biogeophys/TemperatureType.F90:1507]: I don't think `SHR_CONST_TKFRZ` is needed in `UpdateAccVars()`.

File: src/biogeophys/TemperatureType.F90 [hunk 30]
```diff
@@ -1535,78 +1681,26 @@ subroutine UpdateAccVars (this, bounds)
...
-          end if
-       end do
-       call update_accum_field  ('GDD10', rbufslp, nstep)
-       call extract_accum_field ('GDD10', this%gdd10_patch, nstep)
+       call this%UpdateAccVars_CropGDDs(rbufslp, begp, endp, month, day, secs, dtime, nstep, 10, this%gdd10_patch, crop_inst)
 
        ! Accumulate and extract running 20-year means
        if (is_end_curr_year()) then
+          ! Flush, if needed
+          if (flush_gdd20 .or. this%flush_gdd20) then
```
Comment (samsrabin) [inline src/biogeophys/TemperatureType.F90:1696]: Why two `flush_gdd20`s?

File: src/biogeophys/TemperatureType.F90 (hunk 29 above)
Comment (samsrabin) [reply src/biogeophys/TemperatureType.F90:1507]: Yes, it is.

File: src/biogeophys/TemperatureType.F90 (hunk 1 above)
Comment (samsrabin) [reply src/biogeophys/TemperatureType.F90:900]: Reverted in 71ca96d2d.

File: bld/CLMBuildNamelist.pm (hunk 3 above)
Comment (samsrabin) [reply bld/CLMBuildNamelist.pm:4203]: Done with ad2c7f3af.

File: src/cpl/share_esmf/cropcalStreamMod.F90 (hunk 6 above)
Comment (samsrabin) [reply src/cpl/share_esmf/cropcalStreamMod.F90:798]: Done with 592476f7c.

File: cime_config/testdefs/testmods_dirs/clm/RxCropCalsAdaptGGCMI/user_nl_clm (hunk 9 above)
Comment (samsrabin) [reply cime_config/testdefs/testmods_dirs/clm/RxCropCalsAdaptGGCMI/user_nl_clm:4]: Done with 013028c46.

File: python/ctsm/crop_calendars/import_ds.py (hunk 20 above)
Comment (samsrabin) [reply python/ctsm/crop_calendars/import_ds.py:62]: Done with 96c7c2d96.

File: python/ctsm/run_sys_tests.py (hunk 22 above)
Comment (samsrabin) [reply python/ctsm/run_sys_tests.py:739]: Done with 1d9e93989.

File: src/biogeochem/CNPhenologyMod.F90 (hunk 24 above)
Comment (samsrabin) [reply src/biogeochem/CNPhenologyMod.F90:2724]: Done with 78d9f9806.

File: src/biogeochem/CNPhenologyMod.F90 (hunk 25 above)
Comment (samsrabin) [reply src/biogeochem/CNPhenologyMod.F90:2732]: Done with 78d9f9806.

File: src/biogeochem/CropType.F90 (hunk 26 above)
Comment (samsrabin) [reply src/biogeochem/CropType.F90:57]: Done with d3e6cbf13.

File: src/biogeophys/TemperatureType.F90 (hunk 28 above)
Comment (samsrabin) [reply src/biogeophys/TemperatureType.F90:912]: No. Reverted with 6546a681b.

File: bld/namelist_files/namelist_defaults_ctsm.xml (hunk 4 above)
Comment (samsrabin) [reply bld/namelist_files/namelist_defaults_ctsm.xml:1715]: You need different baseline values depending on what "warm period" you're using. The `stream_gdd20_seasons=".false."` version was generated from a run using the CLM default warm period (hemisphere-specific). The `stream_gdd20_seasons=".true."` version was copied from a prescribed maturity requirement file that used the GGCMI growing seasons, which are the default "warm periods" with `stream_gdd20_seasons=".true."`.

File: cime_config/testdefs/testmods_dirs/clm/StreamGdd20Seasons/user_nl_clm (hunk 10 above)
Comment (samsrabin) [reply cime_config/testdefs/testmods_dirs/clm/StreamGdd20Seasons/user_nl_clm:2]: Yes, in one of the tests in the crop_calendars suite.

File: cime_config/testdefs/testmods_dirs/clm/sowingWindows/user_nl_clm (hunk 13 above)
Comment (samsrabin) [reply cime_config/testdefs/testmods_dirs/clm/sowingWindows/user_nl_clm:3]: No. Deleted in c96ce350e.

File: python/ctsm/crop_calendars/check_rxboth_run.py (hunk 14 above)
Comment (samsrabin) [reply python/ctsm/crop_calendars/check_rxboth_run.py:159]: Done with b96ec9107.

File: python/ctsm/crop_calendars/interpolate_gdds.py (hunk 21 above)
Comment (samsrabin) [reply python/ctsm/crop_calendars/interpolate_gdds.py:124]: Done with 876e23bb4.

File: cime_config/testdefs/testmods_dirs/clm/cropAnnOutputMonthly/user_nl_clm (hunk 11 above)
Comment (samsrabin) [reply cime_config/testdefs/testmods_dirs/clm/cropAnnOutputMonthly/user_nl_clm:3]: Nope, redundant with `cropMonthOutput`. Deleted in fecad2997.

File: python/ctsm/crop_calendars/cropcal_module.py (hunk 16 above)
Comment (samsrabin) [reply python/ctsm/crop_calendars/cropcal_module.py:430]: Done with 833d4f67e.

File: cime_config/testdefs/testlist_clm.xml (hunk 7 above)
Comment (samsrabin) [reply cime_config/testdefs/testlist_clm.xml:3675]: 56523e4cb removes the 1-degree version from those suites.

File: cime_config/testdefs/testmods_dirs/clm/RxCropCalsAdaptFlush/user_nl_clm (hunk 8 above)
Comment (samsrabin) [reply cime_config/testdefs/testmods_dirs/clm/RxCropCalsAdaptFlush/user_nl_clm:2]: Actually, this testmod isn't needed. Removed with d06e8642a.

File: python/ctsm/crop_calendars/generate_gdd20_baseline.py (hunk 17 above)
Comment (samsrabin) [reply python/ctsm/crop_calendars/generate_gdd20_baseline.py:291]: Clarifying comment added with a2bf12483.

File: src/biogeochem/CNPhenologyMod.F90 (hunk 23 above)
Comment (samsrabin) [reply src/biogeochem/CNPhenologyMod.F90:2719]: Resolved (dismissed) with c9ff0ee33.

File: src/biogeophys/TemperatureType.F90 (hunk 30 above)
Comment (samsrabin) [reply src/biogeophys/TemperatureType.F90:1696]: Cleaned up with bc055919b and d298aef94. Briefly: `this%flush_gdd20` refers to the member of `TemperatureType`, whereas `flush_gdd20` refers to the parameter from `clm_varctl`. I've now cleaned it up so that the latter is only considered during `TemperatureType` `Init()` and `Restart()`.

File: src/biogeophys/TemperatureType.F90 (hunk 27 above)
Comment (samsrabin) [reply src/biogeophys/TemperatureType.F90]: Deleted in 827632e12.

**Comment by samsrabin** [comment]
@slevis-lmwg In 827632e12, I resolved the "two `flush_gdd20`s" question by removing the one that was a member of `TemperatureType`. Having that alongside `flush_gdd20` from `clm_varctl` meant that they could disagree when restarting, and it's not obvious which should win.

Note that the user being able to request a flush at all is dangerous. If they start a run with it true, they might continue that run without setting it to false. Instead, the restart decision should be made by the model—if a gridcell has different prescribed GDD20 season from what its restart file says, then that gridcell should be flushed.

I will plan to make that change in a future update, post-code-freeze. It only affects things when streaming GDD20 seasons, which will not be a default behavior, so I think it's okay to leave things as they are now.

File: python/ctsm/crop_calendars/generate_gdds_functions.py (hunk 19 above)
Comment (samsrabin) [reply python/ctsm/crop_calendars/generate_gdds_functions.py:287]: Done with 4ab30a5dd.

File: python/ctsm/crop_calendars/cropcal_module.py (hunk 15 above)
Comment (samsrabin) [reply python/ctsm/crop_calendars/cropcal_module.py:348]: Done with 4ab30a5dd.

**Comment by samsrabin** [comment]
For some reason I'm getting an unexpected change in `ERP_D_P128x1_Ld26.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-midDecStart--clm-RxCropCalsAdaptGGCMI` and its PEM version.

```
ERP_D_P128x1_Ld26.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-midDecStart--clm-RxCropCalsAdaptGGCMI
2024-07-24 18:33:49: NLCOMP
Comparison failed between '/glade/derecho/scratch/samrabin/tests_0724-183247de/ERP_D_P128x1_Ld26.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-midDecStart--clm-RxCropCalsAdaptGGCMI.GC.0724-183247de_int/CaseDocs/lnd_in' with '/glade/campaign/cgd/tss/ctsm_baselines/scale-mat-reqs-pr2-ggcmiseas.22742634/ERP_D_P128x1_Ld26.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-midDecStart--clm-RxCropCalsAdaptGGCMI/CaseDocs/lnd_in'
  BASE: stream_fldfilename_gdd20_baseline = gdd20bl.copied_from.gdds_20230829_161011.v2.tweaked_latlons.nc'
  COMP: stream_fldfilename_gdd20_baseline = 20230714_cropcals_pr2_1deg.actually2deg.1980-2009.from_GDDB20.interpd_halfdeg.tweaked_latlons.nc'
```

`stream_fldfilename_gdd20_baseline` should not have changed. In the baseline (2274263), the relevant bit of `namelist_defaults_ctsm.xml` looked like this:
```xml
<stream_fldFileName_gdd20_baseline cropcals_rx_adapt=".true.">lnd/clm2/cropdata/calendars/processed/gdd20bl.copied_from.gdds_20230829_161011.v2.tweaked_latlons.nc</stream_fldFileName_gdd20_baseline>
```
And in the latest test (aeb4182) it looked like this:
```xml
<stream_fldFileName_gdd20_baseline cropcals_rx_adapt=".true." stream_gdd20_seasons=".false.">lnd/clm2/cropdata/calendars/processed/20230714_cropcals_pr2_1deg.actually2deg.1980-2009.from_GDDB20.interpd_halfdeg.tweaked_latlons.nc</stream_fldFileName_gdd20_baseline>
<stream_fldFileName_gdd20_baseline cropcals_rx_adapt=".true." stream_gdd20_seasons=".true.">lnd/clm2/cropdata/calendars/processed/gdd20bl.copied_from.gdds_20230829_161011.v2.tweaked_latlons.nc</stream_fldFileName_gdd20_baseline>
```
These two tests have `cropcals_rx_adapt` and `stream_gdd20_seasons` both true.

**Comment by mvdebolskiy** [comment]
I think the issue is here:
```
add_default($opts, $nl_flags->{'inputdata_rootdir'}, $definition, $defaults, $nl, 'stream_fldFileName_gdd20_baseline');
```
does not get the seasons var at all.
Try:
```
add_default($opts, $nl_flags->{'inputdata_rootdir'}, $definition, $defaults, $nl, 'stream_fldFileName_gdd20_baseline', "stream_gdd20_seasons"=>$stream_gdd20_seasons->as_string() );
```

**Comment by samsrabin** [comment]
That's it! The exact diff needed, for posterity:
```
diff --git a/bld/CLMBuildNamelist.pm b/bld/CLMBuildNamelist.pm
index 5202717d7..04d2ee37b 100755
--- a/bld/CLMBuildNamelist.pm
+++ b/bld/CLMBuildNamelist.pm
@@ -4211,7 +4211,7 @@ sub setup_logic_cropcal_streams {
     add_default($opts, $nl_flags->{'inputdata_rootdir'}, $definition, $defaults, $nl, 'stream_fldFileName_swindow_end');
     add_default($opts, $nl_flags->{'inputdata_rootdir'}, $definition, $defaults, $nl, 'stream_fldfilename_cultivar_gdds');
     if ( &value_is_true($cropcals_rx_adapt) ) {
-      add_default($opts, $nl_flags->{'inputdata_rootdir'}, $definition, $defaults, $nl, 'stream_fldFileName_gdd20_baseline');
+      add_default($opts, $nl_flags->{'inputdata_rootdir'}, $definition, $defaults, $nl, 'stream_fldFileName_gdd20_baseline', 'stream_gdd20_seasons'=>$stream_gdd20_seasons);
     }
   }
```
Thanks, @mvdebolskiy!!

**Comment by samsrabin** [comment]
@slevis-lmwg This is ready for re-review.

**Comment by slevis-lmwg** [comment]
@samsrabin I just wanted to confirm that you will track the items left pending from this PR, such as these:
https://github.com/ESCOMP/CTSM/pull/2593#issuecomment-2249100289
https://github.com/ESCOMP/CTSM/pull/2593#issuecomment-2251010346

**Comment by samsrabin** [comment]
Good thinking. I've made the first one into issue #2660. I'm fixing the second as we speak, so I won't make a separate issue for that.

**Review by slevis-lmwg — APPROVED** [review]
