### PR TITLE
Remove endrun for Meier2022 case to work

### LINKED ISSUE #2264: Meier2022 option fails in BiogeophysPreFluxCalcsMod.F90 line 208 in IHist case
### Brief summary of bug

Meier2022 option fails on Dec 31, 2001, of this IHist case:
https://github.com/NCAR/LMWG_dev/issues/38 
Simulation started in 1989.

### General bug information

**CTSM version you are using:**
ctsm5.1.dev154

**Does this bug cause significantly incorrect results in the model's science?**
Run fails.

**Configurations affected:**
`./create_newcase --case ctsm51d154_2deg_GSWP3V1_hist --compset HIST_DATM%GSWP3v1_CLM51%BGC-CROP_SICE_SOCN_MOSART_SGLC_SWAV --res f19_g17 --run-unsupported`

### Details of bug

During pre-tag testing for dev154, I encountered the same failure in the aux_clm test-suite. I resolved it by adding the if istcrop statement:
```
               if ( htop(p) <= 1.e-10_r8 )then
                  if (lun%itype(l) == istcrop) then
                     z0m(p) = 0._r8
                     displa(p) = 0._r8
                  else
                     write(iulog,*) ' nstep = ', get_nstep(), ' htop = ', htop(p)
                     call endrun(subgrid_index=p, subgrid_level=subgrid_level_patch, msg=errMsg(sourcefile, __LINE__))
                  end if
               else
                   z0m(p) = htop(p) * (1._r8 - displa(p) / htop(p)) * exp(-0.4_r8 * U_ustar + &
                               log(pftcon%z0v_cw(patch%itype(p))) - 1._r8 + pftcon%z0v_cw(patch%itype(p))**(-1._r8))
               end if
```
That this now fails in an IHist simulation tells me that the model likely encounters tiny htop for a newly introduced non-crop patch. I propose that we remove the new if istcrop, as well as the endrun and just set z0m and displa to 0 for tiny htop.

### Important details of your setup / configuration so we can reproduce the bug

Case was submitted here:
`/glade/work/slevis/git_ctsm_tags/ctsm5.1.dev154/cime/scripts/ctsm51d154_2deg_GSWP3V1_hist`

### Important output or errors that show the problem

Case ran here:
`/glade/scratch/slevis/ctsm51d154_2deg_GSWP3V1_hist/run`

### PR DESCRIPTION
**Pull request by slevis-lmwg**
### Description of changes

For tiny htop, remove endrun and add z0m = 0 and displa = 0.

### Specific notes

Contributors other than yourself, if any:

CTSM Issues Fixed (include github issue #):
Fixes #2264 

Are answers expected to change (and if so in what way)?
No, in the test-suites.
In longer simulation, prevents failure.

Any User Interface Changes (namelist or namelist defaults changes)?
No.

Testing performed, if any:
The fix works. Tried alternate suggestion that failed, as documented in #2264.

### CODE REVIEW

File: src/biogeophys/BiogeophysPreFluxCalcsMod.F90 [hunk 1]
```diff
@@ -200,16 +200,11 @@ subroutine SetZ0mDisp(bounds, num_nolakep, filter_nolakep, &
...
                if ( htop(p) <= 1.e-10_r8 )then
-                  if (lun%itype(l) == istcrop) then
-                     z0m(p) = 0._r8
-                     displa(p) = 0._r8
-                  else
-                     write(iulog,*) ' nstep = ', get_nstep(), ' htop = ', htop(p)
-                     call endrun(subgrid_index=p, subgrid_level=subgrid_level_patch, msg=errMsg(sourcefile, __LINE__))
-                  end if
+                  z0m(p) = 0._r8
+                  displa(p) = 0._r8
```
Comment (slevis-lmwg) [inline src/biogeophys/BiogeophysPreFluxCalcsMod.F90:204]: In case it helps to look at the origins of this code, see 
BiogeophysPreFluxCalcsMod.F90
in
https://github.com/ESCOMP/CTSM/pull/2045/files

The if statement came in with the Meier2022 code to prevent divide by zero (or tiny) htop. The if statement did not account for the possibility of valid zero (or tiny) htop.

**Comment by slevis-lmwg** [comment]
@olyson suggested z0m = soil roughness instead of 0.
@ekluzek suggested running with debug on to confirm we don't have NaNs at the year transition that was failing.

**Comment by slevis-lmwg** [comment]
@olyson I'm requesting a review from you. Only one file changed, where I implemented the change from dev154 to your suggestion [posted above](https://github.com/ESCOMP/CTSM/pull/2271#issuecomment-1834117795).

**Comment by slevis-lmwg** [comment]
**Test-suites**
Izumi PASS
Cheyenne likely OK
...to be certain, I'm rerunning SMS_D_Lm6_P144x1.f45_f45_mg37.I2000Clm50FatesRs.cheyenne_intel.clm-FatesCold

**Review by olyson — APPROVED** [review]
Looks good to me thanks.
