### PR TITLE
ctsm5.3.039: Create driver data structure for SP mode

### LINKED ISSUE #2945: htop_patch is being incorrectly used in FATES compsets
### Brief summary of bug

`htop_patch` is being incorrectly used in FATES compsets, especially (only?) when FATES SP-mode is on. This is because the `htop_patch` data structure is indexed by **CLM PFTS** whereas in FATES runs we should be using a data structure that is indexed by **FATES PFTS**.

see [here](https://github.com/ESCOMP/CTSM/blob/ec0986b37ea8b7f34384a9f8134830cbf7fb7722/src/biogeophys/CanopyFluxesMod.F90#L1074) for an example.

### General bug information

**CTSM version you are using:** ctsm5.3.020

**Does this bug cause significantly incorrect results in the model's science?** Yes
**Configurations affected:** FATES, especially FATES-SP

### PR DESCRIPTION
**Pull request by adrifoster**
### Description of changes

Creates a new data structure for `htop`, `tlai`, and `tsai` that is just driver data.

### Specific notes

Previously, fates used `htop_patch` (etc.) as a **driver** data, but we also needed to update it and set set `htop_hist_patch`. This `htop_hist_patch` was inconsistently used throughout the CLM code, resulting in mis-matches between the PFT structures that we actually were trying to run (see #2945).

Now we have the SP driver data as a separate data structure, and methods to set it. FATES sets it and passes it back to CLM through the `bc_out` struct, CLM just sets it in a 1:1 call.

Contributors other than yourself, if any:

@ekluzek @rgknox @rosiealice 

CTSM Issues Fixed (include github issue #): Closes #2945 

Are answers expected to change (and if so in what way)? Yes - because we were incorrectly using it before, all FATES-SP compsets should change. 

**ALL OTHER COMPSETS SHOULD BE B4B**

Any User Interface Changes (namelist or namelist defaults changes)? No

Does this create a need to change or add documentation? Did you do so? N/A

Testing performed, if any:

Will test

### CODE REVIEW

File: src/biogeochem/SatellitePhenologyMod.F90 [hunk 1]
```diff
@@ -24,7 +24,8 @@ module SatellitePhenologyMod
   private
   !
   ! !PUBLIC MEMBER FUNCTIONS:
-  public :: SatellitePhenology     ! CLMSP Ecosystem dynamics: phenology, vegetation
+  public :: GetSatellitePhenologyInputs ! put the data into the correct format
+  public :: SetSPModeCanopyStructs      ! CLMSP Ecosystem dynamics: phenology, vegetation
```
Comment (wwieder) [inline src/biogeochem/SatellitePhenologyMod.F90:28]: FWIW I find it confusing to refer to CLM Ecosystem Dynamics when this is NOT related to FATES can the comment just be for CLM-SP phenology and vegetation

**Comment by adrifoster** [comment]
Testing `aux_clm` on derecho:

Removed expected fails...

0206-092821de_gnu: 65 tests
    FAIL SMS_D.1x1_brazil.I2000Clm60FatesSpCruRsGs.derecho_gnu.clm-FatesColdDryDepSatPhen BASELINE ctsm5.3.021: DIFF
    FAIL SMS_D.1x1_brazil.I2000Clm60FatesSpCruRsGs.derecho_gnu.clm-FatesColdMeganSatPhen BASELINE ctsm5.3.021: DIFF

 
0206-092821de_int: 167 tests
    FAIL ERP_P128x2_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen COMPARE_base_rest
    FAIL ERP_P128x2_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen BASELINE ctsm5.3.021: DIFF

0206-092821de_nvh
    FAIL SMS_D.f10_f10_mg37.I2000Clm60BgcCrop.derecho_nvhpc.clm-crop RUN time=35
    FAIL SMS.f45_f45_mg37.I2000Clm60FatesSpRsGs.derecho_nvhpc.clm-FatesColdSatPhen BASELINE ctsm5.3.021: DIFF



Does anyone (@samsrabin?) know why `SMS_D.f10_f10_mg37.I2000Clm60BgcCrop.derecho_nvhpc.clm-crop RUN time=35` ? The log files don't really show anything at all. Only the med.log and cesm.log have anything in them at all.

**Comment by ekluzek** [comment]
> Does anyone (@samsrabin?) know why `SMS_D.f10_f10_mg37.I2000Clm60BgcCrop.derecho_nvhpc.clm-crop RUN time=35` ? The log files don't really show anything at all. Only the med.log and cesm.log have anything in them at all.

Check the baseline and see if it died as well and didn't get put into expected fails.

We've been having problems with the nvhpc compiler, so personally I'm not too inclined to make sure it works if everything else is OK. But, always good to spend some time looking at it...

**Review by ekluzek — COMMENTED** [review]
This is great, this improves the current code structure and removes some problematic logic in the code. I have a few questions on names, that we can discuss.

As a separate thing I'd like us to be thinking about what kind of design we'd like to have for FATES-SP that we can work towards. If we do some thinking there we can make sure steps like this are moving us toward what we think the end design goal might be. I think that should probably be an issue itself, where we put some design thinking in. So we should open that and reference here. This would just be thought of as a step toward that, and not doing everything desired there.

Happy to discuss and do more thinking about naming and a design goal to work towards.

But, thanks for the work here, I like that you are both fixing an immediate problem and improving the code. That's the golden thing to try to do when we can.

**Comment by adrifoster** [comment]
> > Does anyone (@samsrabin?) know why `SMS_D.f10_f10_mg37.I2000Clm60BgcCrop.derecho_nvhpc.clm-crop RUN time=35` ? The log files don't really show anything at all. Only the med.log and cesm.log have anything in them at all.
> 
> Check the baseline and see if it died as well and didn't get put into expected fails.
> 
> We've been having problems with the nvhpc compiler, so personally I'm not too inclined to make sure it works if everything else is OK. But, always good to spend some time looking at it...

There is no baseline for this because it was not supposed to pass SHAREDLIB_BUILD (has an expected fail for that), but somehow it passed that stage but died in RUN

File: src/biogeochem/SatellitePhenologyMod.F90 [hunk 2]
```diff
@@ -153,53 +145,112 @@ subroutine SatellitePhenology(bounds, num_filter, filter, &
...
+         hbot_driver(p) = timwt(1)*mhvb2t(p,1) + timwt(2)*mhvb2t(p,2)
+         
+      end do
+      end associate
+      
+   end subroutine GetSatellitePhenologyInputs
+   
+   !==============================================================================
+   
+   subroutine SetSPModeCanopyStructs(bounds, num_filter, filter, &
```
[the remark this answers is not in the document]
Comment (adrifoster) [reply src/biogeochem/SatellitePhenologyMod.F90:162]: Sounds great to me. I love long method names :)

File: src/biogeochem/SatellitePhenologyMod.F90 [hunk 3]
```diff
@@ -107,25 +107,17 @@ subroutine SatellitePhenology(bounds, num_filter, filter, &
...
-         tlai               => canopystate_inst%tlai_patch    ,          & ! Output: [real(r8) (:) ] one-sided leaf area index, no burying by snow
-         tsai               => canopystate_inst%tsai_patch    ,          & ! Output: [real(r8) (:) ] one-sided stem area index, no burying by snow
-         elai               => canopystate_inst%elai_patch    ,          & ! Output: [real(r8) (:) ] one-sided leaf area index with burying by snow
-         esai               => canopystate_inst%esai_patch    ,          & ! Output: [real(r8) (:) ] one-sided stem area index with burying by snow
-         htop               => canopystate_inst%htop_patch    ,          & ! Output: [real(r8) (:) ] canopy top (m)
-         hbot               => canopystate_inst%hbot_patch    ,          & ! Output: [real(r8) (:) ] canopy bottom (m)
-         frac_veg_nosno_alb => canopystate_inst%frac_veg_nosno_alb_patch & ! Output: [integer  (:) ] fraction of vegetation not covered by snow (0 OR 1) [-]
+         tlai_driver        => canopystate_inst%tlai_input_patch    ,    & ! Output: [real(r8) (:) ] one-sided leaf area index, no burying by snow
```
[the remark this answers is not in the document]
Comment (adrifoster) [reply src/biogeochem/SatellitePhenologyMod.F90:117]: That's fair. Yeah the `input_patch` is the interpolated/weighted data so, no, not raw. I can update.

File: src/biogeophys/CanopyStateType.F90 [hunk 4]
```diff
@@ -29,9 +29,10 @@ module CanopyStateType
      real(r8) , pointer :: elai_patch               (:)   ! patch canopy one-sided leaf area index with burying by snow
      real(r8) , pointer :: esai_patch               (:)   ! patch canopy one-sided stem area index with burying by snow
 
-     real(r8) , pointer :: tlai_hist_patch               (:)   ! patch canopy one-sided leaf area index, for SP mode
-     real(r8) , pointer :: tsai_hist_patch               (:)   ! patch canopy one-sided stem area index, for SP mode
-     real(r8) , pointer :: htop_hist_patch               (:)   ! patch canopy height, for SP mode
+     real(r8) , pointer :: tlai_input_patch          (:)   ! patch canopy one-sided leaf area index driver data for SP mode (no burying by snow)
```
[the remark this answers is not in the document]
Comment (adrifoster) [reply src/biogeophys/CanopyStateType.F90:32]: well yes, input, plus interpolated?

File: src/biogeochem/SatellitePhenologyMod.F90 [hunk 5]
```diff
@@ -153,53 +145,113 @@ subroutine SatellitePhenology(bounds, num_filter, filter, &
...
-         ! accounts for a 20% bending factor, as used in Lombardozzi et al. (2018) GRL 45(18), 9889-9897
-
-         ! NOTE: The following snow burial code is duplicated in CNVegStructUpdateMod.
-         ! Changes in one place should be accompanied by similar changes in the other.
-
-         if (patch%itype(p) > noveg .and. patch%itype(p) <= nbrdlf_dcd_brl_shrub ) then
-            ol = min( max(snow_depth(c)-hbot(p), 0._r8), htop(p)-hbot(p))
-            fb = 1._r8 - ol / max(1.e-06_r8, htop(p)-hbot(p))
-         else
-            fb = 1._r8 - (max(min(snow_depth(c),max(0.05,htop(p)*0.8_r8)),0._r8)/(max(0.05,htop(p)*0.8_r8)))
```
[the remark this answers is not in the document]
Comment (adrifoster) [reply src/biogeochem/SatellitePhenologyMod.F90:177]: these were just local variables that were only used within a `if .not. use_fates_sp` clause

**Comment by adrifoster** [comment]
@ekluzek, @rosiealice, or anyone...

we have encountered some further issues.

It seems that we will need some further refactoring to get this bug fixed.

I spoke with @glemieux and he pointed out that `CanopyFluxes` runs before we ever get to the `fates` call that sets up the satellite phenology structures. Thus, even if we have `fates` pass back the **correct** `htop` array, it will not ever get used.

Is this correct?

**Comment by rosiealice** [comment]
Do you mean, not 'ever' get used, or just not get used until FATES is called at the end of the day? I guess either way this is problematic/will cause restart test failures.  I guess somehow we need to pass through the SP code during initialization to fix this?

File: src/biogeochem/SatellitePhenologyMod.F90 [hunk 6]
```diff
@@ -24,7 +24,8 @@ module SatellitePhenologyMod
   private
   !
   ! !PUBLIC MEMBER FUNCTIONS:
-  public :: SatellitePhenology     ! CLMSP Ecosystem dynamics: phenology, vegetation
+  public :: GetSatellitePhenologyInputs ! put the data into the correct format
+  public :: SetSatellitePhenologyBGCCanopyStructs ! CLM(BGC)-SP phenology and vegetation
```
Comment (ekluzek) [inline src/biogeochem/SatellitePhenologyMod.F90:28]: I'm just wondering about changing the name to

SetSatellitePhenologyBGCCanopyTypes

Comment (adrifoster) [reply src/biogeochem/SatellitePhenologyMod.F90:28]: sure sounds good

File: src/biogeochem/SatellitePhenologyMod.F90 [hunk 7]
```diff
@@ -153,53 +145,113 @@ subroutine SatellitePhenology(bounds, num_filter, filter, &
...
+    type(waterdiagnosticbulk_type) , intent(in)    :: waterdiagnosticbulk_inst
+    type(canopystate_type)         , intent(inout) :: canopystate_inst
+    !
+    ! !LOCAL VARIABLES:
+    integer  :: fp,p,c                            ! indices
+    real(r8) :: ol                                ! thickness of canopy layer covered by snow (m)
+    real(r8) :: fb                                ! fraction of canopy layer covered by snow
+    
+    if (use_fates_sp) then 
+      write(iulog,*) 'SetSatellitePhenologyBGCCanopyStructs', 'should not be calling this method when use_fates_sp == .true.'
```
Comment (ekluzek) [inline src/biogeochem/SatellitePhenologyMod.F90:190]: Remove the subroutine name. The errMsg serves this purpose. See #1452

File: src/biogeophys/CanopyStateType.F90 (hunk 4 above)
[the remark this answers is not in the document]
Comment (ekluzek) [reply src/biogeophys/CanopyStateType.F90:32]: Hmmm, maybe it should be "interp" then?

File: src/biogeochem/SatellitePhenologyMod.F90 (hunk 7 above)
Comment (ekluzek) [reply src/biogeochem/SatellitePhenologyMod.F90:190]: It's actually for any FATES simulation, so maybe should be use_fates? 

And actually maybe this check should just be done at initialization? But, since it's a subroutine call -- there isn't a way to do that. Hmmm.... A single check like this is fine

File: src/biogeochem/SatellitePhenologyMod.F90 [hunk 8]
```diff
@@ -153,53 +145,113 @@ subroutine SatellitePhenology(bounds, num_filter, filter, &
...
-
-         if (patch%itype(p) > noveg .and. patch%itype(p) <= nbrdlf_dcd_brl_shrub ) then
-            ol = min( max(snow_depth(c)-hbot(p), 0._r8), htop(p)-hbot(p))
-            fb = 1._r8 - ol / max(1.e-06_r8, htop(p)-hbot(p))
-         else
-            fb = 1._r8 - (max(min(snow_depth(c),max(0.05,htop(p)*0.8_r8)),0._r8)/(max(0.05,htop(p)*0.8_r8)))
+            tlai_tinterp(p) = timwt(1)*mlai2t(p,1) + timwt(2)*mlai2t(p,2)
          endif
 
-         ! area weight by snow covered fraction
```
Comment (ekluzek) [inline src/biogeochem/SatellitePhenologyMod.F90:180]: Glad to get rid of the need for the use_fates_sp part in here.

File: src/biogeochem/SatellitePhenologyMod.F90 [hunk 9]
```diff
@@ -24,7 +24,8 @@ module SatellitePhenologyMod
   private
   !
   ! !PUBLIC MEMBER FUNCTIONS:
-  public :: SatellitePhenology     ! CLMSP Ecosystem dynamics: phenology, vegetation
+  public :: GetSatellitePhenologyInputs ! put the data into the correct format
```
Comment (ekluzek) [inline src/biogeochem/SatellitePhenologyMod.F90:27]: I kind of think of a method with Get in the title as a getter method. And this is more than that. We tend to use Calc or Update for something more extensive. This is really where the interpolation is applied though.

So maybe something like...

CalcSatellitePhenologyTimeInterp?

**Review by ekluzek — CHANGES_REQUESTED** [review]
@adrifoster thanks for your nice work here and the cleanup of the code calling structure. I just have some thoughts on names of things, which is always a hard thing to get right. I have some suggestions and we can talk about this a bit when we meet in a little bit.

File: src/biogeochem/SatellitePhenologyMod.F90 (hunk 6 above)
Comment (ekluzek) [reply src/biogeochem/SatellitePhenologyMod.F90:28]: Compsets: Sp, Bgc, BgcCrop, Fates, FatesSp

File: src/biogeophys/CanopyStateType.F90 (hunk 4 above)
[the remark this answers is not in the document]
Comment (ekluzek) [reply src/biogeophys/CanopyStateType.F90:32]: tlai_interp_patch vs tlai_input_interp_patch?

**Comment by adrifoster** [comment]
------------------------------------------------------------------------
Testing results for aux_clm on derecho:

0414-091736de_gnu: 80 tests
    FAIL SMS_D.1x1_brazil.I2000Clm60FatesSpCruRsGs.derecho_gnu.clm-FatesColdDryDepSatPhen BASELINE ctsm5.3.038: DIFF

```
grep "RMS" /glade/derecho/scratch/afoster/tests_0414-091736de/SMS_D.1x1_brazil.I2000Clm60FatesSpCruRsGs.derecho_gnu.clm-FatesColdDryDepSatPhen.GC.0414-091736de_gnu/run/SMS_D.1x1_brazil.I2000Clm60FatesSpCruRsGs.derecho_gnu.clm-FatesColdDryDepSatPhen.GC.0414-091736de_gnu.clm2.h0.2000-01-06-00000.nc.cprnc.out
 RMS HTOP                             1.9450E+01            NORMALIZED  9.4802E-01
 RMS TLAI                             2.7786E+00            NORMALIZED  8.3487E-01
 RMS TSAI                             4.9343E-01            NORMALIZED  7.9647E-01
```

    FAIL SMS_D.1x1_brazil.I2000Clm60FatesSpCruRsGs.derecho_gnu.clm-FatesColdMeganSatPhen BASELINE ctsm5.3.038: DIFF

```
grep "RMS" /glade/derecho/scratch/afoster/tests_0414-091736de/SMS_D.1x1_brazil.I2000Clm60FatesSpCruRsGs.derecho_gnu.clm-FatesColdMeganSatPhen.GC.0414-091736de_gnu/run/SMS_D.1x1_brazil.I2000Clm60FatesSpCruRsGs.derecho_gnu.clm-FatesColdMeganSatPhen.GC.0414-091736de_gnu.clm2.h0.2000-01-06-00000.nc.cprnc.out
 RMS HTOP                             1.9450E+01            NORMALIZED  9.4802E-01
 RMS TLAI                             2.7786E+00            NORMALIZED  8.3487E-01
 RMS TSAI                             4.9343E-01            NORMALIZED  7.9647E-01
```

    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Bgc.derecho_gnu.clm-default--clm-NEON-HARV SHAREDLIB_BUILD time=15 (UNEXPECTED: expected FAIL)
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Bgc.derecho_gnu.clm-NEON-MOAB--clm-PRISM SHAREDLIB_BUILD time=10 (UNEXPECTED: expected FAIL)
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Bgc.derecho_gnu.clm-NEON-MOAB--clm-PRISM RUN time=88 (UNEXPECTED: expected FAIL)
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.derecho_gnu.clm-FatesPRISM--clm-NEON-FATES-YELL SHAREDLIB_BUILD time=11 (UNEXPECTED: expected FAIL)
    FAIL SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.derecho_gnu.clm-FatesPRISM--clm-NEON-FATES-YELL RUN time=101 (EXPECTED FAILURE)

 
0414-091736de_int: 192 tests
    FAIL ERP_P128x2_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen BASELINE ctsm5.3.038: DIFF

```
grep "RMS" /glade/derecho/scratch/afoster/tests_0414-091736de/ERP_P128x2_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen.GC.0414-091736de_int/run/ERP_P128x2_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen.GC.0414-091736de_int.clm2.h0.2000-01-31-00000.nc.cprnc.out
 RMS ALPHA_TC_RATE                    2.0184E-02            NORMALIZED  6.4123E+00
 RMS DSTFLXT                          4.9946E-10            NORMALIZED  9.5686E+00
 RMS ETA                              2.2085E-02            NORMALIZED  7.1768E+00
 RMS FRC_THR_RGHN_FCT                 1.6212E-01            NORMALIZED  1.9717E+00
 RMS HTOP                             9.2588E+00            NORMALIZED  1.4235E+00
 RMS LND_FRC_MBLE                     1.7562E-01            NORMALIZED  2.0348E+00
 RMS P_FT                             3.6887E-01            NORMALIZED  2.3365E+00
 RMS P_IT                             3.5925E-01            NORMALIZED  2.3785E+00
 RMS SSR                              1.5230E-01            NORMALIZED  2.0614E+00
 RMS TLAI                             1.0072E+00            NORMALIZED  1.4418E+00
 RMS TSAI                             1.6746E-01            NORMALIZED  7.7983E-01
 RMS U_FT                             4.0920E+00            NORMALIZED  3.6157E+00
 RMS U_IT                             1.1551E+00            NORMALIZED  2.3022E+00
 RMS U_S_MEAN                         5.2116E-01            NORMALIZED  2.3157E+00
 RMS U_S_SIGMA                        7.6745E-02            NORMALIZED  2.4079E+00
 RMS VAI_OKIN                         1.8079E-01            NORMALIZED  3.4753E+00
 RMS WND_FRC_SOIL                     3.0178E-02            NORMALIZED  2.3157E+00
 RMS ZETAOBU                          4.7292E+01            NORMALIZED  7.4206E+00

grep "RMS" /glade/derecho/scratch/afoster/tests_0414-091736de/ERP_P128x2_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen.GC.0414-091736de_int/run/ERP_P128x2_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen.GC.0414-091736de_int.cpl.hi.2000-01-31-00000.nc.cprnc.out
 RMS lndImp_Fall_flxdst1              1.4137E-13            NORMALIZED  8.0939E-01
 RMS lndImp_Fall_flxdst2              7.5882E-13            NORMALIZED  8.0939E-01
 RMS lndImp_Fall_flxdst3              1.7794E-12            NORMALIZED  8.0939E-01
 RMS lndImp_Fall_flxdst4              1.6761E-12            NORMALIZED  8.0939E-01

```

    FAIL ERP_P256x2_Ld30.f45_f45_mg37.I2000Clm60FatesRs.derecho_intel.clm-mimicsFatesCold RUN time=42 (EXPECTED FAILURE)
    PEND ERP_P256x2_Ld30.f45_f45_mg37.I2000Clm60FatesRs.derecho_intel.clm-mimicsFatesCold COMPARE_base_rest
    FAIL ERP_P64x2_Ld396.f10_f10_mg37.IHistClm60Bgc.derecho_intel.clm-monthly--clm-matrixcnOn_ignore_warnings BASELINE ctsm5.3.038: DIFF (EXPECTED FAILURE)
    FAIL REP_P64x2_Ld396.f10_f10_mg37.IHistClm60Bgc.derecho_intel.clm-monthly--clm-matrixcnOn_ignore_warnings COMPARE_base_rep2 (EXPECTED FAILURE)
    FAIL REP_P64x2_Ld396.f10_f10_mg37.IHistClm60Bgc.derecho_intel.clm-monthly--clm-matrixcnOn_ignore_warnings BASELINE ctsm5.3.038: DIFF (EXPECTED FAILURE)
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.derecho_intel.clm-FatesFireLightningPopDens--clm-NEON-FATES-NIWO SHAREDLIB_BUILD time=16 (UNEXPECTED: expected FAIL)
    FAIL SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.derecho_intel.clm-FatesFireLightningPopDens--clm-NEON-FATES-NIWO RUN time=85 (EXPECTED FAILURE)

 
0414-091736de_nvh: 3 tests
    FAIL SMS_D.f10_f10_mg37.I2000Clm60BgcCrop.derecho_nvhpc.clm-crop RUN time=30 (EXPECTED FAILURE)
    FAIL SMS.f45_f45_mg37.I2000Clm60FatesSpRsGs.derecho_nvhpc.clm-FatesColdSatPhen BASELINE ctsm5.3.038: DIFF

```
grep "RMS" /glade/derecho/scratch/afoster/tests_0414-091736de/SMS.f45_f45_mg37.I2000Clm60FatesSpRsGs.derecho_nvhpc.clm-FatesColdSatPhen.GC.0414-091736de_nvh/run/SMS.f45_f45_mg37.I2000Clm60FatesSpRsGs.derecho_nvhpc.clm-FatesColdSatPhen.GC.0414-091736de_nvh.cpl.hi.2000-01-06-00000.nc.cprnc.out
 RMS lndImp_Fall_flxdst1              5.7865E-12            NORMALIZED  4.7810E+01
 RMS lndImp_Fall_flxdst2              3.1061E-11            NORMALIZED  4.7810E+01
 RMS lndImp_Fall_flxdst3              7.2834E-11            NORMALIZED  4.7810E+01
 RMS lndImp_Fall_flxdst4              6.8607E-11            NORMALIZED  4.7810E+01

grep "RMS" /glade/derecho/scratch/afoster/tests_0414-091736de/SMS.f45_f45_mg37.I2000Clm60FatesSpRsGs.derecho_nvhpc.clm-FatesColdSatPhen.GC.0414-091736de_nvh/run/SMS.f45_f45_mg37.I2000Clm60FatesSpRsGs.derecho_nvhpc.clm-FatesColdSatPhen.GC.0414-091736de_nvh.clm2.h0.2000-01-06-00000.nc.cprnc.out
 RMS ALPHA_TC_RATE                    8.9378E-03            NORMALIZED  1.0372E+01
 RMS DSTFLXT                          2.0588E-10            NORMALIZED  2.0559E+01
 RMS ETA                              8.8883E-03            NORMALIZED  1.1175E+01
 RMS FRC_THR_RGHN_FCT                 1.6288E-01            NORMALIZED  2.0251E+00
 RMS HTOP                             9.2588E+00            NORMALIZED  1.4235E+00
 RMS LND_FRC_MBLE                     1.9821E-01            NORMALIZED  2.1338E+00
 RMS P_FT                             3.6789E-01            NORMALIZED  2.3666E+00
 RMS P_IT                             3.6001E-01            NORMALIZED  2.3816E+00
 RMS SSR                              1.5258E-01            NORMALIZED  2.1147E+00
 RMS TLAI                             1.0271E+00            NORMALIZED  1.4369E+00
 RMS TSAI                             1.6835E-01            NORMALIZED  7.7606E-01
 RMS U_FT                             4.1120E+00            NORMALIZED  3.3602E+00
 RMS U_IT                             1.1530E+00            NORMALIZED  2.3472E+00
 RMS U_S_MEAN                         4.9382E-01            NORMALIZED  2.5067E+00
 RMS U_S_SIGMA                        7.1787E-02            NORMALIZED  2.5966E+00
 RMS VAI_OKIN                         1.7938E-01            NORMALIZED  3.5458E+00
 RMS WND_FRC_SOIL                     2.8595E-02            NORMALIZED  2.5067E+00
 RMS ZETAOBU                          4.1769E+01            NORMALIZED  7.7709E+00

```

------------------------------------------------------------------------
Testing results for fates on derecho:


0414-092045de_gnu: 10 tests
    FAIL PEM_D_Ld20.5x5_amazon.I2000Clm50FatesRs.derecho_gnu.clm-FatesColdSeedDisp COMPARE_base_modpes (EXPECTED FAILURE)
    FAIL SMS_D.1x1_brazil.I2000Clm60FatesSpCruRsGs.derecho_gnu.clm-FatesColdSatPhen BASELINE fates-sci.1.82.3_api.39.0.0-ctsm5.3.038: DIFF

```
grep "RMS" /glade/derecho/scratch/afoster/tests_0414-092045de/SMS_D.1x1_brazil.I2000Clm60FatesSpCruRsGs.derecho_gnu.clm-FatesColdSatPhen.GC.0414-092045de_gnu/run/SMS_D.1x1_brazil.I2000Clm60FatesSpCruRsGs.derecho_gnu.clm-FatesColdSatPhen.GC.0414-092045de_gnu.clm2.h0.2000-01-06-00000.nc.cprnc.out
 RMS HTOP                             1.9450E+01            NORMALIZED  9.4802E-01
 RMS TLAI                             2.7786E+00            NORMALIZED  8.3487E-01
 RMS TSAI                             4.9343E-01            NORMALIZED  7.9647E-01
```

    FAIL SMS_D_Ld3.f09_g17.I2000Clm60FatesSpCruRsGs.derecho_gnu.clm-FatesColdSatPhen_prescribed RUN time=100 (EXPECTED FAILURE)
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.derecho_gnu.clm-FatesPRISM--clm-NEON-FATES-YELL SHAREDLIB_BUILD time=128 (UNEXPECTED: expected FAIL)
    FAIL SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.derecho_gnu.clm-FatesPRISM--clm-NEON-FATES-YELL RUN time=97 (EXPECTED FAILURE)

0414-092045de_int: 39 tests
    FAIL ERP_P128x2_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen BASELINE fates-sci.1.82.3_api.39.0.0-ctsm5.3.038: DIFF

```
grep "RMS" /glade/derecho/scratch/afoster/tests_0414-092045de/ERP_P128x2_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen.GC.0414-092045de_int/run/ERP_P128x2_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen.GC.0414-092045de_int.cpl.hi.2000-01-31-00000.nc.cprnc.out
 RMS lndImp_Fall_flxdst1              1.4137E-13            NORMALIZED  8.0939E-01
 RMS lndImp_Fall_flxdst2              7.5882E-13            NORMALIZED  8.0939E-01
 RMS lndImp_Fall_flxdst3              1.7794E-12            NORMALIZED  8.0939E-01
 RMS lndImp_Fall_flxdst4              1.6761E-12            NORMALIZED  8.0939E-01

grep "RMS" /glade/derecho/scratch/afoster/tests_0414-092045de/ERP_P128x2_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen.GC.0414-092045de_int/run/ERP_P128x2_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen.GC.0414-092045de_int.clm2.h0.2000-01-31-00000.nc.cprnc.out
 RMS ALPHA_TC_RATE                    2.0184E-02            NORMALIZED  6.4123E+00
 RMS DSTFLXT                          4.9946E-10            NORMALIZED  9.5686E+00
 RMS ETA                              2.2085E-02            NORMALIZED  7.1768E+00
 RMS FRC_THR_RGHN_FCT                 1.6212E-01            NORMALIZED  1.9717E+00
 RMS HTOP                             9.2588E+00            NORMALIZED  1.4235E+00
 RMS LND_FRC_MBLE                     1.7562E-01            NORMALIZED  2.0348E+00
 RMS P_FT                             3.6887E-01            NORMALIZED  2.3365E+00
 RMS P_IT                             3.5925E-01            NORMALIZED  2.3785E+00
 RMS SSR                              1.5230E-01            NORMALIZED  2.0614E+00
 RMS TLAI                             1.0072E+00            NORMALIZED  1.4418E+00
 RMS TSAI                             1.6746E-01            NORMALIZED  7.7983E-01
 RMS U_FT                             4.0920E+00            NORMALIZED  3.6157E+00
 RMS U_IT                             1.1551E+00            NORMALIZED  2.3022E+00
 RMS U_S_MEAN                         5.2116E-01            NORMALIZED  2.3157E+00
 RMS U_S_SIGMA                        7.6745E-02            NORMALIZED  2.4079E+00
 RMS VAI_OKIN                         1.8079E-01            NORMALIZED  3.4753E+00
 RMS WND_FRC_SOIL                     3.0178E-02            NORMALIZED  2.3157E+00
 RMS ZETAOBU                          4.7292E+01            NORMALIZED  7.4206E+00


```

    FAIL ERP_P256x2_Ld30.f45_f45_mg37.I2000Clm60FatesRs.derecho_intel.clm-mimicsFatesCold RUN time=42 (EXPECTED FAILURE)
    PEND ERP_P256x2_Ld30.f45_f45_mg37.I2000Clm60FatesRs.derecho_intel.clm-mimicsFatesCold COMPARE_base_rest
    FAIL ERS_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen BASELINE fates-sci.1.82.3_api.39.0.0-ctsm5.3.038: DIFF

```
grep "RMS" /glade/derecho/scratch/afoster/tests_0414-092045de/ERS_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen.GC.0414-092045de_int/run/ERS_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen.GC.0414-092045de_int.cpl.hi.2000-01-31-00000.nc.cprnc.out
 RMS lndImp_Fall_flxdst1              1.4137E-13            NORMALIZED  8.0939E-01
 RMS lndImp_Fall_flxdst2              7.5882E-13            NORMALIZED  8.0939E-01
 RMS lndImp_Fall_flxdst3              1.7794E-12            NORMALIZED  8.0939E-01
 RMS lndImp_Fall_flxdst4              1.6761E-12            NORMALIZED  8.0939E-01

grep "RMS" /glade/derecho/scratch/afoster/tests_0414-092045de/ERS_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen.GC.0414-092045de_int/run/ERS_Ld30.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdSatPhen.GC.0414-092045de_int.clm2.h0.2000-01-31-00000.nc.cprnc.out
 RMS ALPHA_TC_RATE                    2.0184E-02            NORMALIZED  6.4123E+00
 RMS DSTFLXT                          4.9946E-10            NORMALIZED  9.5686E+00
 RMS ETA                              2.2085E-02            NORMALIZED  7.1768E+00
 RMS FRC_THR_RGHN_FCT                 1.6212E-01            NORMALIZED  1.9717E+00
 RMS HTOP                             9.2588E+00            NORMALIZED  1.4235E+00
 RMS LND_FRC_MBLE                     1.7562E-01            NORMALIZED  2.0348E+00
 RMS P_FT                             3.6887E-01            NORMALIZED  2.3365E+00
 RMS P_IT                             3.5925E-01            NORMALIZED  2.3785E+00
 RMS SSR                              1.5230E-01            NORMALIZED  2.0614E+00
 RMS TLAI                             1.0072E+00            NORMALIZED  1.4418E+00
 RMS TSAI                             1.6746E-01            NORMALIZED  7.7983E-01
 RMS U_FT                             4.0920E+00            NORMALIZED  3.6157E+00
 RMS U_IT                             1.1551E+00            NORMALIZED  2.3022E+00
 RMS U_S_MEAN                         5.2116E-01            NORMALIZED  2.3157E+00
 RMS U_S_SIGMA                        7.6745E-02            NORMALIZED  2.4079E+00
 RMS VAI_OKIN                         1.8079E-01            NORMALIZED  3.4753E+00
 RMS WND_FRC_SOIL                     3.0178E-02            NORMALIZED  2.3157E+00
 RMS ZETAOBU                          4.7292E+01            NORMALIZED  7.4206E+00
 ```

    FAIL ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdST3 RUN time=29 (EXPECTED FAILURE)
    FAIL PVT_Lm3.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesLUPFT RUN time=1303 (EXPECTED FAILURE)
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.derecho_intel.clm-FatesFireLightningPopDens--clm-NEON-FATES-NIWO SHAREDLIB_BUILD time=103 (UNEXPECTED: expected FAIL)
    FAIL SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.derecho_intel.clm-FatesFireLightningPopDens--clm-NEON-FATES-NIWO RUN time=86 (EXPECTED FAILURE)
    FAIL SMS_Lm1.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdBasic BASELINE fates-sci.1.82.3_api.39.0.0-ctsm5.3.038: DIFF

```
grep "RMS" /glade/derecho/scratch/afoster/tests_0414-092045de/SMS_Lm1.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdBasic.GC.0414-092045de_int/run/SMS_Lm1.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdBasic.GC.0414-092045de_int.cpl.hi.2000-02-01-00000.nc.cprnc.out
 RMS lndImp_Fall_flxdst1              1.7867E-12            NORMALIZED  1.1653E+01
 RMS lndImp_Fall_flxdst2              9.5907E-12            NORMALIZED  1.1653E+01
 RMS lndImp_Fall_flxdst3              2.2489E-11            NORMALIZED  1.1653E+01
 RMS lndImp_Fall_flxdst4              2.1184E-11            NORMALIZED  1.1653E+01

grep "RMS" /glade/derecho/scratch/afoster/tests_0414-092045de/SMS_Lm1.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdBasic.GC.0414-092045de_int/run/SMS_Lm1.f45_f45_mg37.I2000Clm60FatesSpCruRsGs.derecho_intel.clm-FatesColdBasic.GC.0414-092045de_int.clm2.h0.2000-01.nc.cprnc.out
 RMS ALPHA_TC_RATE                    9.7230E-03            NORMALIZED  4.8018E+00
 RMS DSTFLXT                          2.1990E-10            NORMALIZED  7.0259E+00
 RMS ETA                              9.7896E-03            NORMALIZED  5.0198E+00
 RMS FRC_THR_RGHN_FCT                 1.6187E-01            NORMALIZED  1.9920E+00
 RMS HTOP                             9.2588E+00            NORMALIZED  1.4235E+00
 RMS LND_FRC_MBLE                     1.8608E-01            NORMALIZED  2.0763E+00
 RMS P_FT                             3.6597E-01            NORMALIZED  2.3358E+00
 RMS P_IT                             3.5736E-01            NORMALIZED  2.3561E+00
 RMS SSR                              1.5204E-01            NORMALIZED  2.0838E+00
 RMS TLAI                             1.0170E+00            NORMALIZED  1.4389E+00
 RMS TSAI                             1.6770E-01            NORMALIZED  7.7752E-01
 RMS U_FT                             4.0170E+00            NORMALIZED  3.4518E+00
 RMS U_IT                             1.1445E+00            NORMALIZED  2.3085E+00
 RMS U_S_MEAN                         4.6015E-01            NORMALIZED  2.3068E+00
 RMS U_S_SIGMA                        6.7311E-02            NORMALIZED  2.3940E+00
 RMS VAI_OKIN                         1.7694E-01            NORMALIZED  3.4516E+00
 RMS WND_FRC_SOIL                     2.6645E-02            NORMALIZED  2.3068E+00
 RMS ZETAOBU                          2.4688E+01            NORMALIZED  5.2118E+00

 ```

0414-092045de_nvh: 1 test
    FAIL SMS.f45_f45_mg37.I2000Clm60FatesSpRsGs.derecho_nvhpc.clm-FatesColdSatPhen BASELINE fates-sci.1.82.3_api.39.0.0-ctsm5.3.038: DIFF

```
grep "RMS" /glade/derecho/scratch/afoster/tests_0414-092045de/SMS.f45_f45_mg37.I2000Clm60FatesSpRsGs.derecho_nvhpc.clm-FatesColdSatPhen.GC.0414-092045de_nvh/run/SMS.f45_f45_mg37.I2000Clm60FatesSpRsGs.derecho_nvhpc.clm-FatesColdSatPhen.GC.0414-092045de_nvh.clm2.h0.2000-01-06-00000.nc.cprnc.out
 RMS ALPHA_TC_RATE                    8.9378E-03            NORMALIZED  1.0372E+01
 RMS DSTFLXT                          2.0588E-10            NORMALIZED  2.0559E+01
 RMS ETA                              8.8883E-03            NORMALIZED  1.1175E+01
 RMS FRC_THR_RGHN_FCT                 1.6288E-01            NORMALIZED  2.0251E+00
 RMS HTOP                             9.2588E+00            NORMALIZED  1.4235E+00
 RMS LND_FRC_MBLE                     1.9821E-01            NORMALIZED  2.1338E+00
 RMS P_FT                             3.6789E-01            NORMALIZED  2.3666E+00
 RMS P_IT                             3.6001E-01            NORMALIZED  2.3816E+00
 RMS SSR                              1.5258E-01            NORMALIZED  2.1147E+00
 RMS TLAI                             1.0271E+00            NORMALIZED  1.4369E+00
 RMS TSAI                             1.6835E-01            NORMALIZED  7.7606E-01
 RMS U_FT                             4.1120E+00            NORMALIZED  3.3602E+00
 RMS U_IT                             1.1530E+00            NORMALIZED  2.3472E+00
 RMS U_S_MEAN                         4.9382E-01            NORMALIZED  2.5067E+00
 RMS U_S_SIGMA                        7.1787E-02            NORMALIZED  2.5966E+00
 RMS VAI_OKIN                         1.7938E-01            NORMALIZED  3.5458E+00
 RMS WND_FRC_SOIL                     2.8595E-02            NORMALIZED  2.5067E+00
 RMS ZETAOBU                          4.1769E+01            NORMALIZED  7.7709E+00
 
grep "RMS" /glade/derecho/scratch/afoster/tests_0414-092045de/SMS.f45_f45_mg37.I2000Clm60FatesSpRsGs.derecho_nvhpc.clm-FatesColdSatPhen.GC.0414-092045de_nvh/run/SMS.f45_f45_mg37.I2000Clm60FatesSpRsGs.derecho_nvhpc.clm-FatesColdSatPhen.GC.0414-092045de_nvh.cpl.hi.2000-01-06-00000.nc.cprnc.out
 RMS lndImp_Fall_flxdst1              5.7865E-12            NORMALIZED  4.7810E+01
 RMS lndImp_Fall_flxdst2              3.1061E-11            NORMALIZED  4.7810E+01
 RMS lndImp_Fall_flxdst3              7.2834E-11            NORMALIZED  4.7810E+01
 RMS lndImp_Fall_flxdst4              6.8607E-11            NORMALIZED  4.7810E+01
 
 ```

**Review by ekluzek — APPROVED** [review]

**Comment by ekluzek** [comment]
Awesome. Thanks for that confirmation that you were expecting this.

I just did a tiny bit of checking, since, you expected it. And yes these all have to do with Leung dust emissions and the change in TLAI and TSAI would explain the difference. And the ones with the differences are only the Clm60 compsets, so would have a dependency on LAI and SAI because of Leung dust emissions. And that explains why they change. So I agree this is all good.

Thanks for putting the differences in the PR, so we have the history recorded of what the differences are.

**Comment by adrifoster** [comment]
Test results for `fates` suite on izumi:
0414-151031iz_nag: 9 tests
    FAIL ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.izumi_nag.clm-FatesColdLUH2 RUN time=37 (EXPECTED FAILURE)
    PEND ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.izumi_nag.clm-FatesColdPRT2 RUN (EXPECTED FAILURE)
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.izumi_nag.clm-FatesFireLightningPopDens--clm-NEON-FATES-NIWO SHAREDLIB_BUILD time=156 (UNEXPECTED: expected FAIL)
    FAIL SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.izumi_nag.clm-FatesFireLightningPopDens--clm-NEON-FATES-NIWO RUN time=473 (EXPECTED FAILURE)
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.izumi_nag.clm-FatesPRISM--clm-NEON-FATES-YELL SHAREDLIB_BUILD time=14 (UNEXPECTED: expected FAIL)
    FAIL SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.izumi_nag.clm-FatesPRISM--clm-NEON-FATES-YELL RUN time=458 (EXPECTED FAILURE)

test results for `aux_clm` suite on izumi:

19:12 $ ./cs.status.fails
0414-142152iz_int: 1 test

 
0414-142152iz_nag: 47 tests
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Bgc.izumi_nag.clm-default--clm-NEON-HARV--clm-matrixcnOn RUN time=334 (UNEXPECTED: expected FAIL)
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Bgc.izumi_nag.clm-NEON-MOAB--clm-PRISM SHAREDLIB_BUILD time=15 (UNEXPECTED: expected FAIL)
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Bgc.izumi_nag.clm-NEON-MOAB--clm-PRISM RUN time=299 (UNEXPECTED: expected FAIL)
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.izumi_nag.clm-FatesFireLightningPopDens--clm-NEON-FATES-NIWO SHAREDLIB_BUILD time=15 (UNEXPECTED: expected FAIL)
    FAIL SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.izumi_nag.clm-FatesFireLightningPopDens--clm-NEON-FATES-NIWO RUN time=477 (EXPECTED FAILURE)
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.izumi_nag.clm-FatesPRISM--clm-NEON-FATES-YELL SHAREDLIB_BUILD time=15 (UNEXPECTED: expected FAIL)
    FAIL SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.izumi_nag.clm-FatesPRISM--clm-NEON-FATES-YELL RUN time=458 (EXPECTED FAILURE)
