### PR TITLE
MIMICS into vertically resolved CTSM

### LINKED ISSUE #1473: decomp_depth_efolding appears (with the same value) in the namelist and the params files; the model ends up using the one from the namelist
### Brief summary of bug
`decomp_depth_efolding` appears (with the same value) in the namelist and the params files; the model ends up using the one from the namelist. I report this as a bug because users may wrongly believe that they can change the value of this parameter by updating the params files.

### General bug information

**CTSM version you are using:**
ctsm5.1.dev053-48-g1c1a9451

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]
No, unless user thought that they were modifying the value via the params files.

**Configurations affected:**
Configurations using vertically resolved DecompCascadeBGC or DecompCascadeCN (deprecated) for below-ground decomposition.

### Details of bug
Summary gives enough detail.
To correct, @slevisconsulting will remove `decomp_depth_efolding` from the namelist.

### PR DESCRIPTION
**Pull request by slevisconsulting**
### Description of changes
Adding new model of below-ground biogeochemistry to the CTSM.

### Specific notes
Getting MIMICS from Wieder et al. 2015 and [from testbed](https://github.com/wwieder/biogeochem_testbed_1.1/blob/Testbed_CN/SOURCE_CODE/mimics_cycle_CN.f90) into the vertically resolved CTSM.

Related issue: #1260

Contributors other than yourself, if any:
@wwieder @ekluzek 

CTSM Issues Fixed (include github issue #):
   Fixes #1473

Are answers expected to change (and if so in what way)?   
   No when comparing to answers from CTSM's existing below-ground bgc model(s).

Any User Interface Changes (namelist or namelist defaults changes)?
  soilbgc_decomp can now also be MIMICSWieder2015

Testing performed, if any: regular testing

### CODE REVIEW

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 1]
```diff
@@ -0,0 +1,1302 @@
+module SoilBiogeochemDecompCascadeMIMICSMod
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:1]: This entire file is new, so to see what I did this far to SoilBiogeochemDecompCascadeBGCMod.F90, you will need to look at the changes from my second commit.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 2]
```diff
@@ -1,15 +1,15 @@
...
   ! Sets the coeffiecients used in the decomposition cascade submodel.  
-  ! This uses the CENTURY/BGC parameters
+  ! This uses the MIMICS parameters.
   !
   ! !USES:
   use shr_kind_mod                       , only : r8 => shr_kind_r8
   use shr_const_mod                      , only : SHR_CONST_TKFRZ
   use shr_log_mod                        , only : errMsg => shr_log_errMsg
-  use clm_varpar                         , only : nlevsoi, nlevgrnd, nlevdecomp, ndecomp_cascade_transitions, ndecomp_pools
+  use clm_varpar                         , only : nlevdecomp
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:12]: Removed items that are not in use.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 3]
```diff
@@ -173,88 +198,116 @@ subroutine readParams ( ncid )
...
     logical            :: readv   ! has variable been read in or not
     real(r8)           :: tempr   ! temporary to read in constant
     character(len=100) :: tString ! temp. var for reading
     !-----------------------------------------------------------------------
 
     ! Read off of netcdf file
-    tString='tau_l1'
+    ! TODO slevis: new params will be added here and in the params file
+    ! TODO slevis: Keep tau_cwd?
+    tString='tau_cwd'
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:211]: This and the next few are not new. The differencing code interpreted them as new.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 4]
```diff
@@ -173,88 +198,116 @@ subroutine readParams ( ncid )
...
-    tString='tau_s2'
+    tString='cn_s3_bgc'
     call ncd_io(trim(tString),tempr, 'read', ncid, readvar=readv)
     if ( .not. readv ) call endrun(msg=trim(errCode)//trim(tString)//errMsg(sourcefile, __LINE__))
-    params_inst%tau_s2_bgc=tempr
+    params_inst%cn_s3_bgc=tempr
 
-    tString='tau_s3'
+    ! TODO slevis: rf params changing
+    tString='rf_l1m1_mimics'
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:232]: Here we get to new parameters (with suffix _mimcs)

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 5]
```diff
@@ -530,6 +616,36 @@ subroutine init_decompcascade_bgc(bounds, soilbiogeochem_state_inst, soilstate_i
       is_cellulose(i_soil3) = .false.
       is_lignin(i_soil3) = .false.
 
+      floating_cn_ratio_decomp_pools(i_micr1) = .true.
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:619]: These new paragraphs follow the prev. paragraphs as a template. Things may need to be corrected.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 6]
```diff
@@ -805,7 +1066,6 @@ subroutine decomp_rate_constants_bgc(bounds, num_soilc, filter_soilc, &
          ! the following normalizes values in fr so that they
          ! sum to 1.0 across top nlevdecomp levels on a column
          frw(bounds%begc:bounds%endc) = 0._r8
-         nlev_soildecomp_standard=5
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90]: Redundant as far as I can tell.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 7]
```diff
@@ -792,10 +1042,21 @@ subroutine decomp_rate_constants_bgc(bounds, num_soilc, filter_soilc, &
...
             spinup_geogterm_s3(c) = 1._r8
+            spinup_geogterm_m1(c) = 1._r8
+            spinup_geogterm_m2(c) = 1._r8
          end do
       endif
 
       !--- time dependent coefficients-----!
+      ! TODO slevis: Not immediately obvious how to reduce the if-else
+      !      repetition, bc t_scalar, w_scalar, o_scalar sum all j
+      !      to layer 1 in the if, while they do not in the else.
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:1053]: @wwieder you mentioned that we would use w_scalar and o_scalar but didn't mention t_scalar. Regardless of whether we reduce the if-else repetition, I wanted to go over with you what we're keeping and what we're discarding from this section.

Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:1053]: ...so pls ignore for now the next few lines of comments.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 8]
```diff
@@ -975,84 +1235,68 @@ subroutine decomp_rate_constants_bgc(bounds, num_soilc, filter_soilc, &
...
+!              c = filter_soilc(fc)
+!              t_scalar(c,j) = t_scalar(c,j) * normalization_factor
+!           end do
+!        end do
+!     endif
+
+      ! Term that reduces decomposition rate at depth
+      ! TODO slevis: Reduced code repetition by defining
+      !              depth_scalar(c,j) = 1.0_r8 in the else instead of
+      !              repeating the decomp_k lines.
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:1253]: In this case I successfully reduced some code repetition.

Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:1253]: For now, all the changes below this line are due to the consolidation of repetitive code.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 1 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:1]: I have drawn attention to a few items with my posts here in the PR. I have also included several TODO comments directly in the code where I sometimes seek clarification for something.

@wwieder feel free to look over everything and/or it may be a good time to set up a meeting to go over progress this far and identify the next steps.

**Comment by wwieder** [comment]
This is awesome Sam.  Tomorrow is mostly meetings for me, but looks like
Friday could work?  Would it be helpful to include Erik re. SE questions or
just with me for science type stuff?  In the meantime, I'll set up a
meeting for all.

**Comment by slevisconsulting** [comment]
At this stage I am mostly concerned with science questions. 
@ekluzek up to you whether you attend on Friday.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 9]
```diff
@@ -51,28 +51,52 @@ module SoilBiogeochemDecompCascadeBGCMod
...
+     !              tau params define microbial turnover to SOM. Update params
+     !              file if necessary.
+     real(r8):: tau_l1_mimics     ! 1/turnover time of litter 1 (1/yr)
+     real(r8):: tau_l2_l3_mimics  ! 1/turnover time of litter 2 and 3 (1/yr)
+     real(r8):: tau_s1_mimics     ! 1/turnover time of SOM 1 (1/yr)
+     real(r8):: tau_s2_mimics     ! 1/turnover time of SOM 2 (1/yr)
+     real(r8):: tau_s3_mimics     ! 1/turnover time of SOM 3 (1/yr)
+     real(r8):: tau_m1_mimics     ! 1/turnover time of microbial 1 (1/yr)
+     real(r8):: tau_m2_mimics     ! 1/turnover time of microbial 2 (1/yr)
+     ! TODO slevis: Keep?
```
Comment (wwieder) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:99]: here I think we just want the turnover of microbial pools `tau_m1_mimics` & `tau_m2_mimics`, which are actually functions.  I don't know how best to implement the Vmax and Km functions that are needed to calculate decompositon rates in MIMICS.  Maybe:
`Vmax_l1_m1_mimics`, `Vmax_l2_m1_mimics`,`Vmax_s2_m1_mimics` etc.

Comment (wwieder) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:99]: below, we'll use tau_cwd_bgc, but cwd_fcel_bgc is not relevent.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 10]
```diff
@@ -118,7 +143,7 @@ subroutine DecompCascadeBGCreadNML( NLFilename )
     integer :: ierr                 ! error code
     integer :: unitn                ! unit for namelist file
 
-    character(len=*), parameter :: subname = 'DecompCascadeBGCreadNML'
+    character(len=*), parameter :: subname = 'DecompCascadeMIMICSreadNML'
     character(len=*), parameter :: nmlname = 'CENTURY_soilBGCDecompCascade'
```
Comment (wwieder) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:147]: is this accurate?

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 3 above)
Comment (wwieder) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:211]: see comment above on C:N ratios

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 4 above)
Comment (wwieder) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:232]: again see comment above on rf (again, we only need 6).

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 11]
```diff
@@ -294,11 +347,11 @@ subroutine readParams ( ncid )
...
 
   !-----------------------------------------------------------------------
-  subroutine init_decompcascade_bgc(bounds, soilbiogeochem_state_inst, soilstate_inst )
+  subroutine init_decompcascade_mimcs(bounds, soilbiogeochem_state_inst, soilstate_inst )
     !
     ! !DESCRIPTION:
-    !  initialize rate constants and decomposition pathways following the decomposition cascade of the BGC model.
-    !  written by C. Koven 
+    ! initialize rate constants and decomposition pathways following the
+    ! decomposition cascade of the MIMICS model.
```
Comment (wwieder) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:354]: we can discuss this tomorrow...

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 12]
```diff
@@ -398,16 +475,18 @@ subroutine init_decompcascade_bgc(bounds, soilbiogeochem_state_inst, soilstate_i
...
       ! set path fractions
-      f_s2s1 = 0.42_r8/(0.45_r8)
       f_s2s3 = 0.03_r8/(0.45_r8)
 
       ! some of these are dependent on the soil texture properties
+      ! TODO slevis: Template for calculated mimics params?
+      !              But soil texture remains const with time.
+      !              So one-time initializations here and time-dep params
+      !              in subr. decomp_rate_constants_mimics.
+
```
Comment (wwieder) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:485]: I think this makes sense

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 5 above)
Comment (wwieder) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:619]: yes, we can go through this if needed

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 13]
```diff
@@ -51,28 +51,52 @@ module SoilBiogeochemDecompCascadeBGCMod
   integer, private, parameter :: i_litr1   = i_met_lit  ! First litter pool, metobolic
   integer, private, parameter :: i_litr2   = i_cel_lit  ! Second litter pool, cellulose
   integer, private, parameter :: i_litr3   = i_lig_lit  ! Third litter pool, lignin
+  integer, private, parameter :: i_micr1   = i_micr_r   ! First microbial pool, copiotrophic, as labeled in Wieder et al. 2015
+  integer, private, parameter :: i_micr2   = i_micr_k   ! Second microbial pool, oligotrophic, as labeled in Wieder et al. 2015
```
Comment (wwieder) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:56]: were are the som pools defined?  we should clarify SOMp, SOMc, and SOMa as som1, som2, som3

**Review by wwieder — COMMENTED** [review]
lots of good stuff here, Sam.
looking forward to talking  tomorrow.
Also,  I accidentally resolved a comments re. t_scalar.  Not sure what it was, but we won't use t_scalar in mimics

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 2 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:12]: In the BGC version of this module these are not used. I may need to bring them back if I discover that the MIMICS version of the module requires them. For now though we don't need to worry about this.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 7 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:1053]: @wwieder wrote by email "we won't use t_scalar in mimics."

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 13 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:56]: Ok, done!

@wwieder this comment, together with comments about 2 litter pools not 3, helped me realize that I wasn't thinking of `i_cwd, i_soil1, i_soil2, i_soil3, i_micr1, i_micr2` correctly. I have reworked these and will explain in our meeting.

**Comment by slevisconsulting** [comment]
> looking forward to talking tomorrow.

@wwieder thank you for looking over my initial work!

It's late in the day anyway, but I wanted to be clear that I'm NOT requesting that you go over my latest changes before our meeting :-)

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 14]
```diff
@@ -1,15 +1,15 @@
...
+  ! This uses the MIMICS parameters.
   !
   ! !USES:
   use shr_kind_mod                       , only : r8 => shr_kind_r8
   use shr_const_mod                      , only : SHR_CONST_TKFRZ
   use shr_log_mod                        , only : errMsg => shr_log_errMsg
-  use clm_varpar                         , only : nlevsoi, nlevgrnd, nlevdecomp, ndecomp_cascade_transitions, ndecomp_pools
+  use clm_varpar                         , only : nlevdecomp
   use clm_varpar                         , only : i_met_lit, i_cel_lit, i_lig_lit, i_cwd
   use clm_varctl                         , only : iulog, spinup_state, anoxia, use_lch4, use_vertsoilc, use_fates
```
[the remark this answers is not in the document]
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:14]: We didn't address this in Friday's meeting, so I will mark it with googly eyes as still to investigate.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 10 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:119]: This whole subroutine is now gone.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 15]
```diff
@@ -0,0 +1,924 @@
...
+    end associate
+
+  end subroutine init_decompcascade_mimics
+
+  !-----------------------------------------------------------------------
+  subroutine decomp_rates_mimics(bounds, num_soilc, filter_soilc, &
+       soilstate_inst, temperature_inst, ch4_inst, soilbiogeochem_carbonflux_inst)
+    !
+    ! !DESCRIPTION:
+    ! Calculate rate constants and decomposition pathways for the MIMICS
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:514]: I missed all these comments that still say "rate constants" in the latest commit. I marked them for the next commit :-)

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 14 above)
[the remark this answers is not in the document]
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:14]: ...better yet, I'm adding a comment raising this concern directly in the code.

File: src/main/clm_varpar.F90 [hunk 16]
```diff
@@ -227,20 +228,31 @@ subroutine clm_varpar_init(actual_maxsoil_patches, actual_numcft)
        write(iulog, *)
     end if
 
+    ! TODO BFB refactor: How to derive these instead of hardwiring?
```
Comment (slevisconsulting) [inline src/main/clm_varpar.F90:231]: I gave this a try today and failed due to the order of initializations in the code:

Deriving `ndecomp_pools` and `ndecomp_cascade_transitions` on the fly rather than hardwiring, means initializing them in `init_decompcascade_bgc` or `init_decompcascade_cn` or 'init_decompcascade_mimics`. However, we use these parameters earlier in `InitAllocate` (in `SoilBiogeochemStateType`).

Reordering initializations feels like a bigger refactor than I should attempt here.

Comment (wwieder) [reply src/main/clm_varpar.F90:231]: This is fine with me, @slevisconsulting .  Is it helpful to have another meeting, or do you feel like there's more you can continue working on?

Comment (slevisconsulting) [reply src/main/clm_varpar.F90:231]: As @ekluzek recommended, I created a refactor branch and am working on the refactor ideas that have come up this far. Soon thereafter we should meet. Would Tuesday or Monday next week work? I'm happy to book it if I can point to the same zoom info as we used last time. Otherwise feel free to book it @wwieder because my zoom acct permits up to 40-min meetings.

File: src/biogeochem/CNCStateUpdate1Mod.F90 [hunk 17]
```diff
@@ -69,6 +69,14 @@ subroutine CStateUpdateDynPatch(bounds, num_soilc_with_inactive, filter_soilc_wi
...
           do fc = 1, num_soilc_with_inactive
              c = filter_soilc_with_inactive(fc)
+             ! TODO BFB refactor: In loops like this, we will run into trouble
+             !      with MIMICS bc we will have 2 instead of 3 litter pools. Can
+             !      address with if statements (NOT ideal) or
+             !      turn these repetitive lines into a loop BUT to do that
+             !      we need to turn dwt_frootc_to_litr_* into a 3d var.
+             !      There are 3 such loops here, 2 in CNCStateUpdate2, and one
+             !      in CNCStateUpdate1 and the pattern repeats in the
+             !      corresponding N modules.
```
Comment (slevisconsulting) [inline src/biogeochem/CNCStateUpdate1Mod.F90:79]: @wwieder and @ekluzek I'm interested in your input regarding this refactor. It seems straightforward but it touches a fair number of variables. One way or another we will have to address this for MIMICS to work, correct me if I'm wrong.

Comment (slevisconsulting) [reply src/biogeochem/CNCStateUpdate1Mod.F90:79]: I posted an update of this in [the refactor PR.](https://github.com/ESCOMP/CTSM/pull/1340/files#r613643764)

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 18]
```diff
@@ -0,0 +1,925 @@
...
+  public :: DecompCascadeMIMICSreadNML      ! Read in namelist
+  public :: readParams                      ! Read in parameters from params file
+  public :: init_decompcascade_mimics       ! Initialization
+  public :: decomp_rates_mimics             ! Figure out decomposition rates
+  !
+  ! !PUBLIC DATA MEMBERS 
+  !
+  ! !PRIVATE DATA MEMBERS 
+
+  integer, private, parameter :: npools = 8             ! Number of pools
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:44]: I can remove npools and use ndecomp_pools instead.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 1 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:1]: This note for reference:
This entire file `SoilBiogeochemDecompCascadeMIMICSMod.F90` is new, so to see how it now differs from `SoilBiogeochemDecompCascadeBGCMod.F90`, compare my first commit in this PR to my current commit in this PR, e.g.:
`git diff 9985a65 446b587` and search for mimics

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 19]
```diff
@@ -0,0 +1,917 @@
...
+  type, private :: params_type
+     ! TODO BFB refactor: First merge the refactor branch to CTSM main
+     ! TODO slevis: New rf params in MIMICS. Update params file accordingly.
+     !              I haven't identified what these correspond to in testbed.
+     real(r8):: rf_l1m1_mimics  ! respiration fraction litter 1 -> microbe 1
+     real(r8):: rf_l2m1_mimics
+     real(r8):: rf_s3m1_mimics  ! respiration fraction soil 3 -> microbe 1
+     real(r8):: rf_l1m2_mimics
+     real(r8):: rf_l2m2_mimics
+     real(r8):: rf_s3m2_mimics
```
[the remark this answers is not in the document]
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:59]: MIMICS params file:
https://github.com/wwieder/biogeochem_testbed_1.1/blob/Testbed_CN/EXAMPLE_GRID/pftlookup_LIDET-MIM-REV_lowerKM_v11.28.2017.csv

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 20]
```diff
@@ -0,0 +1,917 @@
...
+
+! TODO slevis: tau params are changing; map to Wieder et al. 2015
+! From testbed code
+! ------------------
+
+! Vmax, tau*, and Km are time-dependent
+
+! Table B1 Wieder et al. 2015 gives
+! Vslope = 0.063, Vint = 5.47, av = 8e-6
+! Vmod_r = 10,2,10, Vmod_K = 3,3,2 (for LITm,s,SOMa --> MICr,K respectively)
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:611]: Make Vmod = Vmod * av

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 19 above)
[the remark this answers is not in the document]
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:59]: Get updated MIMICS params file from @wwieder when ready to get values in CTSM params file.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 21]
```diff
@@ -0,0 +1,917 @@
...
+            end if
+         end do
+      end do
+
+      ! calculate rates for all litter and som pools
+      ! TODO I will start updating this section when I feel confident in my list
+      !      of k_ factors. For example
+      !      - Should decomp_k be dimensioned (c,j,i_l1m1) instead?
+      !      - Should there be two sets of decomp_k, the first corresponding to
+      !        vmax and the second to km?
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:884]: No need for two sets of decomp_k.
In mimics_cycle_CN line 1688 and on, remove the pool (LITm, LITs, ...) from the formulas, and you have the new decomp_k rate.

File: src/main/clm_varpar.F90 [hunk 22]
```diff
@@ -63,6 +64,8 @@ module clm_varpar
 
   ! constants for decomposition cascade
 
+  integer, public, parameter :: i_micr_r   = 1
+  integer, public, parameter :: i_micr_k   = i_micr_r + 1
   integer, public, parameter :: i_met_lit  = 1
```
[the remark this answers is not in the document]
Comment (slevisconsulting) [reply src/main/clm_varpar.F90]: Trying `i_str_lit` for now.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 23]
```diff
@@ -0,0 +1,1024 @@
...
+            ! TODO Combine multiple terms of same donor pools...
+            ! TODO Where to calculate m1_pool and m2_pool?
+            ! TODO When to introduce litter/soil biomass to the calculation?
+            ! TODO Excluded spinup terms for now. See cwd below how used.
+            decomp_k(c,j,i_met_lit) = (vmax_l1_m1 * m1_pool(c,j) / &
+                                       (km_l1_m1 + m1_pool(c,j))) * &
+                                      w_d_o_scalars
+            decomp_k(c,j,i_met_lit) = (vmax_l1_m2 * m2_pool(c,j) / &
+                                       (km_l1_m2 + m2_pool(c,j))) * &
+                                      w_d_o_scalars
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:979]: look into changing 3rd index to donor-receiver pair indices.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 24]
```diff
@@ -0,0 +1,1024 @@
...
+            decomp_k(c,j,i_str_lit) = (vmax_l2_m2 * m2_pool(c,j) / &
+                                       (km_l2_m2 + m2_pool(c,j))) * &
+                                      w_d_o_scalars
+
+            decomp_k(c,j,i_pas_som) = (vmax_s3_m1 * m1_pool(c,j) / &
+                                       (km_s3_m1 + m1_pool(c,j))) * &
+                                      w_d_o_scalars
+            decomp_k(c,j,i_pas_som) = (vmax_s3_m2 * m2_pool(c,j) / &
+                                       (km_s3_m2 + m2_pool(c,j))) * &
+                                      w_d_o_scalars
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:993]: these two should be i_avl_som
and *_s1_m*
all references to ACT_SOM should be AVL_SOM which is S1

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 25]
```diff
@@ -0,0 +1,1024 @@
...
+
+            decomp_k(c,j,i_act_som) = k_s1_s3 * w_d_o_scalars
+            decomp_k(c,j,i_slo_som) = k_s2_s3 * w_d_o_scalars
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:996]: s1_s3 --> s3_s1
s2_s3 --> s2_s1
both of these should be controlled by microbial biomass:
the flux in the testbed is "oxidat":
[OXIDAT = (mimicspool%MICk(npt) * mimicsbiome%Vmax(npt,K2) * mimicspool%SOMc(npt)    &
                    / (mimicsbiome%KO(2)*mimicsbiome%Km(npt,K2) + mimicspool%SOMc(npt)))      &
                    + (mimicspool%MICr(npt) * mimicsbiome%Vmax(npt,R2) * mimicspool%SOMc(npt) &
                    / (mimicsbiome%KO(1)*mimicsbiome%Km(npt,R2) + mimicspool%SOMc(npt)))](https://github.com/wwieder/biogeochem_testbed_1.1/blob/52d460fd39720c3f7dc7b47265f20f4c6149796d/SOURCE_CODE/mimics_cycle_CN.f90#L897)

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 23 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:979]: confirm whether decomp_k is used in a transitions loop or a pool loop. We need transitions loop.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 25 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:996]: oxidat shows two components going from s2 to s1, the sum of which is decomp_k.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 24 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:993]: again sum the two for decom_k of i_avl_som

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 26]
```diff
@@ -0,0 +1,1024 @@
...
+                                      fphys(c) * w_d_o_scalars
+            decomp_k(c,j,i_cop_mic) = tau_m1_s2 * m1_pool(c,j)**(densdep) * &
+                                      fchem(c) * w_d_o_scalars
+            decomp_k(c,j,i_cop_mic) = tau_m1_s3 * m1_pool(c,j)**(densdep) * &
+                                      faval(c) *w_d_o_scalars
+            decomp_k(c,j,i_oli_mic) = tau_m2_s1 * m2_pool(c,j)**(densdep) * &
+                                      fphys(c) * w_d_o_scalars
+            decomp_k(c,j,i_oli_mic) = tau_m2_s2 * m2_pool(c,j)**(densdep) * &
+                                      fchem(c) * w_d_o_scalars
+            decomp_k(c,j,i_oli_mic) = tau_m2_s3 * m2_pool(c,j)**(densdep) * &
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:1008]: in this case sum the three to get decomp_k for i_cop_mic
similarly for i_oli_mic

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 27]
```diff
@@ -0,0 +1,1024 @@
...
+      pathfrac_decomp_cascade(bounds%begc:bounds%endc,1:nlevdecomp,i_l2m2)= 1.0_r8
+
+      i_s3m2 = 6
+      decomp_cascade_con%cascade_step_name(i_s3m2) = 'S3M2'
+      rf_decomp_cascade(bounds%begc:bounds%endc,1:nlevdecomp,i_s3m2) = rf_s3m2
+      cascade_donor_pool(i_s3m2) = i_pas_som
+      cascade_receiver_pool(i_s3m2) = i_oli_mic
+      pathfrac_decomp_cascade(bounds%begc:bounds%endc,1:nlevdecomp,i_s3m2) = 1.0_r8
+
+      ! TODO If keeping s1_s3 & s2_s3 code, is pathfrac correct or should = 1?
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:562]: should be 1

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 28]
```diff
@@ -0,0 +1,1024 @@
...
+         tau_m1_s3 = tau_r1 * exp(tau_r2 * fmet) * tauMod
+         tau_m2_s1 = tau_k1 * exp(tau_k2 * fmet) * tauMod
+         tau_m2_s2 = tau_k1 * exp(tau_k2 * fmet) * tauMod
+         tau_m2_s3 = tau_k1 * exp(tau_k2 * fmet) * tauMod
+
+         do j = 1,nlevdecomp
+            ! vmax are time-dependent terms
+            ! Table B1 Wieder et al. (2015) & MIMICS params file give different
+            ! kslope. I used the params file value(s).
+            ! TODO Introduce t_soi24_degC_col following t_veg24_patch (running
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:948]: make it the instantaneous soil temp

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 29]
```diff
@@ -0,0 +1,1024 @@
...
+               ligninNratio(c,froot) * (croot2met(c) + croot2str(c)) + &
+               ligninNratio(c,wood) * (cwd2str(c))) / &
+              max(0.001, cleaf2met(c) + cleaf2str(c) + &
+                         croot2met(c) + croot2str(c) + cwd2str(c))
+
+         ! Set limits on Lignin:N to keep fmet > 0.2
+         ! Necessary for litter quality in boreal forests with high cwd flux
+         fmet = fmet_p1 * (fmet_p2 - fmet_p3 * min(40.0_r8, &
+                                                   ligninNratioAvg(c)))
+         ! TODO USE cnveg_carbonflux_inst%annsum_npp_col (gC/m2/yr) updated 1/yr
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:928]: use this one

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 30]
```diff
@@ -0,0 +1,1024 @@
...
+         ! Time-dependent params from Wieder et al. 2015 & testbed code
+         ! TODO STILL MISSING N-related stuff: DIN...
+
+         ! TODO I don't see existing ligninNratioAvg, so calculate
+           ligninNratioAvg(c) =  &
+              (ligninNratio(c,leaf) * (cleaf2met(c) + cleaf2str(c)) + &
+               ligninNratio(c,froot) * (croot2met(c) + croot2str(c)) + &
+               ligninNratio(c,wood) * (cwd2str(c))) / &
+              max(0.001, cleaf2met(c) + cleaf2str(c) + &
+                         croot2met(c) + croot2str(c) + cwd2str(c))
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:922]: cleaf2met is leaf carbon to metabolic litter
similarly the others

rethink this as the sum of input to metabolic + str litter? @wwieder will look at this.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 31]
```diff
@@ -0,0 +1,1024 @@
...
+            km_s3_m1 = exp(kslope_s3_m1 * t_soi24_degC_col(c,j) + kint_s3_m1) * kmod_s3_m1 / p_scalar(c,j)
+            km_s3_m2 = exp(kslope_s3_m2 * t_soi24_degC_col(c,j) + kint_s3_m2) * kmod_s3_m2 / p_scalar(c,j)
+
+            ! Product of w_scalar * depth_scalar * o_scalar
+            w_d_o_scalars = w_scalar(c,j) * depth_scalar(c,j) * o_scalar(c,j)
+
+            ! decomp_k used in SoilBiogeochemPotentialMod.F90
+            ! TODO Defined correctly here?
+            ! TODO Combine multiple terms of same donor pools...
+            ! TODO Where to calculate m1_pool and m2_pool?
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:971]: m1 and m2 pools should be handled by existing loops elsewhere...

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 32]
```diff
@@ -0,0 +1,1024 @@
...
+               if (j==1) w_scalar(c,:) = 0._r8
+               psi = min(soilpsi(c,j),maxpsi)
+               ! decomp only if soilpsi is higher than minpsi
+               if (psi > minpsi) then
+                  w_scalar(c,1) = w_scalar(c,1) + (log(minpsi/psi)/log(minpsi/maxpsi))*fr(c,j)
+               end if
+            end do
+         end do
+
+         ! TODO @wwieder concerned about breaking ch4 code
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:813]: we may need a hook from mimics to ch4 code for it to work

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 33]
```diff
@@ -0,0 +1,1024 @@
...
+            decomp_k(c,j,i_oli_mic) = tau_m2_s2 * m2_pool(c,j)**(densdep) * &
+                                      fchem(c) * w_d_o_scalars
+            decomp_k(c,j,i_oli_mic) = tau_m2_s3 * m2_pool(c,j)**(densdep) * &
+                                      faval(c) * w_d_o_scalars
+            ! Same for cwd but only if fates not enabled; fates handles cwd on
+            ! its own structure
+            ! TODO Kept cwd bc we do not have a MIMICS replacement for it.
+            !      Also this shows what the BGC decomp_k formulas looked like.
+            if (.not. use_fates) then
+               decomp_k(c,j,i_cwd) = k_frag * w_d_o_scalars * spinup_geogterm_cwd(c)
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:1015]: should go from cwd to str litter
should be same as bgc where it goes to cel & lig

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 34]
```diff
@@ -0,0 +1,1024 @@
...
+                                       (km_s3_m1 + m1_pool(c,j))) * &
+                                      w_d_o_scalars
+            decomp_k(c,j,i_pas_som) = (vmax_s3_m2 * m2_pool(c,j) / &
+                                       (km_s3_m2 + m2_pool(c,j))) * &
+                                      w_d_o_scalars
+
+            decomp_k(c,j,i_act_som) = k_s1_s3 * w_d_o_scalars
+            decomp_k(c,j,i_slo_som) = k_s2_s3 * w_d_o_scalars
+
+            decomp_k(c,j,i_cop_mic) = tau_m1_s1 * m1_pool(c,j)**(densdep) * &
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:998]: densdep = 1 for now
m1_pool should be replaced with carbon density in soil layer, so divided by layer thickness.

Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:998]: pool gC/m2
two conversions to get to...
conc mgC/cm3

decomp_k will end up in units of per hour and we need per second.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 35]
```diff
@@ -0,0 +1,1024 @@
...
+      ! some of these are dependent on the soil texture properties
+      ! TODO rf_s1s3 -> rf_decomp_cascade as template for p_scalar?
+      !      One-time initializations here.
+      !      Time-dep params in subr. decomp_rates_mimics.
+
+      do c = bounds%begc, bounds%endc
+         do j = 1, nlevdecomp
+            t = 0.85_r8 - 0.68_r8 * 0.01_r8 * (100._r8 - cellsand(c,j))
+            f_s1s3(c,j) = .004_r8 / (1._r8 - t)
+            rf_s1s3(c,j) = t
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:347]: s3_s1 this rf should be zero

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 36]
```diff
@@ -0,0 +1,1024 @@
...
+      rf_s3m1 = 1.0_r8 - params_inst%mge(3)
+      rf_l1m2 = 1.0_r8 - params_inst%mge(4)
+      rf_l2m2 = 1.0_r8 - params_inst%mge(5)
+      rf_s3m2 = 1.0_r8 - params_inst%mge(6)
+
+      rf_s2s3 = params_inst%rf_s2s3_bgc
+      rf_cwdl2 = params_inst%rf_cwdl2_bgc
+
+      ! set the structural fraction for coarse woody debris
+      ! TODO Renamed LHS to cwd_fstr. Make RHS = sum or avg of the two?
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:291]: set to 1

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 37]
```diff
@@ -0,0 +1,1024 @@
...
+         floating_cn_ratio_decomp_pools(i_cwd) = .true.
+         decomp_cascade_con%decomp_pool_name_restart(i_cwd) = 'cwd'
+         decomp_cascade_con%decomp_pool_name_history(i_cwd) = 'CWD'
+         decomp_cascade_con%decomp_pool_name_long(i_cwd) = 'coarse woody debris'
+         decomp_cascade_con%decomp_pool_name_short(i_cwd) = 'CWD'
+         is_microbe(i_cwd) = .false.
+         is_litter(i_cwd) = .false.
+         is_soil(i_cwd) = .false.
+         is_cwd(i_cwd) = .true.
+         initial_cn_ratio(i_cwd) = 10._r8  ! 90 in BGC; not used in MIMICS
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:490]: all initial_cn_ratio terms need to be 1
all rf_decomp_cascade need to be 0
for the decomp_k loop to work in soilbiogeochem/SoilBiogeochemPotentialMod.F90
but does it break anything else and is this how we want to resolve this...?

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 32 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:813]: Added this comment to the code to be addressed later.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 25 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:996]: Initially I misunderstood from comment 1 above that both s2_s1 and s3_s1 were controlled by OXIDAT. From comment 2 and the testbed code I now realize that we were likely talking about s2_s1 only. And the decomp_k term for s3_s1 just equals desorption from what I can tell.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 38]
```diff
@@ -925,92 +926,77 @@ subroutine decomp_rates_mimics(bounds, num_soilc, filter_soilc, &
...
+! Controlled by microbial biomass through OXIDAT (line 1145 in testbed)
+! TODO OXIDAT = MICk * Vmax(K2) * SOMc / (KO(2) * Km(K2) + MICk) + &
+!               MICr * Vmax(R2) * SOMc / (KO(1) * Km(R2) + MICr)
+            decomp_k(c,j,i_slo_som) = TODO * w_d_o_scalars
+
+            decomp_k(c,j,i_cop_mic) = tau_m1 * m1_conc(c,j)**(densdep) * &
                                       w_d_o_scalars
-            decomp_k(c,j,i_pas_som) = (vmax_s3_m2 * m2_pool(c,j) / &
-                                       (km_s3_m2 + m2_pool(c,j))) * &
+            decomp_k(c,j,i_oli_mic) = tau_m2 * m2_conc(c,j)**(densdep) * &
```
Comment (wwieder) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:995]: Does `m*_conc` come in here, or is the donor pool multiplied by microbial turnover when all the decomp_k values are used elsewhere?

Comment (wwieder) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:995]: If we do leave `m1_conc` out here, I'm not sure how we'd be able to handle `densdep` here, which may be OK since we're setting it to 1 (at least for starters).

**Review by wwieder — COMMENTED** [review]
let me know if comment here warrant a quick conversation for clarification.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 39]
```diff
@@ -271,80 +253,65 @@ subroutine init_decompcascade_mimics(bounds, soilbiogeochem_state_inst, soilstat
...
-      !      One-time initializations here.
+      ! TODO One-time initializations here.
       !      Time-dep params in subr. decomp_rates_mimics.
 
       do c = bounds%begc, bounds%endc
          do j = 1, nlevdecomp
-            t = 0.85_r8 - 0.68_r8 * 0.01_r8 * (100._r8 - cellsand(c,j))
-            f_s1s3(c,j) = .004_r8 / (1._r8 - t)
-            rf_s1s3(c,j) = t
             p_scalar(c,j) = (0.8_r8 * exp(-3.0_r8 * sqrt(cellclay(c,j))))** &
```
[the remark this answers is not in the document]
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:315]: Also I will rewrite this as
`1 / (...)` instead of 
`(...)**(-1)`
Let me know you're opposed.

[the remark this answers is not in the document]
Comment (wwieder) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:315]: sounds good

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 40]
```diff
@@ -624,27 +630,21 @@ subroutine decomp_rates_mimics(bounds, num_soilc, filter_soilc, &
...
-    real(r8):: km_s3_m2  !
-    real(r8):: tau_m1_s1  !
-    real(r8):: tau_m1_s2  !
-    real(r8):: tau_m1_s3  !
-    real(r8):: tau_m2_s1  !
-    real(r8):: tau_m2_s2  !
-    real(r8):: tau_m2_s3  !
+    real(r8):: km_s1_m2  !
+    real(r8):: tau_m1  !
+    real(r8):: tau_m2  !
```
[the remark this answers is not in the document]
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:647]: From what I see in the testbed code, we use
Vmax(K2), Vmax(R2), Km(K2), Km(R2) which correspond to
vmax_l2_m1, vmax_l2_m2, km_l2_m1, km_l2_m2
The only new thing I see in oxidat is the KO parameter that I will add now.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 41]
```diff
@@ -925,92 +926,77 @@ subroutine decomp_rates_mimics(bounds, num_soilc, filter_soilc, &
...
+            ! TODO Excluded spinup terms for now (except see cwd below)
+            ! TODO Calc m*_conc = m*_pool(c,j) / dz(j) layer thickness
+            !           mgC/cm3 = gC/m3 * (1e3 mg/g) / (1e6 cm3/m3)
+            ! TODO decomp_k will end up in units of per hour and we
+            !      need per s so apply conversion to the coeffs above
+            decomp_k(c,j,i_met_lit) = (vmax_l1_m1 * m1_conc(c,j) / &
+                                       (km_l1_m1 + m1_conc(c,j)) + &
+                                       vmax_l1_m2 * m2_conc(c,j) / &
+                                       (km_l1_m2 + m2_conc(c,j))) * &
                                       w_d_o_scalars
```
[the remark this answers is not in the document]
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:972]: I'm not sure I follow...
Currently we set pathfrac = 1 for all transitions EXCEPT for
`m1s1, m1s2, m1s3`
`m2s1, m2s2, m2s3`
where we use
`fphys, fchem, faval`

As I think about it, we may need to change pathfrac for the others to avoid double-counting. So in your example
pathfrac(l1m1) = (vmax_l1_m1 * m1_conc(c,j) / (km_l1_m1 + m1_conc(c,j))) / (vmax_l1_m2 * m2_conc(c,j) / (km_l1_m2 + m2_conc(c,j)))
pathfrac(l1m2) = 1 - pathfrac(l1m1)
because doesn't this determine how much of the donor will go to each receiver? If we need to do this, we'll see how complicated it ends up being...

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 30 above)
Comment (wwieder) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:923]: What's the best way to do this for a column? 

We should be able to get lignin:N for each patch with data in `pftconMod.F90`:
- `lflitcn`, `frootcn` for litter CN as well as (are these used in CLM5?)
-  `lf_flig`, `fr_flig` for lignin (are these used for all pfts)?

We'd also likely need to keep track of the fluxes (`leafc_to_litter_patch`, `frootc__to_litter_patch`, `m_deadstemc_to_litter` from `CNVegCarbonFluxType.F90`) + associated N fluxes.  
Then all of these would have to be appropriately weighted from patches to columns.  Is there an easier way to go?

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 38 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:995]: I see what you mean. I was thrown off by the fact that we multiply all the others by `m*_conc` but the others are litter and soil, not microbes.

If we are keeping `densdep` as a placeholder, then I think the right answer is
```suggestion
            decomp_k(c,j,i_oli_mic) = tau_m2 * m2_conc(c,j)**(densdep - 1.0_r8) * &
```

Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:995]: ...to explain:
The minus 1 in `(densdep - 1)` just means that we are dividing the right hand side by m*_conc to account for the fact that later in the code `decomp_k` will get multiplied by `m*_conc`.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 41 above)
[the remark this answers is not in the document]
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:1009]: I came up with a way to address this. I will commit and push changes by the end of the day.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 42]
```diff
@@ -103,31 +100,16 @@ subroutine readParams ( ncid )
 
     ! Read off of netcdf file
     ! TODO Add new params here and in the params file.
-    ! TODO tau_s1, tau_s2, etc may need _bgc added/removed here/params file
+    ! TODO Some may need _bgc added/removed here and in the params file
     ! TODO Read MIMICS-specific params here & shared ones (eg *_bgc) as:
     !      decomp_depth_efolding = CNParamsShareInst%decomp_depth_efolding
     ! TODO When ready for all final params values, talk to @wwieder and,
     !      if values differ from the BGC values, make separate _mimics params.
```
[the remark this answers is not in the document]
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:108]: I added a TODO about this in the code.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 37 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:468]: I looked again at the decomp_k loop in `SoilBiogeochemPotentialMod.F90`, and I think it's fine as is.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 30 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:950]: Here's what I'm coming up with:

`lflitcn` is used in `CNPhenologyMod`

`frootcn` is used in `CNPhenologyMod`, `CNVegNitrogenStateType`, `NutrientCompetitionFlexibleCNMod`

`lf_flig` and `fr_flig` get assigned values for all pfts, though may not be used for all pfts

In `CNVegCarbonFluxType` I see that the relevant subroutine is `Summary_carbonflux` where we would use `call p2c` to get the variables to the column-level.

I see the following variable mappings:
`cleaf2met(c) + cleaf2str(c)`  -->  `leafc_to_litter_patch` after call p2c
`croot2met(c) + croot2str(c)`  -->  `frootc_to_litter_patch` after call p2c
`cwd2str(c)`  -->  `m_deadstemc_to_litter_patch` after call p2c
`ligninNratio(leaf)`  -->  `lf_flig * lflitcn`   is this how you would do this & the next one?
`ligninNratio(froot)`  -->  `fr_flig * frootcn`
`ligninNratio(wood)`  -->  `cwd_flig * cwdc_col(c) / cwdn_col(c)`

Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90]: I committed and pushed my first draft of this calculation.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 42 above)
[the remark this answers is not in the document]
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:115]: @wwieder 
Question regarding your comment: Would we use the existing `decomp_depth_efolding` (used in line 920) or would we replace?

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 43]
```diff
@@ -0,0 +1,1107 @@
...
+         ! - Or should we even calculate them only for pfts that are present?
+         ! If so, we could do that just before call p2c and then call p2c only
+         ! once for the column-level ligninNratioAvg
+         ligninNratioAvg = ((sum(lf_flig(1:)) / size(lf_flig(1:))) * &
+                            (sum(lflitcn(1:) / size(lflitcn(1:)))) * &
+                            leafc_to_litter(c) + &
+           (sum(fr_flig(1:)) / size(fr_flig(1:))) * &
+           (sum(frootcn(1:)) / size(frootcn(1:))) * &
+           frootc_to_litter(c) + &
+           cwd_flig * (cwdc_col(c) / cwdn_col(c)) * m_deadstem_to_litter(c)) / &
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:976]: Prefer the `cwdc / cwdn` ratio or `deadwdcn` here? Maybe we expect their values to be the same?

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 44]
```diff
@@ -0,0 +1,1107 @@
...
+      end if
+
+      ! Term that reduces decomposition rate at depth
+      do j = 1, nlevdecomp
+         do fc = 1, num_soilc
+            c = filter_soilc(fc)
+            if (use_vertsoilc) then
+               ! Using fixed e-folding depth as in
+               ! SoilBiogeochemDecompCascadeBGCMod.F90
+               depth_scalar(c,j) = exp(-zsoi(j) / decomp_depth_efolding)
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:920]: depth_scalar(c,j) = 1
and comm. out the exp function

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 45]
```diff
@@ -0,0 +1,1107 @@
...
+            pathfrac_decomp_cascade(c,j,i_l2m1) = term_1 / (term_1 + term_2)
+            pathfrac_decomp_cascade(c,j,i_l2m2) = term_2 / (term_1 + term_2)
+
+            term_1 = vmax_s1_m1 * m1_conc / (km_s1_m1 + m1_conc)
+            term_2 = vmax_s1_m2 * m2_conc / (km_s1_m2 + m2_conc)
+            decomp_k(c,j,i_avl_som) = (term_1 + term_2) * w_d_o_scalars
+            pathfrac_decomp_cascade(c,j,i_s1m1) = term_1 / (term_1 + term_2)
+            pathfrac_decomp_cascade(c,j,i_s1m2) = term_2 / (term_1 + term_2)
+
+            decomp_k(c,j,i_phys_som) = desorption * w_d_o_scalars
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:1075]: replace w_d_o with depth_scalar

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 46]
```diff
@@ -0,0 +1,1107 @@
...
+      tauMod_min = 0.8_r8
+      tauMod_max = 1.2_r8
+      tau_r_p1 = 5.2e-4_r8
+      tau_r_p2 = 0.3_r8  ! or 0.4?
+      tau_k_p1 = 2.4e-4_r8
+      tau_k_p2 = 0.1_r8
+      ko_r = 4.0_r8
+      ko_k = 4.0_r8
+      densdep = 1.0_r8
+      desorpQ10 = 1.1_r8
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:946]: change to 1

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 43 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:976]: Do the ligninNratioAvg calculation at the p level and then call p2c for ligninNratioAvg.

Once this code is running, check for high-freq variations in ligninNratioAvg. We may want to replace the pool_to_litter terms with some long term mean.

Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:976]: > Prefer the `cwdc / cwdn` ratio or `deadwdcn` here? Maybe we expect their values to be the same?

Prefer the ratio rather than the parameter.

Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:976]: `m_deadstemc_to_litter` represents the input to cwd and should be replaced by the output from cwd

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 47]
```diff
@@ -0,0 +1,1107 @@
...
+      ! set respiration fractions for fluxes between compartments
+      rf_l1m1 = 1.0_r8 - params_inst%mge(1)
+      rf_l2m1 = 1.0_r8 - params_inst%mge(2)
+      rf_s1m1 = 1.0_r8 - params_inst%mge(3)
+      rf_l1m2 = 1.0_r8 - params_inst%mge(4)
+      rf_l2m2 = 1.0_r8 - params_inst%mge(5)
+      rf_s1m2 = 1.0_r8 - params_inst%mge(6)
+
+      rf_m1s1 =  ! TODO Set or calculate these here OR
+      rf_m1s2 =  !      are all six of them zero?
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:280]: all six are 0

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 48]
```diff
@@ -0,0 +1,1107 @@
...
+    character(len=100) :: errCode = 'Error reading MIMICS params '
+    logical            :: readv   ! has variable been read in or not
+    real(r8)           :: tempr   ! temporary to read in constant
+    character(len=100) :: tString ! temp. var for reading
+    !-----------------------------------------------------------------------
+
+    ! Read off of netcdf file
+    ! TODO Add new params here and in the params file.
+    ! TODO Some may need _bgc added/removed here and in the params file
+    ! TODO Read MIMICS-specific params here & shared ones (eg *_bgc) as:
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:112]: may be nicer to put mimics_ as prefix rather than suffix to gather all the params together in the params file

get approval from Bill/Erik

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 49]
```diff
@@ -0,0 +1,1107 @@
...
+      desorpQ10 = 1.1_r8
+      t_soi_ref = 25.0_r8  ! deg C
+
+      ! calculate rates for all litter and som pools
+      ! TODO Ok that I reversed order of do-loops?
+      do fc = 1,num_soilc
+         c = filter_soilc(fc)
+
+         ! Time-dependent params from Wieder et al. 2015 & testbed code
+         ! TODO STILL MISSING N-related stuff: DIN...
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:955]: start looking in NitrogenCompetitionMod:
we will need hooks to the ctsm no3 and nh4 terms
the fluxes are nmin (nh4)

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 48 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:112]: moved comment to the code

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 47 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:280]: so just removing them

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 40 above)
[the remark this answers is not in the document]
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:673]: went over this in today's meeting

File: src/biogeochem/CNVegCarbonFluxType.F90 [hunk 50]
```diff
@@ -4396,6 +4396,18 @@ subroutine Summary_carbonflux(this, &
             this%hrv_gresp_storage_to_litter_patch(p)      + &
             this%hrv_gresp_xfer_to_litter_patch(p)
 
+       if (use_mimics_decomp) then
+          ! Calculate ligninNratio for leaves and fine roots
```
Comment (slevisconsulting) [inline src/biogeochem/CNVegCarbonFluxType.F90:4400]: > Do the ligninNratioAvg calculation at the p level and then call p2c for ligninNratioAvg.

@wwieder I have now realized (or possibly remembered) that cwd variables are tracked at the column level only. So I'm calculating ligninNratio(leaf) and (root) at the p level and the rest at the column level a few lines down.

File: src/biogeochem/CNVegCarbonFluxType.F90 [hunk 51]
```diff
@@ -4440,6 +4467,22 @@ subroutine Summary_carbonflux(this, &
          this%gpp_patch(bounds%begp:bounds%endp), &
          this%gpp_col(bounds%begc:bounds%endc))
 
+    if (use_mimics_decomp) then
+       ! Calculate ligninNratioAve
+       ! TODO define new var cwdc_to_litter as the flux from cwdl2 transition
```
Comment (slevisconsulting) [inline src/biogeochem/CNVegCarbonFluxType.F90:4472]: I haven't come across anywhere, yet, the variable that represents the flux from the cwdl2 transition. I made a placeholder with cwdc_to_litter(c) for now.

Comment (slevisconsulting) [reply src/biogeochem/CNVegCarbonFluxType.F90:4470]: I think I found this now (see next commit).

File: src/biogeochem/CNVegCarbonFluxType.F90 (hunk 50 above)
Comment (wwieder) [reply src/biogeochem/CNVegCarbonFluxType.F90:4400]: this makes sense, thanks for clarifying @slevisconsulting

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 30 above)
Comment (DavidBergeron-eng) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90]: Thanks for all contributing

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 43 above)
Comment (DavidBergeron-eng) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90]: You folks have me lost at the intro I need visual projection to see blueprint to evaluate. Thanks I'm still in grade school on this coding field but learning each day more and more.🌎🤗

**Review by DavidBergeron-eng — APPROVED** [review]

**Comment by DavidBergeron-eng** [comment]
Underground is off limits what are your reasons

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 52]
```diff
@@ -0,0 +1,1090 @@
...
+    logical            :: readv   ! has variable been read in or not
+    real(r8)           :: tempr   ! temporary to read in constant
+    character(len=100) :: tString ! temp. var for reading
+    !-----------------------------------------------------------------------
+
+    ! Read off of netcdf file
+    ! TODO Add new params here and in the params file.
+    ! TODO Some may need _bgc or _mimics added/removed here and in the params
+    !      file. Nicer to add as prefix instead of as suffix because params will
+    !      then appear grouped in the file. Need approval from Bill/Erik.
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:111]: Question for @ekluzek 
The above TODO talks about adding `bgc` or `mimics` as a **prefix** or as a **suffix** to parameter names that we want to assign to one model or the other.
@wwieder prefers the **prefix** idea because params will then appear grouped in the file. Before I go ahead and implement this, do you object by any chance?

Comment (ekluzek) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90]: Mostly I suggest to go with Will's suggestion as he's going to be working with these variables, and that's a good note about the prefix as far as grouping the variables. There are two caveat's I have to do that though. The first is wondering about our current use of prefixes vs suffixes and if we have any conventions there. The second is that if you do this for MIMICS_ you should likely do the same for SOILBGC_ for the same reason.

In terms of prefixes and suffixes in the history variables. We do have a convention for a prefix that gives the species type (C13_ or C14_ for carbon isotopes, and also CH4_ and O_ for Methane, O3 for Ozone, H2O in some cases for water). In terms of model packages we do have _FUN suffixes for a few variables. A leading T is usually used in TemperatureType for temperatures. SNO for snow variables, SOIL for something to do with soil. Then there's pool types done as prefixes: ACT_, CEL_, DWT_, F for radiation fluxes, Q for water fluxes of various types, CONC_ for some concentrations. There's not a strong enough convention to blindly follow it, so doing something different could be OK here.

Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90]: Thanks @wwieder and @ekluzek . I will work on that.

Here's how I understand what I'm doing. **Pls correct anything that I have misunderstood:**
- In the params file(s) I will add prefixes `mimics_*` or `bgc_*` to model-specific parameters.
- In the code I will read model-specific parameters in the corresponding module `*MIMICSMod` or `*BGCMod`.
- In the params file(s) I will remove such prefixes (or suffixes as the case may be) from parameters that are used by both DecompCascade models.
- In the code I will read parameters that are used by both models in `CNSharedParamsMod`.
- **This one is a clarification question:** In the code, once parameters have been read from the params file(s), do we still want the parameter names to include the prefixes to maintain clarity about where they came from, or is it sufficient that they have prefixes in the params file(s)? I ask because I found myself leaning in favor of removing the prefixes in the parameter names once we're using them in the code. But maybe that's wrong...

Comment (billsacks) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90]: Interesting question on whether to remove the prefix in the code. I don't have strong feelings on this, but I have heard from a few people that they prefer if names don't change from one place to another, to make it easier to grep for things in the code. It seems like this is a situation where that would apply: It's a bit easier to find uses of a parameter if the same name is used in the code as in the param file (otherwise you need to first figure out that it has changed name, then grep for the name that is actually used in the code).

That said, I also see the rationale for removing the prefixes to keep the code more concise and easier to read.

Here's a possible compromise solution that comes to mind: We use a separator other than `_` to separate the prefix from the main variable name in the params file. We choose a separator that is reserved for this purpose of "namespacing" the variables in the params file, and isn't used in any other way in parameter names (maybe `-` or `.`, if they are allowed in NetCDF variable names, or something else). Then we can strip that prefix in the variable name in the code. This would let us have a consistent rule like, "everything before the dot in the param file name is just for namespacing purposes, so to find the variable in the code, just grep for the name after the dot".

Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90]: Thank you for this suggestion, @billsacks .  I opted for the more immediately straightfwd solution of keeping the prefixes.

File: doc/ChangeLog [hunk 53]
```diff
@@ -1,4 +1,81 @@
 ===============================================================
+Tag name:  ctsm5.1.dev053
```
Comment (slevisconsulting) [inline doc/ChangeLog:2]: ChangeLog and ChangeSum show up here at this time because I merged the `hist_vars_for_newton_krylov` branch to this branch. They will disappear from here when the `hist_vars_for_newton_krylov` branch gets merged to master.

**Comment by slevisconsulting** [comment]
For now I'm using this test:
`ERP_P36x2_D_Ld3.f10_f10_mg37.I1850Clm50BgcCrop.cheyenne_gnu.clm-extra_outputs`
Once this runs (and agrees with baseline as expected), I will create a test for MIMICS. At that point I expect to enter another debugging phase.

**Comment by slevisconsulting** [comment]
@ekluzek and I agreed that, for now, I will not rename non-mimics parameters to avoid conflicts with his changes to the params files.

**Comment by wwieder** [comment]
agreed, good catch on this, @slevisconsulting, let's take it out of the name list.  For MIMICS, you're also right, I'm hoping this is obsolete, but if we do use any similar logic I'm imagining it will be a mimics specific parameterization like `mimics_decomp_depth_efolding`

**Comment by slevisconsulting** [comment]
> I would create an issue for that so that we can track it seperately.

I created issue #1473 for the problem discussed above with `decomp_depth_efolding`.
For now, I have made the code changes here because it was easy to do.
@ekluzek do you prefer that I open a separate PR for these changes, because it will allow the changes to get merged to master sooner?

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 54]
```diff
@@ -0,0 +1,1274 @@
...
+               if (j==1) w_scalar(c,:) = 0._r8
+               psi = min(soilpsi(c,j),maxpsi)
+               ! decomp only if soilpsi is higher than minpsi
+               if (psi > minpsi) then
+                  w_scalar(c,1) = w_scalar(c,1) + (log(minpsi/psi)/log(minpsi/maxpsi))*fr(c,j)
+               end if
+            end do
+         end do
+
+         ! TODO May need a hook from MIMICS to ch4 code for this to work
```
Comment (slevisconsulting) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:998]: @wwieder 
I'm trying to diagnose a `CH4 Conservation Error in CH4Mod during diffusion` when I run with MIMICS.
For now I'm writing out key variables and comparing to a case without MIMICS.
Remembering though that you made the comment that I wrote in line 998, maybe you have some intuition about where to look for the problem?

Comment (wwieder) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:998]: hmm, I'm not really sure what's happening in this code block, but wonder if there is information that's being passed to `CH4Mod` with BGC that needs to be included for MIMICS (e.g.,  https://github.com/slevisconsulting/ctsm/blob/3ff27f32c0d9d5fcfda497f92d2eab0df3403c85/src/biogeochem/ch4Mod.F90#L2344). 

Would it be helpful to discuss next week?

Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:998]: It wouldn't hurt and meanwhile I will go back to investigating on Monday morning. This far I have traced the problem to very large values of `source` in `ch4Mod.F90` in my MIMICS case (not so in the default case).

Best days for me next week are Monday, Tuesday, and Friday. Feel free to send me an invite.

**Comment by slevisconsulting** [comment]
I have tracked down a source of the N-bal error. I will test and push code in the next day or two if all goes well. Disclaimer: There's always a chance that there are more errors to be uncovered :-)

File: doc/ChangeLog (hunk 53 above)
Comment (slevisconsulting) [reply doc/ChangeLog]: Not true since I removed my mods to ChangeLog and ChangeSum when I merged with dev061 today.

**Comment by slevisconsulting** [comment]
Cheyenne test-suite OK
but
Izumi test-suite
- Two tests give roundoff diffs from baseline:
`SMS_D.f10_f10_mg37.I2000Clm51BgcCrop.izumi_pgi.clm-crop`
`SMS.f10_f10_mg37.I2000Clm50BgcCrop.izumi_pgi.clm-crop`
- One test gives bigger diffs relative to baseline:
`SMS_D_Vnuopc_Mmpi-serial.CLM_USRDAT.I1PtClm51Bgc.izumi_nag.clm-default--clm-NEON-NIWO.C.1102-115448iz_nag`

@ekluzek this last one doesn't appear in the EXPECTED FAILURES. In TestStatus.log I see messages like this:
`wget failed with output:  and errput --2021-11-04 18:13:06--  ftp://ftp.cgd.ucar.edu/cesm/inputdata/atm/cdeps/v1/NIWO/NIWO_atm_2018-01.nc
[...] No such directory`
and
`svn export failed with output:  and errput svn: E170000: URL 'https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/atm/cdeps/v1/NIWO/NIWO_atm_2018-01.nc' doesn't exist`
for 2018, 2019, 2020, and 2021 files, but files with these names do appear in the tests's inputdata, so this is probably not the problem.

Do you know of problems with this test?

**Comment by ekluzek** [comment]
@slevisconsulting those are normal kind of messages for that NEON test. The NEON cases copy inputdata into the $RUNDIR when they are created, so you always get a bunch of messages like that. But, usually although it has those warnings it's actually successful in the end. So as long as the case worked and ran as expected you are fine. What does the TestStatus file show?

**Comment by slevisconsulting** [comment]
> What does the TestStatus file show?

Shows diffs greater than roundoff from the baseline. A couple of things seem strange to me:
- it's the only test from the two test-suites that gave diffs greater than roundoff
- I see diffs in this file:
`SMS_D_Vnuopc_Mmpi-serial.CLM_USRDAT.I1PtClm51Bgc.izumi_nag.clm-default--clm-NEON-NIWO.C.1104-175601iz_nag.cpl.hi.2018-01-06-00000.nc.cprnc.out`
in variables that I think are not affected by the land model (eg atmImp_Sa_tbot)

**Comment by slevisconsulting** [comment]
1) @wwieder 
I think it's time for a meeting where together we go over remaining TODOs in the code and check them off.

2) @wwieder @ekluzek 
There are at least a couple of changes I made in this PR that ideally I would have made outside this PR (as we did with some refactors early on). Should I go back and do them as separate PRs? For example:
- my changes in SoilBiogeochemDecompCascadeBGCMod.F90
https://github.com/ESCOMP/CTSM/pull/1318/files#diff-e66d718ed1b06ae10ceda3248c8f5c2e860e423897ddbd26339e67d4af81e513
- my changes that fix #1473 (from what I can tell people decided that it's ok not to open a separate PR for this)

I expect both to be bfb changes. The cheyenne test-suite confirms this. The izumi test-suite has two tests with roundoff diffs and one with bigger diffs. The bigger diffs show up in variables that I'm pretty sure MIMICS doesn't affect, eg TBOT and QBOT. So I'm interested in guidance on that test `SMS_D_Vnuopc_Mmpi-serial.CLM_USRDAT.I1PtClm51Bgc.izumi_nag.clm-default--clm-NEON-NIWO`

3) @wwieder @ekluzek 
How should we handle the code review? Should we have others look over this PR?

4) @wwieder @ekluzek 
Testing status:
- See what I wrote above about an izumi test with diffs greater than roundoff.
- I added MIMICS tests to the cheyenne and izumi test-suites. While trying out prospective tests on cheyenne, I found that `ERP_D_P36x2_Ld3.f10_f10_mg37.I2000Clm51BgcCrop.cheyenne_**gnu**.clm-mimics` PASSes, while `ERP_D_P36x2_Ld3.f10_f10_mg37.I2000Clm51BgcCrop.cheyenne_**intel**.clm-mimics` FAILs. I documented the error in the last commit.

**Comment by wwieder** [comment]
@slevisconsulting this is great news!  I'll set up a time when we can meet, but it may not be until later in the week.  
At some point we need to scientifically evaluate the implementation of this code.  When does this typically occur?  

I'll defer to @ekluzek on how to handle the BFB changes you mentioned.

**Comment by slevisconsulting** [comment]
> At some point we need to scientifically evaluate the implementation of this code. When does this typically occur?

Let's discuss scientific evaluation after we look over the remaining TODOs in the code on Thurs.

**Comment by slevisconsulting** [comment]
From conversations in today's "stand-up":
- @ekluzek said that there was no need to open new PR(s) for the bfb changes because this PR is bfb anyway.
- @billsacks suggested that I rerun the nag test giving bigger diffs than roundoff, but for baseline (IN PROGRESS).
- @ekluzek I think you expected the failing tests to be pgi. The two tests giving roundoff diffs _**are**_ pgi.

File: bld/listDefaultNamelist.pl [hunk 55]
```diff
@@ -270,11 +270,17 @@ sub GetListofNeededFiles {
 
            my @bgcsettings   = $definition->get_valid_values( "bgc_mode", 'noquotes'=>1 );
```
Comment (ekluzek) [inline bld/listDefaultNamelist.pl:271]: I'm not sure if this is a useful script anymore. We should talk about getting rid of it.

File: cime_config/testdefs/testlist_clm.xml [hunk 56]
```diff
@@ -538,6 +538,24 @@
       <option name="wallclock">00:20:00</option>
     </options>
   </test>
+  <test name="ERP_D_P36x2_Ld3" grid="f10_f10_mg37" compset="I1850Clm51BgcCrop" testmods="clm/mimics">
```
Comment (ekluzek) [inline cime_config/testdefs/testlist_clm.xml:541]: One thing to think about here is the length of the simulation. Since, MIMICS is going to take a long time to spinup we should likely do at least one test that runs for a few years. Or we should startup from a state where MIMICS was spunup.

File: cime_config/testdefs/testmods_dirs/clm/mimics/include_user_mods [hunk 57]
```diff
@@ -0,0 +1 @@
+../coldStart
```
Comment (ekluzek) [inline cime_config/testdefs/testmods_dirs/clm/mimics/include_user_mods:1]: Since this is inheriting the coldStart the name of the testmod should include that in the name. So mimicsColdStart or at least mimicsCold. At some point we should have a mimics option that doesn't do a cold-start and provides a spunup initial condition file to use.

File: cime_config/testdefs/testlist_clm.xml [hunk 58]
```diff
@@ -538,6 +538,24 @@
...
+  </test>
+  <test name="SMS_Ld5_Mmpi-serial" grid="1x1_brazil" compset="IHistClm50BgcQianRs" testmods="clm/mimics">
+    <machines>
+      <machine name="izumi" compiler="gnu" category="aux_clm"/>
+    </machines>
+    <options>
+      <option name="wallclock">00:20:00</option>
+      <option name="comment"  >Test soil_decomp_method = 'MIMICSWieder2015'</option>
+    </options>
+  </test>
```
Comment (ekluzek) [inline cime_config/testdefs/testlist_clm.xml:558]: You need to add a test for the new newton_krylov testmod.

File: src/biogeochem/CNDriverMod.F90 [hunk 59]
```diff
@@ -314,6 +317,14 @@ subroutine CNDriverNoLeaching(bounds,
     if (decomp_method == century_decomp) then
        call decomp_rate_constants_bgc(bounds, num_soilc, filter_soilc, &
             soilstate_inst, temperature_inst, ch4_inst, soilbiogeochem_carbonflux_inst)
+    else if (decomp_method == mimics_decomp) then
+       call decomp_rates_mimics(bounds, num_soilc, filter_soilc, &
+            soilstate_inst, temperature_inst, cnveg_carbonflux_inst, ch4_inst, &
+            soilbiogeochem_carbonflux_inst, soilbiogeochem_carbonstate_inst)
+    else
```
Comment (ekluzek) [inline src/biogeochem/CNDriverMod.F90:324]: This should already have been checked at initialization, so you don't really need to do this check here. And I'd suggest it should be an abort rather than a warning. Also no_soil_decomp is a valid option so it really shouldn't have an else...

File: src/biogeochem/EDBGCDynMod.F90 [hunk 60]
```diff
@@ -180,6 +182,14 @@ subroutine EDBGCDyn(bounds,                                                    &
     if (decomp_method == century_decomp) then
        call decomp_rate_constants_bgc(bounds, num_soilc, filter_soilc, &
             soilstate_inst, temperature_inst, ch4_inst, soilbiogeochem_carbonflux_inst)
+    else if (decomp_method == mimics_decomp) then
+       call decomp_rates_mimics(bounds, num_soilc, filter_soilc, &
+            soilstate_inst, temperature_inst, cnveg_carbonflux_inst, ch4_inst, &
+            soilbiogeochem_carbonflux_inst, soilbiogeochem_carbonstate_inst)
+    else
```
Comment (ekluzek) [inline src/biogeochem/EDBGCDynMod.F90:189]: As above, remove the else with the warning. This should just be done at initialization.

File: src/main/clm_instMod.F90 [hunk 61]
```diff
@@ -383,6 +385,13 @@ subroutine clm_instInit(bounds)
        if (decomp_method == century_decomp ) then
           call init_decompcascade_bgc(bounds, soilbiogeochem_state_inst, &
                                       soilstate_inst )
+       else if (decomp_method == mimics_decomp ) then
+          call init_decompcascade_mimics(bounds, soilbiogeochem_state_inst, &
+                                         soilstate_inst)
+       else
+          write(iulog,*) 'WARNING:'
```
Comment (ekluzek) [inline src/main/clm_instMod.F90:392]: I'd actually remove the else and warning here, as it's already done in decomp_cascase_par_init.

File: src/main/readParamsMod.F90 [hunk 62]
```diff
@@ -98,7 +100,15 @@ subroutine readParameters (nutrient_competition_method, photosyns_inst)
     !
     if (use_cn .or. use_fates) then
        call readSoilBiogeochemCompetitionParams(ncid)
-       call readSoilBiogeochemDecompBgcParams(ncid)
+       if (decomp_method == mimics_decomp) then
+          call readSoilBiogeochemDecompMimicsParams(ncid)
+       else if (decomp_method == century_decomp) then
+          call readSoilBiogeochemDecompBgcParams(ncid)
+       else
+          write(iulog,*) 'WARNING:'
```
Comment (ekluzek) [inline src/main/readParamsMod.F90:108]: Remove the else and warning.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 63]
```diff
@@ -0,0 +1,1274 @@
...
+  private
+  !
+  ! !PUBLIC MEMBER FUNCTIONS:
+  public :: readParams                      ! Read in parameters from params file
+  public :: init_decompcascade_mimics       ! Initialization
+  public :: decomp_rates_mimics             ! Figure out decomposition rates
+  !
+  ! !PUBLIC DATA MEMBERS 
+  !
+  ! !PRIVATE DATA MEMBERS
```
Comment (ekluzek) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:44]: I think more of the variables should have a description for them. Some of them have a structure with numbers to indicate levels and pools and such, so you just need to describe how the structure of the name works.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 64]
```diff
@@ -0,0 +1,1274 @@
...
+
+      ! translate to per-second time constant
+      k_frag = 1._r8 / (secspday * days_per_year * CNParamsShareInst%tau_cwd)
+
+     ! calc ref rate
+      if ( spinup_state >= 1 ) then
+         do fc = 1,num_soilc
+            c = filter_soilc(fc)
+            !
+            if ( abs(spinup_factor(i_met_lit) - 1._r8) .gt. .000001_r8) then
```
Comment (ekluzek) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:894]: Make 0.000001_r8 a parameter.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 65]
```diff
@@ -0,0 +1,1274 @@
...
+               spinup_geogterm_l1(c) = spinup_factor(i_met_lit) * get_spinup_latitude_term(grc%latdeg(col%gridcell(c)))
+            else
+               spinup_geogterm_l1(c) = 1._r8
```
Comment (ekluzek) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:897]: You could make 1._r8 a parameter "one" because it's used so much. That's not at all critical though since numbers important to make parameters are more complex ones that are likely to change. "one" isn't likely to change, and as such it might be more clear to use 1._r8 rather than "one". But, just throwing that out there for you to think about.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 66]
```diff
@@ -0,0 +1,1274 @@
...
+         do fc = 1, num_soilc
+            c = filter_soilc(fc)
+            ! Using fixed e-folding depth as in
+            ! SoilBiogeochemDecompCascadeBGCMod.F90
+!           depth_scalar(c,j) = exp(-zsoi(j) / decomp_depth_efolding)
+            depth_scalar(c,j) = 1.0_r8
+         end do
+      end do
+
+      mimics_fmet_p1 = params_inst%mimics_fmet(1)
```
Comment (ekluzek) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:1080]: This makes me wonder if some of these shouldn't be arrays?

**Review by ekluzek — CHANGES_REQUESTED** [review]
This is really great to see and I'm excited to see MIMICS come in as an option. I made some requests for changes. Some are just points to think about, others should definitely happen. I'm happy to go over this if it helps.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 65 above)
Comment (billsacks) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:897]: I feel like the important consideration here is: If you change one of these, do others need to be changed as well? If so, you should extract a parameter for each group that should be kept the same. If these are all truly supposed to just be the value 1 and would never change from that, then I feel that using a hard-coded 1 is more clear and I don't see any downsides of it myself. (Maybe it's just me, but when I see use of a parameter like `zero` or `one` in code, I am never satisfied with assuming that it is actually exactly 0 or 1, but instead feel I need to check to confirm that it's really exactly 0 or 1, and not something close to 0, like 0.000001 – so this just slows me down in reading & understanding code.)

Comment (ekluzek) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:897]: I like how @billsacks expressed it. If it's truly just what you would see as 1 in a math equation leave it as it is. If it's something that could need to change as a group so become 1.00000001 or something then express it as a constant. It's true I've seen code where I feel I have to check if one or zero is actually just 1.0_r8 and 0.0_r8. So thanks for articulating that clearly @billsacks.

File: src/main/clm_varpar.F90 [hunk 67]
```diff
@@ -71,7 +71,11 @@ module clm_varpar
   integer, public :: i_litr_min = -9  ! min index of litter pools; overwritten in SoilBiogeochemDecompCascade*Mod
   integer, public :: i_litr_max = -9  ! max index of litter pools; overwritten in SoilBiogeochemDecompCascade*Mod
   integer, public :: i_met_lit = -9  ! index of metabolic litter pool; overwritten in SoilBiogeochemDecompCascade*Mod
+  integer, public :: i_cop_mic = -9  ! index of copiotrophic microbial pool; overwritten in SoilBiogeochemDecompCascade*Mod
+  integer, public :: i_oli_mic = -9  ! index of oligotrophic microbial pool; overwritten in SoilBiogeochemDecompCascade*Mod
   integer, public :: i_cwd      = -9  ! index of cwd pool; overwritten in SoilBiogeochemDecompCascade*Mod
+  ! TODO Not necessary but cleaner to use this copy of i_cwdl2 in *CascadeBGC?
+  integer, public :: i_cwdl2 = -9  ! index of cwd to l2 transition; overwritten in SoilBiogeochemDecompCascade*Mod
```
Comment (slevisconsulting) [inline src/main/clm_varpar.F90:78]: Do it.

File: bld/listDefaultNamelist.pl (hunk 55 above)
Comment (slevisconsulting) [reply bld/listDefaultNamelist.pl:271]: Ok, let me know.

File: cime_config/testdefs/testlist_clm.xml (hunk 56 above)
Comment (slevisconsulting) [reply cime_config/testdefs/testlist_clm.xml:541]: Agreed. For now the /mimics mods directory uses a cold start, but let's plan on switching to spun-up initial conditions when we have an acceptable finidat file.

File: cime_config/testdefs/testmods_dirs/clm/mimics/include_user_mods (hunk 57 above)
Comment (slevisconsulting) [reply cime_config/testdefs/testmods_dirs/clm/mimics/include_user_mods:1]: I think it makes sense to switch to spun-up initial conditions when we have an acceptable finidat file, so I will leave the mods directory name unchanged if that's ok. I will include a comment to that effect in the README.

File: cime_config/testdefs/testlist_clm.xml (hunk 58 above)
Comment (slevisconsulting) [reply cime_config/testdefs/testlist_clm.xml:558]: @ekluzek do you mean a test for what's in this directory:
`cime_config/usermods_dirs/newton_krylov_spinup`?
...otherwise, I haven't created a newton_krylov testmod. Should I? I think I should wait for @wwieder and Keith Lindsay to make progress because I don't know if the N-K solution will work for sure. What do you think @wwieder ?

File: src/biogeochem/CNDriverMod.F90 (hunk 59 above)
Comment (slevisconsulting) [reply src/biogeochem/CNDriverMod.F90:324]: Removed `else`

File: src/biogeochem/EDBGCDynMod.F90 (hunk 60 above)
Comment (slevisconsulting) [reply src/biogeochem/EDBGCDynMod.F90:189]: Removed `else`

File: src/main/clm_instMod.F90 (hunk 61 above)
Comment (slevisconsulting) [reply src/main/clm_instMod.F90:392]: Removed `else`

File: src/main/readParamsMod.F90 (hunk 62 above)
Comment (slevisconsulting) [reply src/main/readParamsMod.F90:108]: Removed `else`

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 63 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:44]: I added comments. Possibly more could be added still.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 64 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:894]: Defining as parameter eps = 1e-6

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 65 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:897]: That helps, thanks. I will keep them as "1" to indicate that they should be addressed independent of each other if at some point they must change.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 66 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:1080]: If we prefer them as arrays, would you approve using the params_inst versions of them, which are already declared as arrays?

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 64 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:894]: ...here and in SoilBiogeochemDecompCascadeBGCMod.F90

File: cime_config/testdefs/testlist_clm.xml (hunk 58 above)
Comment (wwieder) [reply cime_config/testdefs/testlist_clm.xml:558]: I'm optimistic that the N-K will work, but it's vapor ware right now.

File: bld/listDefaultNamelist.pl (hunk 55 above)
Comment (slevisconsulting) [reply bld/listDefaultNamelist.pl]: Meanwhile I also realized that my mods in this script were unnecessary, so I have now reverted them.

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 [hunk 68]
```diff
@@ -0,0 +1,1279 @@
...
+      ! Time-dep params in subr. decomp_rates_mimics.
+
+      do c = bounds%begc, bounds%endc
+         do j = 1, nlevdecomp
+            ! The parameter values currently in the params files always lead to
+            ! positive values for the expressions below, so we do not
+            ! need to use the max function to limit these expressions.
+            ! We apply the min function on cellclay because we are looping over
+            ! some non-soil columns here that contain cellclay = 1e36.
+            clay = dmin1(100.0_r8, cellclay(c,j))
```
Comment (wwieder) [inline src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:464]: @slevisconsulting I need to double check with other MIMICS code, but I think the assumption here is that clay for these equations is a fraction, not a percent.  Assuming this is true, we can add a line where clay =clay /100, but should check it's not being used elsewhere in the code.

Comment (wwieder) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:464]: Yes, this needs to be a fraction (range 0-1), not a percent (range 0-100).   Maybe we should call it `clay_frac` to clarify?

With a quick look, I think this the only place where clay is being used in the MIMICS code.  If this is true, @slevisconsulting can you make this change and test this change for in the 1x1 brazil case?

Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:464]: Sounds good. Do you prefer a clean start using cold-start or a restart with existing pools?

Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:464]: For now started as cold-start to keep the comparison clean.

**Comment by wwieder** [comment]
I think it needs to be clean, as it will really change the size of the SOMp pool with important downstream effects on other C stocks.

**Comment by slevisconsulting** [comment]
I posted a few comments about the latest run in #1451

**Comment by slevisconsulting** [comment]
@ekluzek 
I didn't want to delay this morning's meeting beyond 10 am, but I wonder whether we should add this PR to the upcoming tags.
@wwieder 
you and I talked about that briefly a week or two ago and thought that it was a good idea. Do you still think so?
@ekluzek 
what do you think?

**Comment by wwieder** [comment]
There's still scientific testing that needs to be done here, but initial results look promising.  I'd be supportive of merging this to main while we keep making relatively small improvements.

**Comment by wwieder** [comment]
I also don't know what's preferred here on the SE side when a large new tag is coming in.

**Comment by slevisconsulting** [comment]
@wwieder I confirmed with @ekluzek at the last stand-up that it makes sense to merge this PR sooner rather than later.
- I started updating the ChangeLog in the most recent commit. Pls take a look and let me know how much detail you would like to see there.
- @ekluzek told me that he would like to review the code once more before approving it.
- I will rerun the test-suites once we're closer to merging.

This coming week I will not spend much time on the computer, but I'm available for short meetings if needed.

**Comment by wwieder** [comment]
thanks for the heads up, @slevisconsulting enjoy the time off.  @ekluzek it seems like there are lots of upcoming tags to coordinate?  This is maybe a bit further down the list because it still requires your review, but we can sort this out at an upcoming SE meeing.

**Comment by slevisconsulting** [comment]
I added timing calls and performed tests.
**New timing calls:**  DecompRate, CNvegCflux_summary, SoilBiogeochemPotential
**Existing timing calls:** soilbiogeochemcompetition, SoilBiogeochemDecomp

**Test PFS_Ly1_Mmpi-serial.1x1_brazil.IHistClm50BgcQianRs.cheyenne_gnu.clm-mimics**
mimics 185.90 simulated_years/day vs default 183.17
Region                             PETs  Count Mean (s)   Min (s) Min PET Max (s)     Max PET
soilbiogeochemcompetition 1 17521  5.37/5.09  same  0   same  0
SoilBiogeochemPotential     1 17521   1.80/1.31  same  0   same  0
DecompRate                         1 17521   1.44/1.00  same  0   same  0
SoilBiogeochemDecomp      1 17521   0.98/0.67  same  0   same  0
CNvegCflux_summary          1 17521   1.36/1.18  same   0  same  0

**Test PFS_Ly1.f10_f10_mg37.I2000Clm51BgcCrop.cheyenne_gnu.clm-mimics**
mimics 140.92 simulated_years/day vs default 131.55
DecompRate                        72 17521  4.62/1.86  1.29/0.73  42        8.40/2.91    3/10
SoilBiogeochemPotential     72 17521  4.61/2.44  1.94/1.12  42/59  6.82/3.79   10/13
soilbiogeochemcompetition 72 17521 8.98/8.00  3.65/3.29  42     13.21/12.37  13/3
SoilBiogeochemDecomp      72 17521 2.62/1.72   0.79/0.56  42       4.00/2.71    10
CNvegCflux_summary          72 17521 1.14/1.00   0.71/0.61   42       1.63/1.43    10/3

@ekluzek I would be interested in your feedback regarding these results.

**Comment by slevisconsulting** [comment]
Regarding my previous post, recall that we expect some increase in computational expense due to the following:

```
if ( use_fates ) then
          if (decomp_method == century_decomp) then
             ndecomp_pools = 6
             ndecomp_cascade_transitions = 8
          else if (decomp_method == mimics_decomp) then
             ndecomp_pools = 7
             ndecomp_cascade_transitions = 14
          end if
else
          if (decomp_method == century_decomp) then
             ndecomp_pools = 7
             ndecomp_cascade_transitions = 10
          else if (decomp_method == mimics_decomp) then
             ndecomp_pools = 8
             ndecomp_cascade_transitions = 15
```

**Comment by wwieder** [comment]
@slevisconsulting at our SE meeting we discussed merging this to the trunk to avoid having to maintaining this branch for a long time.  Can you work with @ekluzek on when we can schedule this merge?  How does this work with the other TODOs you're working on.

**Comment by wwieder** [comment]
@slevisconsulting you can go next on this PR if you're available. Otherwise @negin513 has another PR that's nearly ready to go

**Comment by slevisconsulting** [comment]
@wwieder thanks! I will start the test-suites and will report when they complete.

**Comment by slevisconsulting** [comment]
@ekluzek the code uses four new param files in `/glade/p/cesmdata/cseg/inputdata/lnd/clm2/paramdata` and in `/fs/cgd/csm/inputdata/lnd/clm2/paramdata`. I assume I need to `rimport` them to the repository, but I wanted to confirm with you first.

**Comment by slevisconsulting** [comment]
> @wwieder thanks! I will start the test-suites and will report when they complete.

**izumi** OK except one test fails
`SMS_Vmct.f10_f10_mg37.I2000Clm50BgcCrop.izumi_pgi.clm-crop`
and this is due to diffs from baseline (dev073). 
`cprnc.out` shows diffs only in one variable:
`RMS TOTECOSYSC  1.9853E-12            NORMALIZED  6.5087E-17`
@ekluzek are you comfortable with this result, or do you propose I try to explain this difference?

**cheyenne** PASS
Two tests failed the first time around and passed on second attempt.

I will update the ChangeLog with these test results and push. Then, I think this PR is ready unless the izumi_pgi test needs investigation. Also, pending my question above about [rimporting the new param files](https://github.com/ESCOMP/CTSM/pull/1318#issuecomment-1023711360).

File: bld/listDefaultNamelist.pl (hunk 55 above)
Comment (slevisconsulting) [reply bld/listDefaultNamelist.pl]: Referenced this conversation in a new issue to ensure it didn't get lost.

File: cime_config/testdefs/testlist_clm.xml (hunk 58 above)
Comment (slevisconsulting) [reply cime_config/testdefs/testlist_clm.xml:542]: I linked #1457 to this conversation to avoid forgetting...

File: cime_config/testdefs/testmods_dirs/clm/mimics/include_user_mods (hunk 57 above)
Comment (slevisconsulting) [reply cime_config/testdefs/testmods_dirs/clm/mimics/include_user_mods:1]: The comment that I added to this testmod's README:

```
As of 2021/11/15 this test inherits mods from the ../coldStart directory;
however the plan is to change that to ../default when we have an acceptable
spun up finidat file to initialize MIMICS with.
```

File: cime_config/testdefs/testlist_clm.xml (hunk 56 above)
Comment (slevisconsulting) [reply cime_config/testdefs/testlist_clm.xml:525]: See another conversation in this PR discussing [spun up initial conditions](https://github.com/ESCOMP/CTSM/pull/1318/files/4eb33728bda7eb9bfe142d6fae20601370fba0fa#r747797589)

File: src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90 (hunk 66 above)
Comment (slevisconsulting) [reply src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90:1077]: I added a TODO directly in the code with Erik's suggestion to prevent forgetting it.

**Comment by ekluzek** [comment]
The PGI test seems to only be roundoff. And as it's only difference in answers for one test (and it's PGI which seems to be more sensitive) I think it's reasonable to take this as being fine.

SMS_Vmct.f10_f10_mg37.I2000Clm50BgcCrop.izumi_pgi.clm-crop

**Comment by ekluzek** [comment]
Yes go ahead and rimport the files. I usually do this first, before running on izumi, so that the files will automatically appear their when you test.

**Review by ekluzek — CHANGES_REQUESTED** [review]
OK, so there are two changes I'm asking for. But, I am very excited to see this in the code! To have another decomposition option to run MIMICS!

You won't need to redo testing that's done. Just do the one new test that you add.

**Comment by slevisconsulting** [comment]
New test completed successfully and new baseline created:
`./create_test SMS_Ly5_Mmpi-serial.1x1_brazil.IHistClm50BgcQianRs.cheyenne_intel.clm-newton_krylov_spinup -g /glade/p/cgd/tss/ctsm_baselines/ctsm5.1.dev074`

@ekluzek I updated the ChangeLog to mention this.

**Review by ekluzek — APPROVED** [review]

**Comment by wwieder** [comment]
Thanks Sam and Erik!
