### PR TITLE
Dust emissions control moved to cmeps

### LINKED ISSUE #2150: Add capability to flip between different dust emission parameterizations?
I introduce this idea here:

https://github.com/ESCOMP/CTSM/issues/1604#issuecomment-1712923802

I think it would be worthwhile to add the capability to flip between different dust emission parameterizations, for the reasons stated above. This would be done after #1836 is complete. And before #1897 comes in.

This would be done similarly as other OO options we have for code options is done. So a Factory that reads in a namelist to determine which one, and instantiate it. And then an abstract base class, and then specific versions based off the base class.
This doesn't actually add that much code. The abstract class and factory for Fire for example is only about 400 lines. With most of that being boilerplate. So I think adding this would not be a big development.

### LINKED ISSUE #2170: Update the drv_flds namelist definition file in CTSM to work with latest CAM/cmeps
### Brief summary of bug

I see this as a problem in trying SMS.f09_g17.2000_CAM%DEV_CLM51%SP_SICE_SOCN_MOSART_SGLC_SWAV.cheyenne_intel.clm-default
with ctsm5.1.dev125 (technically a ctsm5.2 branch of it, but shouldn't be relevant here).

### General bug information

**CTSM version you are using:** ctsm5.1.dev125-384-gaa3c5cc8a

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** Some configurations with CAM

### Details of bug

I'm not really sure why this isn't a problem all of the time. As cases with CAM obviously work. So why is this an issue in this case?

### Important output or errors that show the problem

This is the error I see when running preview_namelists for the above test. It does fail at this point and doesn't populate CaseDocs with namelists...

```
Create namelist for component drv
   Calling /glade/work/erik/ctsm_worktrees/ctsm5.2.mksurfdata/components/cmeps/cime_config/buildnml
Writing nuopc_runconfig for components ['CPL', 'ATM', 'LND', 'ROF']
ERROR: Variable 'atm_provides_lightning' from file '/glade/work/erik/ctsm_worktrees/ctsm5.2.mksurfdata/cime/scripts/SMS.f09_g17.2000_CAM%DEV_CLM51%SP_SICE_SOCN_MOSART_SGLC_SWAV.cheyenne_intel.clm-default.C.20230925_160609_ag813w/Buildconf/camconf/drv_flds_in' is not in the namelist definition.
```

### LINKED ISSUE #2376: Update CTSM with CMEPS update for controlling Dust emissions
This updates CTSM to use the namelist control in CMEPS (in https://github.com/ESCOMP/CMEPS/pull/429). So the CMEPS external needs to be updated, and the namelist control in CTSM changed to use CMEPS rather than the internal CTSM control settings and the CTSM ones removed.

### LINKED ISSUE #2524: Add option to NOT set the dust-emission drv_flds_in settings when coupled to CAM
As part of the work on dust emissions, we need a way to choose if either CAM or CTSM is going to set the CMEPS dust_emission namelist. The current logic for this is that if CAM and CTSM disagree on the fields in drv_fld_in -- CESM aborts with an error. This happens inside of CMEPS buildnml.

In the case of fire-emissions, MEGAN, or drydep these are all optional so we just don't set them when coupled to CAM. So there is no disagreement with CAM. In this case though dust_emissions -- must be set. So when coupled to CAM, CTSM needs to know not to set it, which means default values should NOT be set for this case.

### LINKED ISSUE #2666: 1x1_cidadinhoBR tests fail in build-namelist_test.pl
### Brief summary of bug

1x1_cidadinhoBR tests fail in `build-namelist_test.pl`.

### General bug information

**CTSM version you are using:** ctsm5.2.016

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** n/a

### Details of bug

Fine; that resolution isn't used by anything yet.

### Important output or errors that show the problem

```
862/3314 < FAIL> <Test Id: 862> <Desc: -bgc bgc -crop -res 1x1_cidadinhoBR -use_case 1850_control -envxml_dir . clm4_5-bgc: lnd_in file exists>
1273/3314 < FAIL> <Test Id: 1273> <Desc: -bgc bgc -crop -res 1x1_cidadinhoBR -use_case 1850_control -envxml_dir . clm5_0-bgc: lnd_in file exists>
1684/3314 < FAIL> <Test Id: 1684> <Desc: -bgc bgc -crop -res 1x1_cidadinhoBR -use_case 1850_control -envxml_dir . clm5_1-bgc: lnd_in file exists>
2095/3314 < FAIL> <Test Id: 2095> <Desc: -bgc bgc -crop -res 1x1_cidadinhoBR -use_case 1850_control -envxml_dir . clm6_0-bgc: lnd_in file exists>
```

### PR DESCRIPTION
**Pull request by ekluzek**
### Description of changes

Remove the dust emissions namelist items from CTSM and use the namelist in the drv_flds_in for CMEPS.

This updates CTSM to use the namelist control in CMEPS (in https://github.com/ESCOMP/CMEPS/pull/429). So the CMEPS external needs to be updated, and the namelist control in CTSM changed to use CMEPS rather than the internal CTSM control settings and the CTSM ones removed.

The new XML variable:

LND_SETS_DUST_EMIS_DRV_FLDS

controls whether dust emission settings are set by CTSM or by CAM. Only one or the other can set them, and it's required so when CAM and CTSM are running together they need to know which one will select.

Add a unit test for the CMEPS code to make sure it's working correctly.

Fix the cidinahoBR test in the build-namelist unit tester. 

- [x] unit test
- [x] Add drv_flds_in namelist definition in CMEPS
- [x] Finalize CMEPS tag point to it here
- [x] Update drv_flds_in namelist definition in CTSM
- [x] Add capability to set the dust emissions settings in drv_flds_in
- [x] Have build-namelist respond to LND_SETS_DUST_EMIS_DRV_FLDS
- [x] Update build-namelist tester to get the new capability working
- [x] Remove the old dust namelist items in CTSM
- [x] Use the new cmeps shared code for namelist in FORTRAN
- [x] Run standard testing and make sure everything is working

### Specific notes

Contributors other than yourself, if any:

CTSM Issues Fixed (include github issue #):
  Fixes #2376
  Fixes #2150
  Fixes #2524
  Fixes #2666

Are answers expected to change (and if so in what way)? No

Any User Interface Changes (namelist or namelist defaults changes)?
  Namelist items removed from CTSM and into the drv_flds_in namelist in CMEPS

Testing performed, if any: will run standard testing, have run a few singleton tests so far

### CODE REVIEW

**Comment by ekluzek** [comment]
This replaces #2538 which got closed when I messed up the rebase to b4b-dev for it. This is actually the same branch, but I force pushed the rebase after I correctly applied it. Since the other was already auto closed I had to open a new one, even though it's the same branch.

**Comment by ekluzek** [comment]
The CMEPS update is going to have to wait until after the cesm3_0_beta01 tag freeze for external updates.

**Comment by ekluzek** [comment]
This is on hold because of the cesm3_0_beta01 freeze going on. But, can go to b4b-dev.

**Comment by ekluzek** [comment]
I had some build problems using the updated CMEPS tag alone. But, replicating the ccs_config and CMEPS versions from #2590 I got the build to work.

File: bld/unit_testers/build-namelist_test.pl [hunk 1]
```diff
@@ -924,303 +839,270 @@ sub cat_and_create_namelistinfile {
...
+                                     },
+     "soil_erod_none_w_Zender"  =>{ options=>"--envxml_dir .",
+                                     namelst=>"dust_emis_method='Zender_2003', " .
+                                     "zender_soil_erod_source='none'",
+                                     GLC_TWO_WAY_COUPLING=>"FALSE",
+                                     phys=>"clm5_1",
+                                     },
+     "soil_erod_bad_w_Zender"   =>{ options=>"--envxml_dir .",
+                                     namelst=>"dust_emis_method='Zender_2003', " .
+                                     "zender_soil_erod_source='zztop'",
```
[the remark this answers is not in the document]
Comment (slevis-lmwg) [reply bld/unit_testers/build-namelist_test.pl:1105]: Also, is it ok that most (all?) dust-related namelst lines have a comma "," right after the method and end with a period "."? Looks inconsistent to me relative to other examples.

**Review by slevis-lmwg — COMMENTED** [review]
Thank you @ekluzek 

Other than one concern that you will find in my review, nothing else jumped out at me. For me to understand a few things better, I would not mind a quick (30-minute?) meeting to go over this PR together if that's ok with you.

File: bld/unit_testers/build-namelist_test.pl (hunk 1 above)
[the remark this answers is not in the document]
Comment (ekluzek) [reply bld/unit_testers/build-namelist_test.pl:1105]: You are right about the duplication. Thanks for pointing that out. I think I might have added it on the previous branch that came in as well as this one. So I'll remove the second duplicate one.

[the remark this answers is not in the document]
Comment (ekluzek) [reply bld/unit_testers/build-namelist_test.pl:1105]: Good question on the ending with the period. The syntax is correct, but as you point out it looks very arcane. The thing that's happening is that the "." concatenates two strings together. So the lines here...

``` perl
dust_emis_method='Zender_2003', " .
                                     "zender_soil_erod_source='none'",
```

Is really this...

``` perl
dust_emis_method='Zender_2003', zender_soil_erod_source='none'",
```

I did the concatenate to break up the long line. But, this might be a case that goes along with our recent discussion about long lines in code. With modern editors there isn't a reason to break lines up as much as in the past. The NAG compiler for FORTRAN code has a 132 character limit. So there's still reason to break up our FORTRAN code. And for readability I'd argue you should keep FORTRAN code shorter than that. But, perl and python don't have these limits. It's still an ingrained habit for me to shorten code lines, but this is a case where the concatenation makes the code unreaable. So I'll work with and removing that confusing use of concatenation syntax.

File: bld/CLMBuildNamelist.pm [hunk 2]
```diff
@@ -4708,7 +4723,7 @@ sub write_output_files {
   $log->verbose_message("Writing clm namelist to $outfile");
 
   # Drydep, fire-emission or MEGAN namelist for driver
-  @groups = qw(drydep_inparm megan_emis_nl fire_emis_nl carma_inparm);
+  @groups = qw(drydep_inparm megan_emis_nl fire_emis_nl carma_inparm dust_emis_inparm);
```
Comment (glemieux) [inline bld/CLMBuildNamelist.pm:4726]: I'm not very familiar with how `@groups` works, but I noticed that I couldn't find `dust_emis_inparm` (or `carma_inparm`) elsewhere in the CLMBuildNamelist.pm.  I'm assuming this is fine, but wanted to double check.

**Review by glemieux — APPROVED** [review]
Per our discussion I only reviewed the namelist defaults and CLMBuildNamelist.  I only had one question asking for a clarification.

File: bld/CLMBuildNamelist.pm [hunk 3]
```diff
@@ -3960,50 +3960,65 @@ sub setup_logic_fire_emis {
...
+  # Only set dust emission settings -- if not connected to CAM
+  my $lnd_sets_dust = logical_to_fortran($envxml_ref->{'LND_SETS_DUST_EMIS_DRV_FLDS'});
+  if ( &value_is_true( $lnd_sets_dust)) {
+
+      # First get the dust emission method
+      my $var = "dust_emis_method";
+      add_default($opts,  $nl_flags->{'inputdata_rootdir'}, $definition, $defaults, $nl, $var );
+      my $dust_emis_method = remove_leading_and_trailing_quotes( $nl->get_value($var) );
+
+      my @zender_files_in_lnd_opts = ( "stream_fldfilename_zendersoilerod", "stream_meshfile_zendersoilerod",
```
Comment (ekluzek) [inline bld/CLMBuildNamelist.pm:3975]: Make sure the logic is such that this isn't set if dust_emis_method != Zender_2003

File: src/biogeochem/DustEmisFactory.F90 [hunk 4]
```diff
@@ -28,30 +28,28 @@ function create_dust_emissions(bounds, NLFilename) result(dust_emis)
         !---------------------------------------------------------------------------
         use DustEmisBase      , only : dust_emis_base_type
         use DustEmisZender2003, only : dust_emis_zender2003_type
-        use clm_varctl        , only : dust_emis_method
         use decompMod         , only : bounds_type
         use shr_kind_mod      , only : CL => shr_kind_cl
+        use shr_dust_emis_mod , only : is_dust_emis_zender, is_dust_emis_leung
```
Comment (slevis-lmwg) [inline src/biogeochem/DustEmisFactory.F90:33]: I suggest a short justification explaining why this is preferable over using the generic dust_emis_method variable.

File: bld/unit_testers/build-namelist_test.pl [hunk 5]
```diff
@@ -924,303 +839,270 @@ sub cat_and_create_namelistinfile {
...
+                                     phys=>"clm5_1",
+                                     },
+     "Set_Dust_When_CAM_Sets"   =>{ options=>"--envxml_dir .",
+                                     namelst=>"dust_emis_method='Zender_2003'",
+                                     LND_SETS_DUST_EMIS_DRV_FLDS=>"FALSE",
+                                     phys=>"clm5_1",
+                                     },
+     "soil_erod_none_w_Zender"  =>{ options=>"--envxml_dir .",
+                                     namelst=>"dust_emis_method='Zender_2003', " .
+                                     "zender_soil_erod_source='none'",
```
Comment (ekluzek) [inline bld/unit_testers/build-namelist_test.pl:1099]:
```suggestion
                                     namelst=>"dust_emis_method='Zender_2003', zender_soil_erod_source='none'",
```

File: bld/CLMBuildNamelist.pm (hunk 2 above)
Comment (ekluzek) [reply bld/CLMBuildNamelist.pm:4726]: This is correct for the perl code. This just lists what namelists you want to write out and you only want to list each one once for the perl code. The namelist is referenced in the new namelist_definition file for dust_emis.

File: src/biogeochem/DustEmisFactory.F90 (hunk 4 above)
Comment (ekluzek) [reply src/biogeochem/DustEmisFactory.F90:33]: Yep will do.

Comment (ekluzek) [reply src/biogeochem/DustEmisFactory.F90:33]: Adding some notes here. The design doc for the CMEPS code is here:
[
](https://docs.google.com/document/d/18nZ3LJF5W-YF9iBhqed6s_NWeKOvSSL2-k0Lye1nnLg)

It uses a OOP design in order to make sure that it can't be messed up by either CAM or CTSM (since it's used by both). Using the function calls is a way of ensuring internal variables aren't able to be changed by either. There's a few other ways it could be done, but since it's used by both I thought it important to make sure neither could mess with the internal settings. That's also the reason to have a unit tester for it, so that both models can rely on the behavior for it.

File: bld/CLMBuildNamelist.pm (hunk 3 above)
Comment (ekluzek) [reply bld/CLMBuildNamelist.pm:3975]: I couldn't tell from the diff if the logic is done correctly, but looking at the code it looks fine. So resolving.

File: src/biogeochem/DustEmisFactory.F90 (hunk 4 above)
Comment (ekluzek) [reply src/biogeochem/DustEmisFactory.F90:43]: @slevis-lmwg I added a note in this regard at the function header. Let me know about any feedback.

File: src/biogeochem/DustEmisFactory.F90 [hunk 6]
```diff
@@ -25,33 +25,41 @@ function create_dust_emissions(bounds, NLFilename) result(dust_emis)
         !---------------------------------------------------------------------------
         ! Create a dust_emission base class objecct
         ! The method implemented depends on namelist input
+        !
+        ! DESIGN NOTES:   Erik Kluzek 07/15/2024
```
Comment (ekluzek) [inline src/biogeochem/DustEmisFactory.F90:29]: @adrifoster if you can I'd be interested in your feedback on this little design note section I added. Thanks...

File: bld/unit_testers/build-namelist_test.pl (hunk 1 above)
[the remark this answers is not in the document]
Comment (ekluzek) [reply bld/unit_testers/build-namelist_test.pl]: OK, handled both these comments.

File: src/biogeochem/DustEmisFactory.F90 (hunk 4 above)
Comment (slevis-lmwg) [reply src/biogeochem/DustEmisFactory.F90:43]: Looks good. Thank you for doing that @ekluzek

File: src/biogeochem/DustEmisFactory.F90 (hunk 6 above)
Comment (adrifoster) [reply src/biogeochem/DustEmisFactory.F90:29]: Good note. I like this strategy better (at least in this instance) since as you say we need both CAM and CTSM to know about the dust emission type. It's better to have it chosen as a function that we can control elsewhere. CTSM doesn't need to know anything about *how* we know which dust emission it is, we just need to know is it this? is it that?

Comment (ekluzek) [reply src/biogeochem/DustEmisFactory.F90:29]: Awesome. Thanks for looking at it.

Notes like this might be something appropriate to do in other places when we bring in new code and we want to talk about the design. I think it is better kept here in the code for this case than under the doc/design directory.

**Comment by ekluzek** [comment]
Testing on Izumi is as expected, with answers identical with the exception of changes in the field list. There are two new fields in the cpl files due to the cmeps update.

Similarily on Derecho 173 tests differ because of the field list. Most tests pass, but I am seeing the following fails right now (but could be because of Derecho problems):

ERI_D.ne30pg3_t232.I1850Clm60BgcCropG.derecho_intel.clm-clm60cam7LndTuningMode		
ERP_D_Ld5.f10_f10_mg37.I1850Clm50BgcCropG.derecho_gnu.clm-glcMEC_changeFlags		
ERP_D_Ld9.ne30pg3_t232.I1850Clm51BgcCropG.derecho_intel.clm-clm51cam6LndTuningMode		
ERP_D_Ld9.ne30pg3_t232.I1850Clm60BgcCropG.derecho_intel.clm-clm60cam7LndTuningMode		
ERP_D_Ld9.ne30pg3_t232.IHistClm60BgcCropG.derecho_intel.clm-clm60cam7LndTuningMode		
ERP_P256x2_D_Ld5.f19_g17_gris4.I1850Clm50BgcCropG.derecho_intel.clm-glcMEC_increase		
ERP_P64x2_D_Ld10.f10_f10_mg37.IHistClm50SpG.derecho_intel.clm-glcMEC_decrease		
ERS_D_Ld12.f10_f10_mg37.I1850Clm50BgcCropG.derecho_intel.clm-glcMEC_spunup_inc_dec_bgc		
ERS_D_Ld9.ne30pg3_t232.I1850Clm60BgcCropG.derecho_intel.clm-clm60cam7LndTuningMode		
ERS_Ly3_P64x2.f10_f10_mg37.IHistClm50BgcCropG.derecho_intel.clm-cropMonthOutput		
LILACSMOKE_D_Ld2.f10_f10_mg37.I2000Ctsm50NwpSpAsRs.derecho_intel.clm-lilac		
SMS_Lm1.ne30pg3_t232.I1850Clm60BgcCropG.derecho_intel.clm-clm60cam7LndTuningMode		
SMS_Lm37.f10_f10_mg37.I1850Clm50SpG.derecho_intel.clm-glcMEC_long

**Comment by ekluzek** [comment]
ALL of the above tests with CISM failed because CMEPS expects to receive runoff from CISM. So I needed to update CISM. I was afraid that would change answers, but from one short test it looks like it might be OK.

I also need to look into the LILAC test.

**Comment by ekluzek** [comment]
I figured out the fix for LILAC.

The CISM update is identical for the shorter tests, but the 3-year and 37 month test change answers. I could make it identical by having branches of submodules -- but that seems to be too much. So it seems the best way to go is to bring this to master, which should then be b4b since the submodule updates have already come in.

**Comment by ekluzek** [comment]
Testing on izumi is b4b with ctsm5.2.015 and as expected. On Derecho only the following are unexpected:

**Comment by ekluzek** [comment]
Looks like the FATES tests are due to this:

https://github.com/ESCOMP/CTSM/issues/2656

**Comment by ekluzek** [comment]
aux_clm testing is as expected on both Derecho and Izumi. The following tests show differences in answers because of the issues talked about above...

ERP_P64x2_Lm13.f10_f10_mg37.IHistClm60Bgc.derecho_intel.clm-monthly--clm-matrixcnOn_ignore_warnings
SMS.f10_f10_mg37.I2000Clm50BgcCrop.derecho_nvhpc.clm-crop
SMS_D.1x1_brazil.I2000Clm60FatesSpCruRsGs.derecho_gnu.clm-FatesColdDryDepSatPhen
SMS_D.1x1_brazil.I2000Clm60FatesSpCruRsGs.derecho_gnu.clm-FatesColdMeganSatPhen

The "nvhpc" test is because of a missing baseline for ctsm5.2.016.

**Comment by ekluzek** [comment]
About a week for sprint 8.
