### PR TITLE
Correct build errors in mksurfdata tools testers

### LINKED ISSUE #1575: Build problem for mksurfdata tools testers
### Brief summary of bug

[Give a one or two sentence summary. This could be the same as the issue title if you feel that is a sufficient summary.]

### General bug information

**CTSM version you are using:** ctsm5.1.dev066

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** Some of the mksurfdata unit testers
### Details of bug

Looks like some options in the tests aren't updated to use the new interfaces for certain subroutines that had an interface change.

@slevisconsulting I think this was your change you made in ctsm5.1.dev040. And is likely pretty straightforward to fix.

### Important details of your setup / configuration so we can reproduce the bug

This is on cheyenne with intel compiler going to the directory

tools/mksurfdata_map/unit_testers

and running

gmake

### Important output or errors that show the problem

Heres the build problem I see...

```
l/include -I/usr/local/lib   test_mkindexmapMod.F90
test_mkindexmapMod.F90(77): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [MASK_SRC]
      call get_dominant_indices(gridmap, src_array, dst_array, minval, maxval, nodata)
-----------^
test_mkindexmapMod.F90(86): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [MASK_SRC]
      call get_dominant_indices(gridmap, src_array, dst_array, minval, maxval, nodata)
-----------^
test_mkindexmapMod.F90(95): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [MASK_SRC]
      call get_dominant_indices(gridmap, src_array, dst_array, minval, maxval, nodata)
-----------^
test_mkindexmapMod.F90(104): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [MASK_SRC]
      call get_dominant_indices(gridmap, src_array, dst_array, minval, maxval, nodata)
-----------^
test_mkindexmapMod.F90(113): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [MASK_SRC]
      call get_dominant_indices(gridmap, src_array, dst_array, minval, maxval, nodata)
-----------^
test_mkindexmapMod.F90(122): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [MASK_SRC]
      call get_dominant_indices(gridmap, src_array, dst_array, minval, maxval, nodata)
-----------^
test_mkindexmapMod.F90(134): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [MASK_SRC]
      call get_dominant_indices(gridmap, src_array, dst_array, minval, maxval, nodata, filter=filter)
-----------^
test_mkindexmapMod.F90(146): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [MASK_SRC]
      call get_dominant_indices(gridmap, src_array, dst_array, minval, maxval, nodata, filter=filter)
-----------^
test_mkindexmapMod.F90(159): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [MASK_SRC]
      call get_dominant_indices(gridmap, src_array, dst_array, minval, maxval, nodata)
-----------^
test_mkindexmapMod.F90(194): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [MASK_SRC]
      call get_dominant_indices(gridmap, src_array, dst_array, minval, maxval, nodata)
-----------^
test_mkindexmapMod.F90(269): error #6632: Keyword arguments are invalid without an explicit interface.   [NODATA]
      call filter_same(gridmap, filter, src_array, dst_array, nodata=nodata)
--------------------------------------------------------------^
test_mkindexmapMod.F90(288): error #6632: Keyword arguments are invalid without an explicit interface.   [NODATA]
      call filter_same(gridmap, filter, src_array, dst_array, nodata=nodata)
--------------------------------------------------------------^
test_mkindexmapMod.F90(298): error #6632: Keyword arguments are invalid without an explicit interface.   [NODATA]
      call filter_same(gridmap, filter, src_array, dst_array, nodata=nodata)
--------------------------------------------------------------^
compilation aborted for test_mkindexmapMod.F90 (code 1)
../src/Makefile.common:348: recipe for target 'test_mkindexmapMod.o' failed
gmake: *** [test_mkindexmapMod.o] Error 1

```

### PR DESCRIPTION
**Pull request by slevisconsulting**
### Description of changes
I included notes with the first commit to this PR, that list the mods necessary to fix the build errors.

### Specific notes

Contributors other than yourself, if any:
@ekluzek 

CTSM Issues Fixed (include github issue #):
 Fixes #1575 

Are answers expected to change (and if so in what way)?
No

Any User Interface Changes (namelist or namelist defaults changes)?
No

Testing performed, if any:
In `/glade/work/slevis/git/mksurfdata_maps_wo_src_masks/tools/mksurfdata_map/unit_testers` I type `gmake` and get no errors now

### CODE REVIEW

**Comment by slevisconsulting** [comment]
@ekluzek this is ready for review.

File: tools/mksurfdata_map/unit_testers/test_mkindexmapMod.F90 [hunk 1]
```diff
@@ -200,111 +202,6 @@ subroutine test_get_dominant_indices
    end subroutine test_get_dominant_indices
 !------------------------------------------------------------------------------
 
-!------------------------------------------------------------------------------
```
Comment (ekluzek) [inline tools/mksurfdata_map/unit_testers/test_mkindexmapMod.F90:203]: @slevisconsulting thanks for working on this. The changes above are the ones that I expected. Below here you are deleting the general test "test_filter_same", which is the part I wondered about.  Shouldn't this test just be changed to use

File: tools/mksurfdata_map/unit_testers/test_mkgridmapMod.F90 [hunk 2]
```diff
@@ -334,193 +333,6 @@ subroutine test_gridmap_areaave_srcmask
 
   end subroutine test_gridmap_areaave_srcmask
 
-  !------------------------------------------------------------------------------
```
Comment (ekluzek) [inline tools/mksurfdata_map/unit_testers/test_mkgridmapMod.F90:337]: @slevisconsulting here you remove the test subroutine test_gridmap_areaave_srcmask2. However, I think these tests still apply, they just need to be reworked to use gridmap_areaave_srcmask rather than gridmap_areaave. I think after that the tests themselves should still work and pass as before. Is there a different reason you removed this test subroutine?

**Review by ekluzek — CHANGES_REQUESTED** [review]
@slevisconsulting thanks for getting this PR out quickly and fixing this. Most of this is straightforward and I of course approve. I did wonder about the removal of the test subroutine as you see below as it looked like to me the calls just need to be updated in it, but the functionality of the tests that are done still apply. But, let me know if you disagree.

**Comment by ekluzek** [comment]
@slevisconsulting we have decided that we need a ctsm5.2.mksurfdata branch to cover changes that are going into mksurfdata until ctsm5.2 tags are made. As such I think this PR would be best to go on that branch, so I'll rebase this to go to that branch. The requirements for things going to that branch will be a little relaxed from those going to CTSM main-dev.

File: tools/mksurfdata_map/unit_testers/test_mkgridmapMod.F90 (hunk 2 above)
Comment (slevisconsulting) [reply tools/mksurfdata_map/unit_testers/test_mkgridmapMod.F90:337]: @ekluzek
I agree that the tests would pass if I reworked the calls to use gridmap_areaave_srcmask; however, the test descriptions in `test_gridmap_areaave_srcmask` and `test_gridmap_areaave_srcmask2` are identical, which suggests that repeating the srcmask2 tests as srcmask would be redundant. Pls let me know if I am missing something in my understanding.

Comment (ekluzek) [reply tools/mksurfdata_map/unit_testers/test_mkgridmapMod.F90:337]: Ahhh, correct I looked into this to verify. That test list was testing the gridmap_areaoave_srcmask2 interface for gridmap_areaave. Since, that interface was removed there is no reason to have that list of tests in place. So removing it is the right thing to do.

**Review by ekluzek — APPROVED** [review]

**Comment by slevisconsulting** [comment]
Thanks @ekluzek 
Do I merge the PR next? I'm not used to being the one who does that, so I thought I'd ask first.

**Comment by ekluzek** [comment]
I'll go ahead and merge it. Although you might be right that you'd have merge permission for this branch.

**Comment by billsacks** [comment]
@ekluzek since this PR fixes a problem on master and does not change the surface datasets created by mksurfdata_map, I think it would be best if this is merged directly to master, then we can merge the latest master into the ctsm5.2.mksurfdata branch. I think it could be helpful to have the tools unit tests working on master.

More generally: Because of the pain sometimes caused by long-lived branches diverging from master, I feel like our rule should be: the only things that go onto the ctsm5.2.mksurfdata branch are things that CANNOT come to master yet. If there's something like this that is perfectly fine to come onto master, I think we'll have less long-term pain if we bring it to master and then update the ctsm5.2.mksurfdata branch accordingly.

**Comment by billsacks** [comment]
I would also add that the changes here are so minimal that I'd be comfortable with no additional testing being run (beyond verifying that the mksurfdata unit testers now work) before it is merged.

**Comment by ekluzek** [comment]
Ahhh yes good point. That makes sense to me. I'll change it back to master and merge it in.

That's a good rule anything that changes answers for mksurfdata so that it couldn't come to master.

**Comment by ekluzek** [comment]
We decided to flip this to go on master as @billsacks says above. As well this might as well go on master now, as it doesn't change code that is run in standard testing. So I'll merge it to master.
