### PR TITLE
Fixes for the LUNA dayl bugs

### LINKED ISSUE #953: Incorrect formula in LUNA
### Brief summary of bug

LUNA has a term where the night-time and day-time effect is averaged. The formula as implemented uses the day-time value for both night and day.

This was found by @lmbirch89. Thank you for figuring this out.

### General bug information

**CTSM version you are using:** ctsm1.0.dev086
**Does this bug cause significantly incorrect results in the model's science?** Unknown
**Configurations affected:** Clm5.0 

### Details of bug

tleafd10 is the day-time value and tleafn10 is the night-time value. To get tleaf10 it averages the two over the length of time they both apply. 

### Important details of your setup / configuration so we can reproduce the bug

Anytime LUNA is on. LUNA is always off for Fates and normally off for CLM4.5

### Important output or errors that show the problem

Here's the bug in the code:

``` fortran
git diff LunaMod.F90
diff --git a/src/biogeophys/LunaMod.F90 b/src/biogeophys/LunaMod.F90
index 35a38701..2fe5f1f8 100644
--- a/src/biogeophys/LunaMod.F90
+++ b/src/biogeophys/LunaMod.F90
@@ -332,7 +332,7 @@ module LunaMod
          hourpd = dayl(g) / 3600._r8             
          tleafd10 = t_veg10_day(p) - tfrz
          tleafn10 = t_veg10_night(p) - tfrz
-         tleaf10  = (dayl(g)*tleafd10 +(86400._r8-dayl(g)) * tleafd10)/86400._r8            
+         tleaf10  = (dayl(g)*tleafd10 +(86400._r8-dayl(g)) * tleafn10)/86400._r8            
          tair10 = t10(p)- tfrz
          relh10 = min(1.0_r8, rh10_p(p))  
         rb10v = rb10_p(p)   
```

### LINKED ISSUE #958: LUNA day length factor
### Brief summary of bug

@lmbirch89 thinks this is a bug, based on the orig. LUNA paper.
@dlawrenncar agrees, but there are big answer changes that should be considered before bringing them into CLM5 physics

### General bug information

**CTSM version you are using:** [output of `git describe`]
CLM5 release

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]
Yes

**Configurations affected:** [Fill this in if known.]
default CLM5

### Details of bug

From Leah's paper:
"The function, f(daylegth), is a scaling factor that is based on the formulation in Bauerle et al. (2012). However, the denominator is set to 12, when it should be the maximum day length possible at a particular latitude (Bauerle et al., 2012). This may not be appropriate where some regions experience up to 24 hour day light in summer, which allows Equation 1 to be > 1, particularly around the summer solstice in June."

### Important details of your setup / configuration so we can reproduce the bug

https://github.com/ESCOMP/CTSM/blob/384c726fa74e5a16ae15f6b40aad3e5d63b19d07/src/biogeophys/LunaMod.F90#L900

### PR DESCRIPTION
**Pull request by ekluzek**
### Description of changes

Fixes two of the LUNA day length bugs that @lmbirch89 found. Use the night term for the night section rather than the day version. And instead of assuming a 12 max day length, use the actual max daylength.

### Specific notes

Contributors other than yourself, if any: @lmbirch89

CTSM Issues Fixed (include github issue #): #953 #958 

 Fixes #953 
 Fixes #958

Are answers expected to change (and if so in what way)? Yes
 (when LUNA on, which is always for CLM5.0, but NOT for CLM4.5)

Any User Interface Changes (namelist or namelist defaults changes)? No

Testing performed, if any: regular
  Running regular testing now on cheyenne and izumi.
  @olyson will also run a longer simulation with it.

### CODE REVIEW

**Comment by ekluzek** [comment]
Testing on cheyenne and izumi has passed as expected. Clm45 and Fates cases compare the same as well as test cases with flexCN_FUN and noFUN_flexCN, since luna is off for those.

The following tests are also identical to the previous case even though Luna is on. The single point cases might just not see enough of a change, but I'm surprised about the f09, f10 and hcru ones.

- ERS_D_Ld7_Mmpi-serial.1x1_smallvilleIA.IHistClm50BgcCropGs.cheyenne_intel.clm-decStart1851_noinitial			
- ERS_Ld5_Mmpi-serial.1x1_vancouverCAN.I1PtClm50SpRsGs.cheyenne_intel.clm-default			
- FUNITCTSM_P1x1.f10_f10_musgs.I2000Clm50SpGs.cheyenne_intel			
- PFS_Ld20.f09_g17.I2000Clm50BgcCrop.cheyenne_intel			
- SMS_D_Ld1_Mmpi-serial.1x1_mexicocityMEX.I1PtClm50SpRsGs.cheyenne_intel.clm-default			
- SMS_D_Ld1_Mmpi-serial.1x1_vancouverCAN.I1PtClm50SpRsGs.cheyenne_gnu.clm-default			
- SMS_D_Ld1_Mmpi-serial.1x1_vancouverCAN.I1PtClm50SpRsGs.cheyenne_intel.clm-default			
- SMS_D_Ld1_Mmpi-serial.f45_f45_mg37.I2000Clm50SpGs.cheyenne_gnu.clm-ptsRLA			
- SMS_D_Ld1_Mmpi-serial.f45_f45_mg37.I2000Clm50SpGs.cheyenne_intel.clm-ptsRLA			
- SMS_D_Ld5_Mmpi-serial.1x1_mexicocityMEX.I1PtClm50SpRsGs.cheyenne_intel.clm-default			
- SMS_D_Lm1_Mmpi-serial.CLM_USRDAT.I1PtClm50SpRsGs.cheyenne_intel.clm-USUMB			
- SMS_Ld1_Mmpi-serial.1x1_mexicocityMEX.I1PtClm50SpRsGs.cheyenne_intel.clm-default			
- SMS_Ld1_Mmpi-serial.f45_f45_mg37.I2000Clm50SpGs.cheyenne_gnu.clm-ptsRLA			
- SMS_Ld1_Mmpi-serial.f45_f45_mg37.I2000Clm50SpGs.cheyenne_gnu.clm-ptsRLB			
- SMS_Ld1_Mmpi-serial.f45_f45_mg37.I2000Clm50SpGs.cheyenne_gnu.clm-ptsROA			
- SMS_Ld1_Mmpi-serial.f45_f45_mg37.I2000Clm50SpGs.cheyenne_intel.clm-ptsRLA			
- SMS_Ly1_Mmpi-serial.1x1_vancouverCAN.I1PtClm50SpRsGs.cheyenne_gnu.clm-output_sp_highfreq			
- SMS_P720x1_Ln6.hcru_hcru.I2000Clm50BgcCruGs.cheyenne_intel.clm-coldStart		
- ERS_D_Ld5_Mmpi-serial.1x1_mexicocityMEX.I1PtClm50SpRsGs.izumi_nag.clm-default			
- SMS_D_Ld1_Mmpi-serial.1x1_vancouverCAN.I1PtClm50SpRsGs.izumi_nag.clm-default			
- SMS_D_Ld1_Mmpi-serial.f45_f45_mg37.I2000Clm50SpGs.izumi_nag.clm-ptsRLA			
- SMS_Ld1_Mmpi-serial.f45_f45_mg37.I2000Clm50SpGs.izumi_nag.clm-ptsRLA

**Comment by lmbirch89** [comment]
@ekluzek I'm not surprised that some point simulations were not affected much as they don't appear to be in the high latitudes, but if the others are a global grid, I am surprised that it would be identical.

**Comment by ekluzek** [comment]
Yes, exactly I find that odd as well. But, most of the global grid tests do show a difference in answers, so I suppose it's not necessarily a problem.

**Comment by ekluzek** [comment]
I reran testing with the argument fix and things ran as expected other than this test that failed as follows...

SMS_Ld2_D.f09_g17.I1850Clm50BgcCropCmip6.cheyenne_intel.clm-basic_interp

> 36:  size=33687990 rss=61878 share=18331 text=23647 datastack=0
> 0:  size=33655620 rss=37175 share=10507 text=23647 datastack=0
> 0: memory_write: model date =   00010103       0 memory =  128211.89 MB (highwater)        141.62 MB (usage)  (pe=    0 comps= ATM IAC ESP)
> 133: p2g_1d error: sumwt is greater than 1.0 at g=         1176
> 133: calling getglobalwrite with decomp_index=         1176  and clmlevel= gridcell
> 133: local  gridcell index =         1176
> 133: global gridcell index =        19898
> 133: gridcell longitude    =    271.250000000000
> 133: gridcell latitude     =    72.0942408376963
> 133: ENDRUN:
>        

But, everything else passed as expected.

**Comment by olyson** [comment]
Diagnostics for this bug fix are here:

http://webext.cgd.ucar.edu/I1850/clm50_ctsm10d089_2deg_GSWP3V1_luna_1850/lnd/clm50_ctsm10d089_2deg_GSWP3V1_luna_1850.51_80-clm50_ctsm10d089_2deg_GSWP3V1_1850.51_80/setsIndex.html

These are 1850 simulations that have been run for 80 years.  Climatology is for the last 30 years.  There are trends in some state variables in the LUNA simulation (e.g., TLAI, TOTSOMC), so I'm continuing these simulations a bit further.

**Comment by wwieder** [comment]
Given these differences in GPP and NPP (> 8 & 3 Pg y-1, respectively) that are concentrated at high latitudes, I wouldn't expect soil C pools to come into equilibrium without going back to an AD spinup.  @dlawrenncar an we still run transient 20th  century simulations w/out the AD spinup and get meaningful results to compare?  @lmbirch89 I know it's hard to say, but are the direction and magnitude of the changes seen here consistent with what you'd expect?  Happy to help walk through diagnostics that @olyson sent, if you're not familiar with this  fire hose of information.

**Comment by wwieder** [comment]
These 'bugs' also seem like they'll have pretty significant climate changing  answers, with a big drop Arctic LAI, ET and LH fluxes paired with higher sensible heat & runoff.  @oleson,  do you have pft  level output on so we can check for survival?

**Comment by lmbirch89** [comment]
@wwieder These are definitely a lot of figures! I think I followed them though. The red lines are the bug fixes to LUNA, right? The decrease in productivity is expected because the day fraction before used to be larger than 1 at high latitudes, which was increasing productivity artificially.

**Comment by wwieder** [comment]
One  more  quesion on  spinup- the transient effect of reduced productivity and SOMC losses  means that high latitude ecosystems are flush with N  that [causes big drops in plant stiochiometry.](http://webext.cgd.ucar.edu/I1850/clm50_ctsm10d089_2deg_GSWP3V1_luna_1850/lnd/clm50_ctsm10d089_2deg_GSWP3V1_luna_1850.51_80-clm50_ctsm10d089_2deg_GSWP3V1_1850.51_80/set6/set6_crbStock_Eastern_Canada.png)  This makes me less sure that these will be meaningful in  a   transient  run w/o an ADspinup.

**Comment by wwieder** [comment]
@olyson let's hold off on running more simulations for a bit.  This initialization gives us enough information to know that the bug fixes are really answer changing and we need to learn a bit more before making a plan about how to move forward to maintain backwards capabilities for CLM5 physics.

**Comment by wwieder** [comment]
The third potential LUNA bug identified was initial Vcmax and Jmax values used when deciduous plants put on leaves. [The code in question is here](https://github.com/ESCOMP/CTSM/blob/b0610edab61ddca95ca773cb8af84ead57503983/src/biogeophys/LunaMod.F90#L475)

@lmbirch89 says the model is very sensitive to the values of these initial conditions and is  suggesting we use the accumulator to save values the previous year, as opposed to the hard coded values currently being used (see #947).  I've asked @xuchongang to comment, but do  we want to bring  these initialization values  for Vcmax and Jmax in as a bug fix or the other arctic C cycle  updates?

File: src/biogeophys/LunaMod.F90 [hunk 1]
```diff
@@ -306,7 +306,9 @@ subroutine Update_Photosynthesis_Capacity(bounds, fn, filterp, &
     vcmx25_z      => photosyns_inst%vcmx25_z_patch                    , & ! Output: [real(r8) (:,:) ] patch leaf Vc,max25 (umol/m2 leaf/s) for canopy layer 
     jmx25_z       => photosyns_inst%jmx25_z_patch                     , & ! Output: [real(r8) (:,:) ] patch leaf Jmax25 (umol electron/m**2/s) for canopy layer
     pnlc_z        => photosyns_inst%pnlc_z_patch                      , & ! Output: [real(r8) (:,:) ] patch proportion of leaf nitrogen allocated for light capture for canopy layer 
-    enzs_z        => photosyns_inst%enzs_z_patch                        & ! Output: [real(r8) (:,:) ] enzyme decay status 1.0-fully active; 0-all decayed during stress
+    enzs_z        => photosyns_inst%enzs_z_patch                      , & ! Output: [real(r8) (:,:) ] enzyme decay status 1.0-fully active; 0-all decayed during stress
+    vcmx_prevyr   => photosyns_inst%vcmx_prevyr                       , & ! Output: [real(r8) (:,:) ] patch leaf Vc,max25 from previous year avg
+    jmx_prevyr    => photosyns_inst%jmx_prevyr                          & ! Output: [real(r8) (:,:) ] patch leaf Jmax25 from previous year avg
```
Comment (wwieder) [inline src/biogeophys/LunaMod.F90:311]: The comments here should just not be the `previous year avg`, but   the values from the end  of the growing season for the  previous  year. @billsacks did you  have thoughts about how to  name this  variable in the  first place?

File: src/biogeophys/PhotosynthesisMod.F90 [hunk 2]
```diff
@@ -183,6 +183,8 @@ module  PhotosynthesisMod
      ! LUNA specific variables
      real(r8), pointer, public  :: vcmx25_z_patch    (:,:) ! patch  leaf Vc,max25 (umol CO2/m**2/s) for canopy layer 
      real(r8), pointer, public  :: jmx25_z_patch     (:,:) ! patch  leaf Jmax25 (umol electron/m**2/s) for canopy layer 
+     real(r8), pointer, public  :: vcmx_prevyr       (:,:) ! patch  leaf Vc,max25 previous year running avg
+     real(r8), pointer, public  :: jmx_prevyr       (:,:) ! patch  leaf Jmax25 previous year running avg
```
Comment (wwieder) [inline src/biogeophys/PhotosynthesisMod.F90:187]: As in LunaMod, this comment is misleading since we're not  taking  the running average. We should be consistent with LunaMod.

File: src/biogeophys/PhotosynthesisMod.F90 [hunk 3]
```diff
@@ -328,6 +330,8 @@ subroutine InitAllocate(this, bounds)
       ! statements.
       allocate(this%vcmx25_z_patch  (begp:endp,1:nlevcan)) ; this%vcmx25_z_patch    (:,:) = 30._r8
       allocate(this%jmx25_z_patch   (begp:endp,1:nlevcan)) ; this%jmx25_z_patch     (:,:) = 60._r8 
+      allocate(this%vcmx_prevyr     (begp:endp,1:nlevcan)) ; this%vcmx_prevyr       (:,:) = 85._r8
+      allocate(this%jmx_prevyr      (begp:endp,1:nlevcan)) ; this%jmx_prevyr        (:,:) = 50._r8
```
Comment (wwieder) [inline src/biogeophys/PhotosynthesisMod.F90:334]: hopefully  doesn't  really matter, but the hard coded values we're replacing  in  LUNA are  were for `vcmx25` = 50 (not 85) & `jmx25` = 85 (not 50)
In lines 331-2 of photosynthesisMod `vcmx25` and  `jmx25` are initialized to 30 & 60, respectively.  Either one of these seem preferable, but not sure which is better?

File: src/biogeophys/PhotosynthesisMod.F90 [hunk 4]
```diff
@@ -833,6 +837,14 @@ subroutine Restart(this, bounds, ncid, flag)
...
          long_name='Maximum carboxylation rate at 25 celcius for canopy layers', units='umol CO2/m**2/s', &
          interpinic_flag='interp', readvar=readvar, data=this%jmx25_z_patch)
+      call restartvar(ncid=ncid, flag=flag, varname='vcmx_prevyr', xtype=ncd_double,  &
+         dim1name='pft', dim2name='levcan', switchdim=.true., &
+         long_name='avg carboxylation rate at 25 celsius for canopy layers', units='umol CO2/m**2/s', &
+         interpinic_flag='interp', readvar=readvar, data=this%vcmx_prevyr)
+      call restartvar(ncid=ncid, flag=flag, varname='jmx_prevyr', xtype=ncd_double,  &
+         dim1name='pft', dim2name='levcan', switchdim=.true., &
+         long_name='avg carboxylation rate at 25 celsius for canopy layers', units='umol CO2/m**2/s', &
+         interpinic_flag='interp', readvar=readvar, data=this%jmx_prevyr)
```
Comment (wwieder) [inline src/biogeophys/PhotosynthesisMod.F90:847]: long names here should match what we're using in the description above, something about the previous year?  

Minor correction, but `jmx25_z_patch` and  `jmx_prevyr` long_name should be maximum rate of electron transport at 25 celsius for canopy layers, with units `umol electron/m**2/s`

**Comment by ekluzek** [comment]
Good suggestions @wwieder. I just brought in exactly what was on @lmbirch89 branch. These changes shouldn't change answers, so I'm going to wait on doing them until after we are sure this is what we want to bring in. So I'll wait for @olyson to run testing on them. Then I can make sure these updates don't change answers for sure.

File: src/biogeophys/LunaMod.F90 (hunk 1 above)
Comment (billsacks) [reply src/biogeophys/LunaMod.F90:311]: My main thought was to avoid having "yr" / "year" in the name. I suggested `vcmx_last_active_day`, but I'm not sure if that's the best. @ekluzek suggested something including "last_valid", which also seems reasonable. Good naming is so hard... (and yet so important).

File: src/biogeophys/PhotosynthesisMod.F90 (hunk 3 above)
Comment (billsacks) [reply src/biogeophys/PhotosynthesisMod.F90:334]: Thank you for raising this point here @wwieder . In addition to cold start, times I can think of when these initial values will matter are (1) in the first year of existence of a crop that newly appears in a grid cell in a transient case; and (2) in the first year after restart for cases using old restart files, including all cases run from master until we update our out-of-the-box finidat files. So, while these values may not be hugely important, they seem more important than your typical cold start initialization value.

**Comment by billsacks** [comment]
> These changes shouldn't change answers

@ekluzek - note that @wwieder 's question about the cold start initialization values could change answers, though hopefully wouldn't change things _too_ dramatically.

**Comment by wwieder** [comment]
@olyson [posted these diagnostics](http://webext.cgd.ucar.edu/I1850/clm50_ctsm10d089_2deg_GSWP3V1_luna3_1850/lnd/clm50_ctsm10d089_2deg_GSWP3V1_luna3_1850.171_200-clm50_ctsm10d089_2deg_GSWP3V1_1850.171_200/setsIndex.html)

**Comment by wwieder** [comment]
@olyson  put up diagnostics for 

- [first two bug fixes](http://webext.cgd.ucar.edu/I1850/clm50_ctsm10d089_2deg_GSWP3V1_luna_1850/lnd/clm50_ctsm10d089_2deg_GSWP3V1_luna_1850.171_200-clm50_ctsm10d089_2deg_GSWP3V1_1850.171_200/setsIndex.html) vs. control #953 & #958 
- [all three bug fixes](http://webext.cgd.ucar.edu/I1850/clm50_ctsm10d089_2deg_GSWP3V1_luna3_1850/lnd/clm50_ctsm10d089_2deg_GSWP3V1_luna3_1850.171_200-clm50_ctsm10d089_2deg_GSWP3V1_1850.171_200/setsIndex.html) vs. control #953 , #958, & #981
- [effect of initial VCmax and Jmax fix alone](http://webext.cgd.ucar.edu/I1850/clm50_ctsm10d089_2deg_GSWP3V1_luna3_1850/lnd/clm50_ctsm10d089_2deg_GSWP3V1_luna3_1850.171_200-clm50_ctsm10d089_2deg_GSWP3V1_luna_1850.171_200/setsIndex.html) (Luna3 - Luna2)  #981 


Specifically @lmbirch89 there [doesn't seem to be much of an effect](http://webext.cgd.ucar.edu/I1850/clm50_ctsm10d089_2deg_GSWP3V1_luna3_1850/lnd/clm50_ctsm10d089_2deg_GSWP3V1_luna3_1850.171_200-clm50_ctsm10d089_2deg_GSWP3V1_luna_1850.171_200/set3/set3_cnFlx_Alaskan_Arctic.png) on the initial conditions for photosynthetic capacity.  I'd expected some shift in GPP early in the growing season, but it's not obvious. Is this consistent with your findings?

**Comment by lmbirch89** [comment]
@wwieder Yes, I found that initial conditions didn't matter too much if you are running the model for many years. I think the initialization only matters if you are analyzing less than a year of output.

File: src/biogeophys/PhotosynthesisMod.F90 (hunk 3 above)
Comment (billsacks) [reply src/biogeophys/PhotosynthesisMod.F90:334]: See also comment from @lmbirch89: https://github.com/ESCOMP/CTSM/pull/947#discussion_r407784297

File: src/biogeophys/LunaMod.F90 (hunk 1 above)
Comment (billsacks) [reply src/biogeophys/LunaMod.F90:311]: Another note about these names: they need `_patch` suffixes. Also, it's probably best if they maintain the `25_z` that appears in `vcmx25_z` and `jmx25_z` variable names, to show the correspondence between these variables.

**Comment by wwieder** [comment]
@olyson ran clean 20th century runs with bug fixes

There are some regular [diagnostics for the LUNA bug fixes compared to control here](http://webext.cgd.ucar.edu/I20TR/clm50_ctsm10d089_2deg_GSWP3V1_luna3_hist/lnd/clm50_ctsm10d089_2deg_GSWP3V1_luna3_hist.1995_2014-clm50_ctsm10d089_2deg_GSWP3V1_histF.1995_2014/setsIndex.html).

and[ ILAMB results here](http://webext.cgd.ucar.edu/I20TR/clm50_ctsm10d089_2deg_GSWP3V1_luna3_hist/lnd/_build_LUNA3/).

A few observations:

- Regional  heterogeneity of  improvement /  degradation are pretty  striking  (better GPP over boreal forests  of North America and worse  over boreal  forests  of Eurasia). 

- The phenology of LAI is pretty woeful  across high latitudes, so presumably @lmbirch89 changes to phenology and allocation  will improve things for CTSM5.1.   

- As @dlawrenncar notes, it does  present challenges for using 5.0  physics with the  LUNAbugFixes  #961.

- This makes  me wonder if we should look at SP simulations to evaluate the effect of  the LUNA bugs on  GPP  without downstream effects on biogeochemistry? Not  sure  if we'd learn that much more beyond, GPP is lower with the LUNA bugFixes

- Finally,  I'm not really  sure why GPP is lower in the Eastern US  with the bugFixes, but it makes me wonder how much we'll need to reparameterize the model in non-Arctic pfts?

**Comment by ekluzek** [comment]
@olyson ran a simulation with this branch and these two namelist changes:

jmaxb1 = 0.17
paramfile = '/glade/p/cgd/tss/people/oleson/modify_param/clm5_params.c200402.slatopA_leafcnA.nc'

for case clm50_ctsm10d089_2deg_GSWP3V1_luna3_jmaxb1-0.17_slatopA_leafcnA_hist. It sounds like we want to bring this in as the updated CLM5.0.

The changes to the paramsfile are to leafcn, leafcn_max, leafcn_min, slatop

 RMS leafcn                           8.5037E-01            NORMALIZED  3.8059E-02
 RMS leafcn_max                       6.3095E-01            NORMALIZED  5.6833E-02
 RMS leafcn_min                       6.3095E-01            NORMALIZED  1.2554E-01
 RMS slatop                           2.1862E-03            NORMALIZED  6.4128E-02

**Comment by wwieder** [comment]
I'm  not sure what the text pasted below means @ekluzek,  but yes, we want to bring the bug fixes to master with those two namelist changes from @olyson.
------------
RMS leafcn 8.5037E-01 NORMALIZED 3.8059E-02
RMS leafcn_max 6.3095E-01 NORMALIZED 5.6833E-02
RMS leafcn_min 6.3095E-01 NORMALIZED 1.2554E-01
RMS slatop 2.1862E-03 NORMALIZED 6.4128E-02

**Comment by ekluzek** [comment]
The paramsfile changes are to index 11 and 12 which are broadleaf_deciduous_boreal_shrub and c3_arctic_grass. Everything else is the same.

Changes 11 and 12 of slatop from: 0.03072, 0.04024 to  0.028, 0.021
11 and 12 of leafcn_min from 15 to 11.4, 10.7
11 and 12 of leafcn_max from 35 to 31.4, 30.7
11 and 12 of leafcn from 23.2558139534884, 28.0269058295964 to 21.4, 20.7

**Comment by ekluzek** [comment]
All tests have passed as expected, and the clm4_5 answers don't change as expected.

File: src/biogeophys/PhotosynthesisMod.F90 (hunk 3 above)
Comment (ekluzek) [reply src/biogeophys/PhotosynthesisMod.F90:350]: Since, our simulations have been run with these values -- we'll need to get the correct values on #947.

File: src/biogeophys/LunaMod.F90 (hunk 1 above)
Comment (ekluzek) [reply src/biogeophys/LunaMod.F90:324]: We'll fix this in #1060

File: src/biogeophys/PhotosynthesisMod.F90 (hunk 2 above)
Comment (ekluzek) [reply src/biogeophys/PhotosynthesisMod.F90:204]: We'll fix this in #1060

File: src/biogeophys/PhotosynthesisMod.F90 (hunk 4 above)
Comment (ekluzek) [reply src/biogeophys/PhotosynthesisMod.F90:902]: We'll fix this in #1060

File: src/biogeophys/LunaMod.F90 (hunk 1 above)
Comment (ekluzek) [reply src/biogeophys/LunaMod.F90:324]: Make that #1107 since this is answer changing

File: src/biogeophys/PhotosynthesisMod.F90 (hunk 3 above)
Comment (ekluzek) [reply src/biogeophys/PhotosynthesisMod.F90:350]: We'll fix this for #1107

Comment (ekluzek) [reply src/biogeophys/PhotosynthesisMod.F90:350]: This is coming in with my PR #1102
