### PR TITLE
Fix clm6_0 defaults

### LINKED ISSUE #2492: Fix defaults in clm6_0 physics
### Brief summary of bug

I'm creating cases with CLM5.2 and noticed that `snow_thermal_cond_method` defaults to Jordan1991 in both SP and BGC cases.  Is this intended?  I thought we switched this to Sturm1997 in #2348?

### LINKED ISSUE #2504: build-namelist tester wasn't properly going over all use-cases
### Brief summary of bug

As a contributor to #2492, the build-namelist unit tester wasn't going over all the use-cases like it was supposed to.

### General bug information

**CTSM version you are using:** ctsm5.2.002

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** Just the unit-tester itself

### Details of bug

I think this bug goes way back. I had been relying on the fact that all use-cases were tested at least in the unit-tester and that wasn't happening. As part of the fix I'll add an update that makes sure the number of use-cases are as expected.

### LINKED ISSUE #2519: MKSURFDATAESMF build fails in cesm2_3_alpha17d and cesm2_3_alpha17e testing
### Brief summary of bug

@fischer-ncar ran into this problem in both cesm2_3_alpha17d and cesm2_3_alpha17e testing. Since, this worked for us in ctsm5.2.0 it must be the difference in externals.

### General bug information

**CTSM version you are using:** ctsm5.2.0

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** just mksurfdata_emsf

### Important details of your setup / configuration so we can reproduce the bug

In both cesm2_3_beta17d and cesm2_3_beta17e

### Important output or errors that show the problem

```
PEND MKSURFDATAESMF_P128x1.f10_f10_mg37.I1850Clm50BgcCrop.derecho_intel SHAREDLIB_BUILD RERUN
 ---------------------------------------------------
2024-05-02 15:27:44: Exception during build:
Command '/glade/u/home/fischer/code/cesm2_3_alpha17e/components/clm/tools/mksurfdata_esmf/gen_mksurfdata_build --blddir /glade/derecho/scratch/fischer/t/cesm2_3_alpha17e_i/MKSURFDATAESMF_P128x1.f10_f10_mg37.I1850Clm50BgcCrop.derecho_intel.GC.c2_3_a17e_int/tool_bld' returned non-zero exit status 1. ERROR RUNNING /glade/u/home/fischer/code/cesm2_3_alpha17e/components/clm/tools/mksurfdata_esmf/gen_mksurfdata_build DETAILS IN /glade/derecho/scratch/fischer/t/cesm2_3_alpha17e_i/MKSURFDATAESMF_P128x1.f10_f10_mg37.I1850Clm50BgcCrop.derecho_intel.GC.c2_3_a17e_int/TestStatus.log

Traceback (most recent call last):
  File "/glade/u/home/fischer/code/cesm2_3_alpha17e/components/clm/cime_config/SystemTests/mksurfdataesmf.py", line 91, in build_phase
subprocess.check_call(f"{build_script_path} --blddir {self._tool_bld}", shell=True)
  File "/glade/u/apps/derecho/23.09/opt/._view/dmewvyohndr7lajyom5grftguonqfbdr/lib/python3.10/subprocess.py", line 369, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/glade/u/home/fischer/code/cesm2_3_alpha17e/components/clm/tools/mksurfdata_esmf/gen_mksurfdata_build --blddir /glade/derecho/scratch/fischer/t/cesm2_3_alpha17e_i/MKSURFDATAESMF_P128x1.f10_f10_mg37.I1850Clm50BgcCrop.derecho_intel.GC.c2_3_a17e_int/tool_bld' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/glade/u/home/fischer/code/cesm2_3_alpha17e/cime/CIME/SystemTests/system_tests_common.py", line 191, in build
self.build_phase(
  File "/glade/u/home/fischer/code/cesm2_3_alpha17e/components/clm/cime_config/SystemTests/mksurfdataesmf.py", line 94, in build_phase
sys.exit(
SystemExit: Command '/glade/u/home/fischer/code/cesm2_3_alpha17e/components/clm/tools/mksurfdata_esmf/gen_mksurfdata_build --blddir /glade/derecho/scratch/fischer/t/cesm2_3_alpha17e_i/MKSURFDATAESMF_P128x1.f10_f10_mg37.I1850Clm50BgcCrop.derecho_intel.GC.c2_3_a17e_int/tool_bld' returned non-zero exit status 1. ERROR RUNNING /glade/u/home/fischer/code/cesm2_3_alpha17e/components/clm/tools/mksurfdata_esmf/gen_mksurfdata_build DETAILS IN /glade/derecho/scratch/fischer/t/cesm2_3_alpha17e_i/MKSURFDATAESMF_P128x1.f10_f10_mg37.I1850Clm50BgcCrop.derecho_intel.GC.c2_3_a17e_int/TestStatus.log
```

### LINKED ISSUE #2520: B1850 compsets are failing cesm2_3_alpha17d and cesm2_3_alpha17e
### Brief summary of bug

@fischer-ncar found tests such as SMS_Ld7.f09_g17.B1850.derecho_intel.allactive-defaultio are failing in cesm2_3_alpha17d and cesm2_3_alpha17e because the finidat files need to have use_init_interp=TRUE and for some reason this isn't happening.

### General bug information

**CTSM version you are using:** ctsm5.2.0

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** f09 @ B1850

### Important details of your setup / configuration so we can reproduce the bug

In cesm2_3_alpha17d and cesm2_3_alpha17e

### Important output or errors that show the problem

```
[dec1768.hsn.de.hpc.ucar.edu](http://dec1768.hsn.de.hpc.ucar.edu/) 393:  check_dim_size ERROR: mismatch of input dimension        50591
[dec1768.hsn.de.hpc.ucar.edu](http://dec1768.hsn.de.hpc.ucar.edu/) 393:   with expected value        48292  for variable landunit
[dec1768.hsn.de.hpc.ucar.edu](http://dec1768.hsn.de.hpc.ucar.edu/) 393: Did you mean to set use_init_interp = .true. in user_nl_clm?
[dec1768.hsn.de.hpc.ucar.edu](http://dec1768.hsn.de.hpc.ucar.edu/) 393: (Setting use_init_interp = .true. is needed when doing a
[dec1768.hsn.de.hpc.ucar.edu](http://dec1768.hsn.de.hpc.ucar.edu/) 393: transient run using an initial conditions file from a non-transient run,
[dec1768.hsn.de.hpc.ucar.edu](http://dec1768.hsn.de.hpc.ucar.edu/) 393: or a non-transient run using an initial conditions file from a transient run,
[dec1768.hsn.de.hpc.ucar.edu](http://dec1768.hsn.de.hpc.ucar.edu/) 393: or when running a resolution or configuration that differs from the initial conditions.)
[dec1768.hsn.de.hpc.ucar.edu](http://dec1768.hsn.de.hpc.ucar.edu/) 393:  ERROR:
[dec1768.hsn.de.hpc.ucar.edu](http://dec1768.hsn.de.hpc.ucar.edu/) 393:  ERROR in /glade/u/home/fischer/code/cesm2_3_alpha17e/components/clm/src/main/nc
[dec1768.hsn.de.hpc.ucar.edu](http://dec1768.hsn.de.hpc.ucar.edu/) 393:  [dio_pio.F90.in](http://dio_pio.f90.in/) at line 409
```

### PR DESCRIPTION
**Pull request by ekluzek**
### Description of changes

Fix namelist defaults for clm6_0 brought in with ctsm5.2.0 as identified in #2492 

### Specific notes

Contributors other than yourself, if any:

CTSM Issues Fixed (include github issue #):
  Fixes #2492
  Fixes #2504
  Fixes #2519 
  Fixes #2520
  One tick box in #2403

Are answers expected to change (and if so in what way)? Yes! (only for clm6_0 physics though)

Any User Interface Changes (namelist or namelist defaults changes)?
   snicar_snobc_intmix, snow_thermal_cond_method, and irrigate
   fix use_cases for clm6_0

Testing performed, if any: namelist testing, regular and ctsm_sci test lists

### CODE REVIEW

**Comment by ekluzek** [comment]
In CSEG we decided this is OK to bring in for cesm2_3_beta18 since the CESM coupled compsets use clm5_1.

**Comment by wwieder** [comment]
I'm a little confused by this last comment.  Why is CESM using clm5_1 physics?  I thought the whole reason for delaying the alpha17 tag was to get 5.2 datasets onto main to avoid all the source mods and workarounds needed to run a 5.2 dataset with 5.1 physics?

Regardless, will the beta17 tag have dead arctic veg modifications active?

**Comment by ekluzek** [comment]
@wwieder this is all something we'll discuss more in depth as a group tomorrow. Yes, I did the update to clm6_0 in ctsm5.2.0 and it naturally fits there -- but was it required and the best time to do it? This will come up in the future so learning here can help us down the road.

At ctsm5.2.0 clm5_1 becomes deprecated (see #2379), misnamed, and misleading. A natural thing to think is that clm5_1 would use the clm5_1 surface datasets while clm6_0 uses the newer ones. So at ctsm5.2.0 I removed almost all of the "I compset" Clm51 compsets, and changed all the testing to Clm60. You can still use clm5_1 with long name compsets for "I cases" though.

At ctsm5.2.0 it becomes a project for CESM to remove uses of CLM51 in compsets and tests. As you can see from #2379 it will take a while for this to go through CESM. Changes in CESM across components take awhile to happen by nature.

But, ctsm5.2.0 is correct when clm5_1 in terms of use of the dead-veg. So the current CAM and CESM compsets will be fine. And that's what will be used for the coupled model testing. Part of what we were looking for on Tuesday at CSEG was to NOT require a tag that was absolutely required for cesm2_3_beta17. This still might make it in though...

File: bld/unit_testers/cmp_baseline_lnd_in_files.sh [hunk 1]
```diff
@@ -0,0 +1,46 @@
+#!/bin/bash
+
```
Comment (ekluzek) [inline bld/unit_testers/cmp_baseline_lnd_in_files.sh:2]: Needs a description of the purpose

File: cime_config/config_compsets.xml [hunk 2]
```diff
@@ -291,22 +295,24 @@
 
   <compset>
      <alias>I1850Clm60BgcNoAnthro</alias>
-     <lname>1850_DATM%GSWP3v1_CLM60%BGC-NOANTHRO_SICE_SOCN_MOSART_SGLC_SWAV</lname>
+     <lname>1850_DATM%GSWP3v1_CLM60%BGC-NOANTHRO_SICE_SOCN_RTM_SGLC_SWAV</lname>
+     <science_support grid="f09_g17"/>
```
Comment (ekluzek) [inline cime_config/config_compsets.xml:299]: Add these two to the testlist

File: cime_config/config_compsets.xml [hunk 3]
```diff
@@ -631,6 +640,17 @@
   <compset>
     <alias>I1850Clm60BgcCropG</alias>
```
Comment (ekluzek) [inline cime_config/config_compsets.xml:641]: This needs to be added to the ctsm_sci testlist.

Comment (ekluzek) [reply cime_config/config_compsets.xml:641]: OK, I added it to aux_clm, so it should also be in ctsm_sci

File: cime_config/testdefs/testlist_clm.xml [hunk 4]
```diff
@@ -331,6 +331,24 @@
       <option name="comment"  >Science support for 1850 with clm5_1 for SP mode at f19</option>
     </options>
   </test>
+  <test name="SMS_Ld1" grid="f09_g17" compset="I1850Clm60Sp" testmods="clm/clm60cam60LndTuningMode">
+    <machines>
+      <machine name="derecho" compiler="intel" category="ctsm_sci"/>
+    </machines>
+    <options>
+      <option name="wallclock">00:20:00</option>
+      <option name="comment"  >Science support for 1850 with clm5_1 for SP mode at f09 with cam60</option>
```
Comment (ekluzek) [inline cime_config/testdefs/testlist_clm.xml:340]: Oh, instances of clm5_1 should be changed to clm6_0.
Do a `git grep clm5_1` and see if it needs to be removed elsewhere...

Comment (ekluzek) [reply cime_config/testdefs/testlist_clm.xml:340]: Got it.

File: bld/namelist_files/namelist_defaults_ctsm.xml [hunk 5]
```diff
@@ -116,9 +116,9 @@ attributes from the config_cache.xml file (with keys converted to upper-case).
 <atm_c14_filename use_c14=".true." use_c14_bombspike =".true." ssp_rcp="SSP5-8.5" >lnd/clm2/isotopes/atm_delta_C14_CMIP6_SSP5B_3x1_global_1850-2100_yearly_c181209.nc</atm_c14_filename>
 
 <!-- Irrigation default -->
-<irrigate >.false.</irrigate>
 <irrigate               use_cndv=".false."  sim_year_range="1850-2100">.true.</irrigate>
 <irrigate phys="clm4_5" use_cndv=".false."  sim_year_range="1850-2100">.false.</irrigate>
+<irrigate >.false.</irrigate>
```
[the remark this answers is not in the document]
Comment (ekluzek) [reply bld/namelist_files/namelist_defaults_ctsm.xml]: Got it.

File: bld/unit_testers/cmp_baseline_lnd_in_files.sh [hunk 6]
```diff
@@ -0,0 +1,46 @@
...
+baseline=$1
+compare=$2
```
Comment (ekluzek) [inline bld/unit_testers/cmp_baseline_lnd_in_files.sh:4]: This also should have error checking and usage added in.

**Review by slevis-lmwg — APPROVED** [review]
@ekluzek thank you for showing me the work that went into this PR.

File: bld/unit_testers/cmp_baseline_lnd_in_files.sh (hunk 6 above)
Comment (ekluzek) [reply bld/unit_testers/cmp_baseline_lnd_in_files.sh:4]: Got it.

File: bld/unit_testers/cmp_baseline_lnd_in_files.sh (hunk 1 above)
Comment (ekluzek) [reply bld/unit_testers/cmp_baseline_lnd_in_files.sh:2]: Added in.

File: cime_config/config_compsets.xml (hunk 2 above)
Comment (ekluzek) [reply cime_config/config_compsets.xml:299]: I updated them from Clm50 to Clm60.

File: bld/namelist_files/use_cases/20thC_transient.xml [hunk 7]
```diff
@@ -18,46 +18,20 @@
...
-<stream_year_first_urbantv phys="clm5_0"  >1850</stream_year_first_urbantv>
-<stream_year_last_urbantv  phys="clm5_0"  >2106</stream_year_last_urbantv>
-<model_year_align_urbantv  phys="clm5_0"  >1850</model_year_align_urbantv>
-
-<stream_year_first_urbantv phys="clm5_1"  >1850</stream_year_first_urbantv>
-<stream_year_last_urbantv  phys="clm5_1"  >2106</stream_year_last_urbantv>
-<model_year_align_urbantv  phys="clm5_1"  >1850</model_year_align_urbantv>
+<irrigate use_crop=".true."               use_cndv=".false.">.true.</irrigate>
+<irrigate use_crop=".true."               use_cndv=".true." >.false.</irrigate>
+<irrigate use_crop=".true." phys="clm4_5"                   >.false.</irrigate>
```
Comment (ekluzek) [inline bld/namelist_files/use_cases/20thC_transient.xml:23]: This setting ends up being different from ctsm5.1.dev176 for clm4_5, but I think the new version is correct. So leaving this as it is.

File: bld/namelist_files/use_cases/2010_control.xml [hunk 8]
```diff
@@ -8,44 +8,17 @@
...
 
-<irrigate use_crop=".true." phys="clm5_1"  use_cndv=".false.">.true.</irrigate>
-<irrigate use_crop=".true." phys="clm5_1"  use_cndv=".false.">.true.</irrigate>
-<irrigate use_crop=".true." phys="clm5_1"  use_cndv=".true." >.false.</irrigate>
-<irrigate use_crop=".true." phys="clm5_0"  use_cndv=".false.">.true.</irrigate>
-<irrigate use_crop=".true." phys="clm5_0"  use_cndv=".true." >.false.</irrigate>
-<irrigate use_crop=".true." phys="clm4_5"                    >.false.</irrigate>
+<irrigate use_crop=".true." =".false."    >.true.</irrigate>
+<irrigate use_crop=".true." =".false."    >.true.</irrigate>
+<irrigate use_crop=".true." phys="clm4_5" >.false.</irrigate>
```
Comment (ekluzek) [inline bld/namelist_files/use_cases/2010_control.xml:13]: This setting ends up being different from ctsm5.1.dev176 for clm4_5, but I think the new version is correct. So leaving this as it is.

**Comment by slevis-lmwg** [comment]
Summary of aux_clm on izumi...
Ok except that this test failed on setup before including the last commit:
`SMS_Ly5_Mmpi-serial.1x1_smallvilleIA.IHistClm60BgcCropQianRs.izumi_gnu.clm-gregorian_cropMonthOutput`
The last commit fixed it.
