### PR TITLE
Minor fixes to names and units of canopy turbulence variables

### LINKED ISSUE #3112: Proposed minor updates to canopy biogeophysics diagnostic variables
I was going through the code to incorporate a few additional output variables in ELM based on the CLM code (E3SM-Project/E3SM#7328), and in the process I found the following: 

1. The units and description of variable `USTAR` are incorrect. I guess the description should be friction velocity, and the units should be m/s.

https://github.com/ESCOMP/CTSM/blob/e0104b91fef35b06aa1458b3023a7d83f568ad03/src/biogeophys/FrictionVelocityMod.F90#L286-L288

2. A few lines later, variable `VPD` seems to be reported in Pa:

https://github.com/ESCOMP/CTSM/blob/e0104b91fef35b06aa1458b3023a7d83f568ad03/src/biogeophys/FrictionVelocityMod.F90#L314-L316

But the actual calculation has a factor of `0.001_r8`, which seems to be a conversion factor to kPa.

https://github.com/ESCOMP/CTSM/blob/e0104b91fef35b06aa1458b3023a7d83f568ad03/src/biogeophys/CanopyFluxesMod.F90#L1103-L1111

3. This one is just a very minor detail, but the term "Monin-Obukhov length" is incorrect, it should be "Obukhov length" according to the [American Meteorological Society](https://glossary.ametsoc.org/wiki/Obukhov_length).

I have a commit ready for pull request that addresses all these points, but I am first opening an issue to see if there are any concerns with my suggested changes.

### PR DESCRIPTION
**Pull request by mpaiao**
### Description of changes

I was adding a few diagnostic variables to ELM based on the CLM code (E3SM-Project/E3SM#7328), and in the process I found a few typos and a potential bug in one of the diagnostic variables.

1. The description and the units of variable `ustar` were incorrect (file `src/biogeophys/FrictionVelocityMod.F90`).
2. The units listed for variable `'VPD'` in the call to sub-routine `hist_addfld1d` (file `src/biogeophys/FrictionVelocityMod.F90`) is Pa, however the calculation of VPD in file `src/biogeophys/CanopyFluxesMod.F90` had a 0.001_r8 multiplication factor, which I think implies conversion to kPa.
3. Replaced the "Monin-Obukhov length" occurrences in comments and output name with "Obukhov length scale", which is consistent with Bonan (2015) and the [American Meteorological Society](https://glossary.ametsoc.org/wiki/Obukhov_length).

### Specific notes

Contributors other than yourself, if any:
@olyson

CTSM Issues Fixed (include github issue #): 
Fixes #3112 that has the proposed fixes

Are answers expected to change (and if so in what way)? 
This should be bit-for-bit, only metadata and code comments updated.

Any User Interface Changes (namelist or namelist defaults changes)?
No

Does this create a need to change or add documentation? Did you do so?
No

Testing performed, if any: will run regular testing

### CODE REVIEW

**Review by ekluzek — APPROVED** [review]
Thanks @mpaiao this is a very helpful contribution. Thanks for making a PR for it!

It's correcting units in comments, as well as being more careful with terminology used in names in comments. And gives better names and units for history fields as well. These are all good things to have before the release.

File: src/biogeophys/FrictionVelocityMod.F90 [hunk 1]
```diff
@@ -304,15 +304,15 @@ subroutine InitHistory(this, bounds)
...
             ptr_patch=this%obu_patch, default='inactive')
        this%zeta_patch(begp:endp) = spval
        call hist_addfld1d (fname='ZETA', units='unitless', &
             avgflag='A', long_name='dimensionless stability parameter', &
             ptr_patch=this%zeta_patch, default='inactive')
        this%vpd_patch(begp:endp) = spval
-       call hist_addfld1d (fname='VPD', units='Pa', &
-            avgflag='A', long_name='vpd', &
+       call hist_addfld1d (fname='VPD', units='kPa', &
+            avgflag='A', long_name='vapour pressure deficit', &
```
Comment (slevis-lmwg) [inline src/biogeophys/FrictionVelocityMod.F90]:
```suggestion
            avgflag='A', long_name='vapor pressure deficit', &
```
...just to keep U.S. rather than U.K. spelling.

**Review by slevis-lmwg — APPROVED** [review]
@mpaiao thank you! Could you give me permission to push to your PR? You do this by:
- clicking Settings near the top of this page, then
- clicking Collaborators and Teams near the top left, and following instructions

**Comment by slevis-lmwg** [comment]
@mpaiao I don't think that I messed anything up by rebasing to b4b-dev, but pls confirm!

**Comment by mpaiao** [comment]
> @mpaiao thank you! Could you give me permission to push to your PR? You do this by:
> 
> * clicking Settings near the top of this page, then
> * clicking Collaborators and Teams near the top left, and following instructions

@slevis-lmwg sure thing, I just added you and @ekluzek as collaborators. Let me know if you have any trouble pushing commits to the PR. Thanks for revising and catching the spelling inconsistency.

**Comment by slevis-lmwg** [comment]
Unlikely to cause failures, but I'm testing on both machines for everyone's sanity :-)
```
OK ./run_sys_tests -s aux_clm -c ctsm5.4.001 --skip-generate
OK ./run_sys_tests -s aux_clm -c ctsm5.4.001 --skip-generate --skip-git-status
```
