### PR TITLE
ctsm5.3.020: Merge b4b-dev 2025-01-16

### LINKED ISSUE #2905: LILAC fails at build phase because of some changes needed for the rpointer handling
### Brief summary of bug

ctsm5.3.015 includes #2757 which includes changes to lnd_comp_nuopc.F90 that need to be moved to lnd_comp_esmf.F90 for LILAC.

 https://github.com/ESCOMP/CTSM/pull/2757/files#diff-f2434c2fccfe6f177f22d26b605bd0f9698f51e85348e9cfdd8a13e4a66a09da

### General bug information

**CTSM version you are using:** ctsm5.3.015 (to be made)
**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** LILAC

### Important details of your setup / configuration so we can reproduce the bug

This test:

LILACSMOKE_D_Ld2.f10_f10_mg37.I2000Ctsm50NwpSpAsRs.derecho_intel.clm-lilac

fails at the BUILD Step because of this.

### PR DESCRIPTION
**Pull request by samsrabin**
### Description of changes

Regular merge of b4b-dev branch into master. Includes some improvements to test list / expected failures.

### Specific notes

**Contributors other than yourself, if any:** None

**CTSM Issues Fixed:**
- Resolves #2905

**Are answers expected to change (and if so in what way)?** No

**Any User Interface Changes (namelist or namelist defaults changes)?** No

**Does this create a need to change or add documentation? Did you do so?** No

**Testing performed, if any:** `aux_clm` passes.

### CODE REVIEW

File: src/cpl/lilac/lnd_comp_esmf.F90 [hunk 1]
```diff
@@ -626,106 +625,106 @@ subroutine lnd_run(gcomp, import_state, export_state, clock, rc)
...
+    !--------------------------------
+
+    call ESMF_ClockGetAlarm(clock, alarmname='lilac_restart_alarm', alarm=alarm, rc=rc)
+    if (ChkErr(rc,__LINE__,u_FILE_u)) return
+
+    if (ESMF_AlarmIsRinging(alarm, rc=rc)) then
        if (ChkErr(rc,__LINE__,u_FILE_u)) return
+       rstwr = .true.
+       call ESMF_AlarmRingerOff( alarm, rc=rc )
+>>>>>>> ctsm5.3.019
```
Comment (slevis-lmwg) [inline src/cpl/lilac/lnd_comp_esmf.F90:714]: Please resolve this conflict with the 019 version.

File: src/cpl/lilac/lnd_comp_esmf.F90 [hunk 2]
```diff
@@ -748,39 +747,57 @@ subroutine lnd_run(gcomp, import_state, export_state, clock, rc)
        !--------------------------------
        ! Run CTSM
        !--------------------------------
+=======
+    call ESMF_ClockGetAlarm(clock, alarmname='lilac_stop_alarm', alarm=alarm, rc=rc)
+    if (ChkErr(rc,__LINE__,u_FILE_u)) return
+>>>>>>> ctsm5.3.019
```
Comment (slevis-lmwg) [inline src/cpl/lilac/lnd_comp_esmf.F90:753]: Please resolve this conflict with the 019 version.

**Review by slevis-lmwg — APPROVED** [review]
I include my conflict resolution suggestions.

Approving the PR preemptively. Thanks @samsrabin.

File: src/cpl/lilac/lnd_comp_esmf.F90 (hunk 1 above)
Comment (slevis-lmwg) [reply src/cpl/lilac/lnd_comp_esmf.F90:714]: @ekluzek suggests reordering the alarms after picking the 019 code, to completely resolve these two conflicts.

Comment (ekluzek) [reply src/cpl/lilac/lnd_comp_esmf.F90:714]: The purpose of the #2912 was to reverse the order that the alarms were set in.

So change it to the ctsm5.3.019 way as @slevis-lmwg points out and then reverse the order of how the alarms are set, which is all that #2912 was doing.

**Review by slevis-lmwg — APPROVED** [review]
@samsrabin thank you! I'm not familiar with every detail here, but things look good from a quick look.
