### PR TITLE
ctsm5.4.012: Fix for C-balance error that manifested in B-cases with pft 67

### LINKED ISSUE #3678: crop C balance error in alpha08a BLT cases
### Brief summary of bug

B1850 cases failing with alpha08a tag

### General bug information

**CTSM version you are using:** [output of `git describe`]
ctsm5.4.003

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]
Yes, model crashes in first years of BLT1850 case

### Details of bug
see errors in [cesm_dev #282](https://github.com/NCAR/cesm_dev/issues/251) and  [cesm_dev #281](https://github.com/NCAR/cesm_dev/issues/250).

TLDR, C balance error in two drifference crop columns that seem to be PFT 67 (sugar cane) 

Reverting crop streams and parameter files to ctsm5.3.002 seems to resolve this issue (currently only 12 year simulations in [cesm_dev #283](https://github.com/NCAR/cesm_dev/issues/252) 

Subsequent simulations by @slevis-lmwg are currently running in clones that 
1) add back in the crop stream files (*283b) or 
2) parameter changes (*283c).

Currently we're assuming this is related to changes to sugar cane parameterization or an issue with crop calendars that came in with the 5.4.003 tag.

Ironically in I cases by:
- @slevis-lmwg with the 003 tag he ran for 200 years.
- @wwieder also run full spinup and historical cases with the 004 tag on both ne30 and f09 grids in lmwg_dev cases 130 and 131 
- @dlawrenncar also noted neither of these were from cesm tags...

@samsrabin we may need your help understanding this one

### PR DESCRIPTION
**Pull request by slevis-lmwg**
### Description of changes
In CNPhenology, I corrected the error by adding a section that I copied from the "else" just below:
``` diff
                if (tlai(p) > 0._r8) then ! plant had emerged before harvest
                   offset_flag(p) = 1._r8
                   offset_counter(p) = dt
+                  ! plant partly emerged from the ground
+                  ! Revert planting transfers; this will replenish the crop seed deficit.
+                  ! We subtract from any existing value in crop_seedc_to_leaf /
+                  ! crop_seedn_to_leaf in the unlikely event that we enter this block of
+                  ! code in the same time step where the planting transfer originally
+                  ! occurred.
+                  if (leafc_xfer(p) > 0._r8) then
+                     crop_seedc_to_leaf(p) = crop_seedc_to_leaf(p) - leafc_xfer(p) / dt
+                     crop_seedn_to_leaf(p) = crop_seedn_to_leaf(p) - leafn_xfer(p) / dt
+                     leafc_xfer(p) = 0._r8
+                     leafn_xfer(p) = leafc_xfer(p) / leafcn_t_evolving(p)
+                     if (use_c13) then
+                        c13_cnveg_carbonstate_inst%leafc_xfer_patch(p) = 0._r8
+                     endif
+                     if (use_c14) then
+                        c14_cnveg_carbonstate_inst%leafc_xfer_patch(p) = 0._r8
+                     endif
+                  end if
                else                      ! plant never emerged from the ground
                   ! Revert planting transfers; this will replenish the crop seed deficit.
                   ! We subtract from any existing value in crop_seedc_to_leaf /
```
To avoid duplication, I propose (and would like @samsrabin to weigh in) this instead:
```
               if (tlai(p) > 0._r8) then ! plant had emerged before harvest
                  offset_flag(p) = 1._r8
                  offset_counter(p) = dt
               end if
               if (leafc_xfer(p) > 0._r8) then  ! plant partly or never emerged from the ground
                  ! Revert planting transfers; this will replenish the crop seed deficit.
                  ! We subtract from any existing value in crop_seedc_to_leaf /
                  ! crop_seedn_to_leaf in the unlikely event that we enter this block of
                  ! code in the same time step where the planting transfer originally
                  ! occurred.
                  crop_seedc_to_leaf(p) = crop_seedc_to_leaf(p) - leafc_xfer(p)/dt
                  crop_seedn_to_leaf(p) = crop_seedn_to_leaf(p) - leafn_xfer(p)/dt
                  leafc_xfer(p) = 0._r8
                  leafn_xfer(p) = leafc_xfer(p) / leafcn_t_evolving(p)
                  if (use_c13) then
                     c13_cnveg_carbonstate_inst%leafc_xfer_patch(p) = 0._r8
                  endif
                  if (use_c14) then
                     c14_cnveg_carbonstate_inst%leafc_xfer_patch(p) = 0._r8
                  endif
               end if
```
### Specific notes

Contributors other than yourself, if any:
@samsrabin 

CTSM Issues Fixed (include github issue #):
Fixes #3678 

Are answers expected to change (and if so in what way)?
Rarely, considering that this error never got triggered in I-cases.

Any User Interface Changes (namelist or namelist defaults changes)?
No.

Does this create a need to change or add documentation? Did you do so?
Is this part of CNPhenology documented in the Technote? If so, it needs updating.

Testing performed so far:
Case `/glade/u/home/slevis/cases_ctsm5.4/b.e30_alpha08a.B1850C_LTso.ne30_t232_wgx3.283d` with ctsm5.4.005 replacing ctsm5.4.003:
- The error was triggered exactly at the year transition from 0019 to 0020, making restarts possible and failures quick. 
- The error was NOT triggered when I included the code change coming in with the first commit of this PR. Ran out of wallclock because I gave it 11 minutes.
- The error was NOT triggered when I included the alternate solution, either. I confirmed b4b by comparing these files:
```
b.e30_alpha08a.B1850C_LTso.ne30_t232_wgx3.283d.cam.h3a.0020-01-16-10800.nc
b.e30_alpha08a.B1850C_LTso.ne30_t232_wgx3.283d.cam.h3a.0020-01-16-10800bkup.nc
```
I allowed this one to run for 4 yrs.

### CODE REVIEW

File: src/biogeochem/CNPhenologyMod.F90 [hunk 1]
```diff
@@ -2553,6 +2553,24 @@ subroutine CropPhenology(num_pcropp, filter_pcropp                     , &
...
+                     crop_seedn_to_leaf(p) = crop_seedn_to_leaf(p) - leafn_xfer(p) / dt
+                     leafc_xfer(p) = 0._r8
+                     leafn_xfer(p) = leafc_xfer(p) / leafcn_t_evolving(p)
+                     if (use_c13) then
+                        c13_cnveg_carbonstate_inst%leafc_xfer_patch(p) = 0._r8
+                     endif
+                     if (use_c14) then
+                        c14_cnveg_carbonstate_inst%leafc_xfer_patch(p) = 0._r8
+                     endif
+                  end if
```
Comment (slevis-lmwg) [inline src/biogeochem/CNPhenologyMod.F90:2573]:
```suggestion
               end if
               ! plant partly emerged from the ground
               ! Revert planting transfers; this will replenish the crop seed deficit.
               ! We subtract from any existing value in crop_seedc_to_leaf /
               ! crop_seedn_to_leaf in the unlikely event that we enter this block of
               ! code in the same time step where the planting transfer originally
               ! occurred.
               if (leafc_xfer(p) > 0._r8) then  ! TODO slevis Merge w the next else?
                  crop_seedc_to_leaf(p) = crop_seedc_to_leaf(p) - leafc_xfer(p) / dt
                  crop_seedn_to_leaf(p) = crop_seedn_to_leaf(p) - leafn_xfer(p) / dt
                  leafc_xfer(p) = 0._r8
                  leafn_xfer(p) = leafc_xfer(p) / leafcn_t_evolving(p)
                  if (use_c13) then
                     c13_cnveg_carbonstate_inst%leafc_xfer_patch(p) = 0._r8
                  endif
                  if (use_c14) then
                     c14_cnveg_carbonstate_inst%leafc_xfer_patch(p) = 0._r8
                  endif
               end if
```
This is what I'm proposing to avoid code duplication, but I want @samsrabin's eyes on it before I make the change.

Comment (samsrabin) [reply src/biogeochem/CNPhenologyMod.F90:2573]: It's kinda hard to see what's going on here, so go ahead and apply it, then I will look at the individual commits to see what differs.

File: src/biogeochem/CNPhenologyMod.F90 [hunk 2]
```diff
@@ -2553,14 +2553,16 @@ subroutine CropPhenology(num_pcropp, filter_pcropp                     , &
...
-                  crop_seedc_to_leaf(p) = crop_seedc_to_leaf(p) - leafc_xfer(p)/dt
-                  crop_seedn_to_leaf(p) = crop_seedn_to_leaf(p) - leafn_xfer(p)/dt
+               end if
+               ! plant partly emerged from the ground
+               ! Revert planting transfers; this will replenish the crop seed deficit.
+               ! We subtract from any existing value in crop_seedc_to_leaf /
+               ! crop_seedn_to_leaf in the unlikely event that we enter this block of
+               ! code in the same time step where the planting transfer originally
+               ! occurred.
+               if (leafc_xfer(p) > 0._r8) then  ! TODO slevis Merge w the next else?
```
Comment (slevis-lmwg) [inline src/biogeochem/CNPhenologyMod.F90]:
```suggestion
               if (leafc_xfer(p) > 0._r8) then
```
@samsrabin the alternate solution is easiest to view by looking at "All commits" and removing whitespace.

**Comment by slevis-lmwg** [comment]
- [x] derecho with the second solution, the one that avoids code duplication:
`./run_sys_tests -s aux_clm -c ctsm5.4.010 --skip-generate`
```
ERI_D.ne30pg3_t232.I1850Clm60BgcCropG.derecho_intel.clm-clm60cam7LndTuningModeLDust COMPARE_base_hybrid
ERP_P64x2_Ld765.f10_f10_mg37.I2000Clm60BgcCrop.derecho_intel.clm-monthly BASELINE ctsm5.4.010: DIFF
ERS_Ly3.f10_f10_mg37.I2000Clm60BgcCrop.derecho_intel BASELINE ctsm5.4.010: DIFF
SMS_Ly2_PS.f19_g17.I2000Clm60BgcCrop.derecho_intel.clm-cropMonthOutput BASELINE ctsm5.4.010: DIFF
```
The ERI failure does not occur with the first solution (see next).
- [x] derecho + izumi with the first solution:
`./run_sys_tests -s aux_clm -c ctsm5.4.010 -g pr3702opt1-ctsm5.4.010`
Same three DIFFs on derecho:
```
ERP_P64x2_Ld765.f10_f10_mg37.I2000Clm60BgcCrop.derecho_intel.clm-monthly BASELINE ctsm5.4.010: DIFF
ERS_Ly3.f10_f10_mg37.I2000Clm60BgcCrop.derecho_intel BASELINE ctsm5.4.010: DIFF
SMS_Ly2_PS.f19_g17.I2000Clm60BgcCrop.derecho_intel.clm-cropMonthOutput BASELINE ctsm5.4.010: DIFF
SMS_D_Ld65.f10_f10_mg37.I2000Clm60BgcCrop.izumi_nag.clm-FireLi2024GSWP BASELINE ctsm5.4.010: DIFF
```
- [x] Conclusion: I will revert to the first of the two solutions.
- [x] Update ChangeLog/Sum

**Comment by samsrabin** [comment]
This makes a lot of sense, thanks! It looks like you're testing now with 5df9554 (the latest commit). It would be good to compare the results of that to a086708 (the first commit) to ensure that the logic change really is bit-for-bit.

Mark it as "ready for review" whenever you're ready and I'll approve.

**Comment by slevis-lmwg** [comment]
Rerunning aux_clm after updating to the latest master
`./run_sys_tests -s aux_clm -c ctsm5.4.011 -g ctsm5.4.012`

**Comment by slevis-lmwg** [comment]
I get one unexpected failure that has a history of appearing periodically, so I will ignore it:
`ERI_D.ne30pg3_t232.I1850Clm60BgcCropG.derecho_intel.clm-clm60cam7LndTuningModeLDust COMPARE_base_hybrid`
`RMS DPFCT_ROCK                       1.8239E-04            NORMALIZED  3.2752E-04`

Here is a record of previous appearances of this failure:
https://github.com/ESCOMP/CTSM/pull/3063#issuecomment-2828423157
https://github.com/ESCOMP/CTSM/pull/2806
https://github.com/ESCOMP/CTSM/pull/2084#issuecomment-2483588443
https://github.com/ESCOMP/CTSM/pull/2052#issuecomment-2487025780

The field was originally introduced in https://github.com/ESCOMP/CTSM/pull/1897

I will open an issue with the above information. Also note that this is the same error that swayed me against using the "second solution" in this PR, because aux_clm with option 1 before updating to ctsm5.4.011 did not give this error. At this point I will not revisit that question. I will rerun the test to see if it's reproducible:
```
./case.setup --reset
./case.build --clean
./case.build
./case.submit
```
I didn't expect this, but the rerun worked!
