### PR TITLE
Start bringing in carbon isotopes in streams

### LINKED ISSUE #3502: Time interpolation for Carbon isotope datasets is done incorrectly
### Brief summary of bug

The time interpolation of the C13 and C14 isotope datasets is supposed to be linear between each year. It looks like in practice it mostly uses the yearly values, with some smoothing between years.

### General bug information

**CTSM version you are using:** branch_tags/CMIP7_ciso.n01.alpha-ctsm5.4.CMIP7.11.ctsm5.3.075

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** when use_c13 or use_c14 is on with transient datasets

### Important details of your setup / configuration so we can reproduce the bug

Start with this test case:

`SMS_Ly3.f10_f10_mt232.IHistClm60BgcCropCrujra.derecho_intel.clm-monthly--clm-clm60cam7LndTuningMode_2013Start`

Edit the user_nl_clm file and add this line:

``` fortran
 hist_fincl1   += 'FCO2', 'RC13_CANAIR', 'RC14_CANAIR'
```

And make sure output is going to be monthly

Run the case then do the following to look at the output:

``` shell
# Concatenate the monthly files together in one file
ncrcat -O -v RC13_CANAIR,RC14_CANAIR $RUNDIR/SMS*.clm2.h0a*.nc allmonths.h0a.nc
# Use ncap2 to convert RC13_CANAIR and RC14_CANAIR to Delta format
ncap2 -s 'c14ratio = 1.e-12' -s 'PDB = 0.0112372' -s 'preind_atm_del13c = -6.' -s 'preind_atm_ratio = PDB + ( preind_atm_del13c * PDB ) /1000.0' -s 'c13ratio = preind_atm_ratio/ ( 1.0+preind_atm_ratio ) ' -s 'Deltac13 = ( RC13_CANAIR/PDB - 1.0 ) /1.0e-3' -s 'Deltac14 = ( RC14_CANAIR/c14ratio - 1.0 ) /1.0e-3' -O allmonths.h0a.nc test.nc
```

The output Deltac13 and Deltac14 will be close to a step function with some smoothing between years.

### PR DESCRIPTION
**Pull request by ekluzek**
### Description of changes

Bring in the capability to read in Carbon isotopes in streams. There will be other changes to fully flesh this out. And a version that allows it to be turned on instead of the current file method. The final thing will be a tag on master to change the default to only using streams. And then on b4b-dev we can remove the old version.

### Specific notes

Contributors other than yourself, if any:

CTSM Issues Fixed (include github issue #):

  Design notes in #3546
  Fixes #3502
  Work on #3346

Are answers expected to change (and if so in what way)? No

Any User Interface Changes (namelist or namelist defaults changes)? Yes
   New namelist options for stream handling will come in:

- stream_fldfilename_atm_c14
- stream_meshfile_atm_c14
- stream_year_first_atm_c14
- stream_year_last_atm_c14
- stream_fldfilename_atm_c13
- stream_year_first_atm_c13
- stream_year_last_atm_c13

Does this create a need to change or add documentation? Did you do so? No No

Testing performed, if any: Single case testing so far, will run aux_clm
  Currently just running an SMS test: SMS_D_Ld3.f10_f10_mt232.IHistClm60BgcCropCrujra.derecho_intel.clm-clm60cam7LndTuningMode
  Will transition to the 3-year test starting in Dec/2013 used previously

### CODE REVIEW

**Comment by ekluzek** [comment]
The read is working now, so it needs more testing to ensure it's correct as well as review and some further updates we'll figure out in the reveiw.

File: src/cpl/share_esmf/CTSMForce2DStreamBaseType.F90 [hunk 1]
```diff
@@ -0,0 +1,178 @@
+module CTSMForce2DStreamBaseType
+
```
Comment (ekluzek) [inline src/cpl/share_esmf/CTSMForce2DStreamBaseType.F90:2]: @slevis-lmwg and I went over the basic name and it makes sense to both of us.

I will need to add comments and descriptions, now that the code is working and we think the names are OK.

File: src/cpl/share_esmf/CTSMForce2DStreamBaseType.F90 [hunk 2]
```diff
@@ -0,0 +1,178 @@
...
+  use decompMod , only : bounds_type
+  use clm_varctl, only : FL => fname_len
+
+  implicit none
+  private
+
+  type, abstract, public :: ctsm_force_2DStream_base_type
+     private
+     type(shr_strdata_type), public :: sdat  ! Stream data type
+     character(len=FL) :: stream_filename ! The stream data filename (also in sdat)
```
Comment (ekluzek) [inline src/cpl/share_esmf/CTSMForce2DStreamBaseType.F90:35]: Do I really need these here? Can I use the data in sdat?

File: src/biogeochem/AtmCarbonIsotopeStreamType.F90 [hunk 3]
```diff
@@ -0,0 +1,193 @@
...
+    subroutine C13Interp( this, bounds )
+         class(atm_delta_c13_stream_type), intent(inout) :: this 
+         type(bounds_type), intent(in) :: bounds
+
+         ! Local Variables
+         integer :: g
+         real(r8), pointer :: dataptr1d(:)
+         integer :: rc ! error return code
+
+         ! Get pointer for stream data that is time and spatially interpolated to model time and grid
```
Comment (ekluzek) [inline src/biogeochem/AtmCarbonIsotopeStreamType.F90:144]: This bit about getting the pointer to data could be put in the base type.

File: src/biogeochem/AtmCarbonIsotopeStreamType.F90 [hunk 4]
```diff
@@ -0,0 +1,193 @@
+module AtmCarbonIsotopeStreamType
+  use shr_kind_mod , only : r8 => shr_kind_r8
```
Comment (ekluzek) [inline src/biogeochem/AtmCarbonIsotopeStreamType.F90:8]: Need to add notes and descriptions and general comments, now that the general structure is approved.

File: src/biogeochem/AtmCarbonIsotopeStreamType.F90 [hunk 5]
```diff
@@ -0,0 +1,193 @@
+module AtmCarbonIsotopeStreamType
```
Comment (ekluzek) [inline src/biogeochem/AtmCarbonIsotopeStreamType.F90:1]: This puts both C13 and C14 in the same file -- it could be separated into two files.

File: src/biogeochem/CNCIsoAtmTimeSeriesReadMod.F90 [hunk 6]
```diff
@@ -33,13 +35,33 @@ module CIsoAtmTimeseriesMod
...
+  type(atm_delta_c14_stream_type), private :: atm_c14_stream  ! Atmospheric C14 stream object
+
   ! !PRIVATE TYPES:
   real(r8), allocatable, private :: atm_c14file_time(:)       ! time for C14 data
   real(r8), allocatable, private :: atm_delta_c14(:,:)        ! Delta C14 data
   real(r8), allocatable, private :: atm_c13file_time(:)       ! time for C13 data
   real(r8), allocatable, private :: atm_delta_c13(:)          ! Delta C13 data
   real(r8), parameter :: time_axis_offset = 1850.0_r8         ! Offset in years of time on file
 
+  ! Private data for the control namelist:
```
Comment (ekluzek) [inline src/biogeochem/CNCIsoAtmTimeSeriesReadMod.F90:64]: This needs to become an actual namelist and added to namelist defaults all the things.

Comment (ekluzek) [reply src/biogeochem/CNCIsoAtmTimeSeriesReadMod.F90:64]: At least the filenames need to be done this way.

File: src/biogeochem/AtmCarbonIsotopeStreamType.F90 (hunk 5 above)
Comment (ekluzek) [reply src/biogeochem/AtmCarbonIsotopeStreamType.F90:1]: We decided one file makes sense here.

File: src/biogeochem/AtmCarbonIsotopeStreamType.F90 (hunk 3 above)
Comment (ekluzek) [reply src/biogeochem/AtmCarbonIsotopeStreamType.F90:144]: I figured out what to do here in #3566 the data can be directly accessed from here.

File: bld/CLMBuildNamelist.pm [hunk 7]
```diff
@@ -3753,48 +3757,92 @@ sub setup_logic_c_isotope {
...
+}
+
+#-------------------------------------------------------------------------------
+
+sub setup_logic_c14_streams {
+  my ($opts, $nl_flags, $definition, $defaults, $nl) = @_;
+  #
+  # C14 stream file settings
+  #
+}
```
Comment (slevis-lmwg) [inline bld/CLMBuildNamelist.pm:3844]: Currently these don't do much. Do you plan to move code from `sub setup_logic_c_isotope` to here later?

File: src/biogeochem/AtmCarbonIsotopeStreamType.F90 (hunk 3 above)
Comment (ekluzek) [reply src/biogeochem/AtmCarbonIsotopeStreamType.F90:144]: I put this in the base type which turned out to be needed to get unit testing working.

File: bld/CLMBuildNamelist.pm (hunk 7 above)
Comment (ekluzek) [reply bld/CLMBuildNamelist.pm:3844]: This will grow as there becomes handling for all the streams namelist items. So it's just a starting point right now.

File: src/biogeochem/CNCIsoAtmTimeSeriesReadMod.F90 (hunk 6 above)
Comment (ekluzek) [reply src/biogeochem/CNCIsoAtmTimeSeriesReadMod.F90:64]: This is done.

File: src/cpl/share_esmf/CTSMForce2DStreamBaseType.F90 (hunk 1 above)
Comment (ekluzek) [reply src/cpl/share_esmf/CTSMForce2DStreamBaseType.F90:2]: OK, I've added comments and descriptions.

File: src/cpl/share_esmf/CTSMForce2DStreamBaseType.F90 (hunk 2 above)
Comment (ekluzek) [reply src/cpl/share_esmf/CTSMForce2DStreamBaseType.F90:35]: In looking at this we'd need to go several type layers down

sdat%stream%file(1)%name

And it looks like stream_name isn't really kept after initialization.

File: src/biogeochem/AtmCarbonIsotopeStreamType.F90 (hunk 4 above)
Comment (ekluzek) [reply src/biogeochem/AtmCarbonIsotopeStreamType.F90:8]: I did this now.

**Comment by ekluzek** [comment]
Reviewing this for post Sprint 25. It looks like time for this is divided up as follows:

- Few days for putting the basic structure in place
- Few days for figuring out the options and flow and test that it's correct
- Few days for working through miscellaneous issues
- Few days for adding the new namelist items and a new test with them
